import {useCallback,useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {api,patch,post,put,session,type Workspace} from './api';
import MarketingCenter from './MarketingCenter';
import ComplianceCenter from './ComplianceCenter';

type Dashboard={workspace?:{id:string;name:string;role:string};crm?:{deals:number;open_deals:number;open_pipeline_minor:number;won_month:number};finance?:{income_paid_minor:number;expense_paid_minor:number;receivable_minor:number;payable_minor:number;overdue_count:number};command?:{open_actions:number};approvals?:{pending_approvals:number};tasks?:{due_tasks:number};appointments?:{today_appointments:number};usage?:any[]};
type Action={id:string;agent_role:string;title:string;summary:string;priority:string;autonomy:string;status:string;approval_id?:string|null;created_at:string};
type Contact={id:string;kind:string;name:string;email?:string;phone?:string;company_name?:string;source?:string;tags?:string[]};
type Deal={id:string;contact_id?:string;contact_name?:string;title:string;stage:string;value_minor:number|string;next_action?:string;source?:string};
type Ledger={id:string;direction:'income'|'expense';category:string;description:string;amount_minor:number|string;status:string;due_at?:string;paid_at?:string;contact_name?:string;account_name?:string};
type Task={id:string;title:string;description?:string;status:string;priority:string;due_at?:string;contact_name?:string};
type Appointment={id:string;title:string;status:string;starts_at:string;ends_at?:string;contact_name?:string};
type Policy={id:string;action_type:string;mode:string};
type Integration={id:string;provider:string;status:string;capabilities:string[]};
type Member={id:string;name:string;email:string;role:string;active:boolean;permissions:string[]};
type FinanceAccount={id:string;name:string;kind:string};

const stages=['lead','qualified','meeting','proposal','won','lost'];
const stageLabel:Record<string,string>={lead:'Lead',qualified:'Qualificado',meeting:'Reunião',proposal:'Proposta',won:'Ganho',lost:'Perdido'};
const roleNames:Record<string,string>={secretary:'Sofia · Secretária',service:'Alex · Atendimento',crm:'Clara · CRM',erp:'Nico · ERP',collections:'Theo · Cobrança',controller:'Theo · Controller',documents:'Dora · Documentos',growth:'Maya · Growth'};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const date=(value?:string)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';
const toIso=(local:string)=>local?new Date(local).toISOString():null;

export default function App(){
  const [authReady,setAuthReady]=useState(false);const [user,setUser]=useState<any>(null);const [workspaces,setWorkspaces]=useState<Workspace[]>([]);
  const [view,setView]=useState('command');const [dashboard,setDashboard]=useState<Dashboard>({});const [actions,setActions]=useState<Action[]>([]);const [contacts,setContacts]=useState<Contact[]>([]);const [deals,setDeals]=useState<Deal[]>([]);const [ledger,setLedger]=useState<Ledger[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [appointments,setAppointments]=useState<Appointment[]>([]);const [policies,setPolicies]=useState<Policy[]>([]);const [integrations,setIntegrations]=useState<Integration[]>([]);const [members,setMembers]=useState<Member[]>([]);const [accounts,setAccounts]=useState<FinanceAccount[]>([]);
  const [modal,setModal]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');

  const loadMe=useCallback(async()=>{const me=await api<any>('/v1/auth/me');setUser(me.user);setWorkspaces(me.workspaces||[]);if(!session.workspace()&&me.workspaces?.[0])session.setWorkspace(me.workspaces[0].id);const invite=new URLSearchParams(location.search).get('invite');if(invite){try{const accepted=await post<any>('/v1/invites/accept',{token:invite});if(accepted.workspaceId)session.setWorkspace(accepted.workspaceId);history.replaceState({},'',location.pathname)}catch{} }return me},[]);
  const refresh=useCallback(async()=>{if(!session.token())return;setError('');try{const [d,a,c,de,l,t,ap,p,i,m,fa]=await Promise.all([api<Dashboard>('/v1/dashboard'),api<Action[]>('/v1/command/actions'),api<Contact[]>('/v1/crm/contacts'),api<Deal[]>('/v1/crm/deals'),api<Ledger[]>('/v1/ledger'),api<Task[]>('/v1/tasks'),api<Appointment[]>('/v1/appointments'),api<Policy[]>('/v1/autonomy-policies'),api<Integration[]>('/v1/integrations'),api<Member[]>('/v1/members'),api<FinanceAccount[]>('/v1/finance/accounts')]);setDashboard(d);setActions(a);setContacts(c);setDeals(de);setLedger(l);setTasks(t);setAppointments(ap);setPolicies(p);setIntegrations(i);setMembers(m);setAccounts(fa)}catch(e:any){if(e?.status===401){session.clear();setUser(null);setWorkspaces([])}else setError(e?.message||'Não foi possível atualizar os dados.')}},[]);

  useEffect(()=>{(async()=>{if(session.token()){try{await loadMe();await refresh()}catch{session.clear()}}setAuthReady(true)})()},[loadMe,refresh]);
  if(!authReady)return <div className="splash">NexOffice</div>;
  if(!user)return <AuthScreen onDone={async(token,workspaceId)=>{session.set(token,workspaceId);await loadMe();await refresh()}}/>;

  const activeWorkspace=workspaces.find(w=>w.id===session.workspace())||workspaces[0];
  const switchWorkspace=async(id:string)=>{session.setWorkspace(id);setBusy(true);await refresh();setBusy(false)};
  const openPipeline=dashboard.crm?.open_pipeline_minor||0;const balance=Number(dashboard.finance?.income_paid_minor||0)-Number(dashboard.finance?.expense_paid_minor||0);
  const nav=[['command','Central de Comando','◈'],['crm','CRM','◎'],['finance','Financeiro','▤'],['agenda','Agenda & Tarefas','◷'],['documents','Documentos','▱'],['team','Equipe Digital','✦'],['marketing','Marketing','◉'],['compliance','Compliance','✓'],['integrations','Integrações','⇄'],['settings','Empresa & Acessos','⚙']];

  async function act(actionId:string,decision:'approved'|'rejected'|'dismissed'){setBusy(true);try{await post(`/v1/command/actions/${actionId}/decision`,{decision});await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function moveDeal(id:string,stage:string){await patch(`/v1/crm/deals/${id}`,{stage});await refresh()}
  async function updateTask(id:string,status:string){await patch(`/v1/tasks/${id}`,{status});await refresh()}
  async function updateAppointment(id:string,status:string){await patch(`/v1/appointments/${id}`,{status});await refresh()}
  async function markPaid(id:string){await patch(`/v1/ledger/${id}`,{status:'paid'});await refresh()}

  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brandMark">N</div><div><strong>NexOffice</strong><small>Sistema operacional do seu negócio</small></div></div><nav>{nav.map(([key,label,icon])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}><span>{icon}</span>{label}</button>)}</nav><div className="sideFoot"><div className="statusDot"/> Core v0.2 · Live</div></aside>
    <main><header className="topbar"><div><p className="eyebrow">NEXOFFICE</p><h1>{title(view)}</h1><p>O sistema operacional do seu negócio.</p></div><div className="topActions"><select value={activeWorkspace?.id||''} onChange={e=>switchWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><div className="userChip"><b>{user.name}</b><small>{activeWorkspace?.role}</small></div><button className="ghost" onClick={async()=>{try{await post('/v1/auth/logout',{})}catch{}session.clear();location.reload()}}>Sair</button></div></header>
    <section className="content">{error&&<div className="errorBanner">{error}<button onClick={()=>setError('')}>×</button></div>}{busy&&<div className="busyLine"/>}{renderView()}</section></main>
    {modal&&<Modal onClose={()=>setModal(null)}>{renderModal()}</Modal>}
  </div>;

  function renderView():ReactNode{
    if(view==='command')return <><div className="hero"><div><p className="eyebrow">CENTRAL DE COMANDO</p><h2>{actions.length?`Você tem ${actions.length} pontos para acompanhar.`:'Seu negócio está em ordem agora.'}</h2><p>Eventos do CRM, agenda, financeiro e integrações viram ações priorizadas para sua equipe digital.</p></div><div className="heroActions"><button className="primary" onClick={()=>setView('team')}>Conversar com a equipe</button><button onClick={()=>refresh()}>Atualizar</button></div></div><div className="kpis"><Kpi label="Pipeline aberto" value={money(openPipeline)} hint={`${dashboard.crm?.open_deals||0} oportunidades`}/><Kpi label="Saldo realizado" value={money(balance)} hint="receitas − despesas"/><Kpi label="A receber" value={money(dashboard.finance?.receivable_minor)} hint={`${dashboard.finance?.overdue_count||0} vencidos`}/><Kpi label="Decisões pendentes" value={String(dashboard.approvals?.pending_approvals||0)} hint="aprovações humanas"/></div><div className="twoCol"><Panel eyebrow="ACTION INBOX" title="O que precisa de você" badge={actions.length}><div className="actionList">{actions.length?actions.map(a=><ActionCard key={a.id} action={a} onDecision={d=>act(a.id,d)}/>):<Empty text="Nenhuma ação pendente."/>}</div></Panel><Panel eyebrow="PULSO DO NEGÓCIO" title="Agora"><Pulse label="CRM" value={`${dashboard.crm?.open_deals||0} negócios abertos`} detail={money(openPipeline)}/><Pulse label="Financeiro" value={`${dashboard.finance?.overdue_count||0} cobranças vencidas`} detail={money(dashboard.finance?.receivable_minor)}/><Pulse label="Agenda" value={`${dashboard.appointments?.today_appointments||0} compromissos hoje`} detail={`${dashboard.tasks?.due_tasks||0} tarefas próximas`}/><Pulse label="Equipe Digital" value={`${dashboard.command?.open_actions||0} ações na fila`} detail={`${policies.length} políticas de autonomia`}/></Panel></div></>;
    if(view==='crm')return <CRM contacts={contacts} deals={deals} onNewContact={()=>setModal('contact')} onNewDeal={()=>setModal('deal')} onMove={moveDeal}/>;
    if(view==='finance')return <Finance ledger={ledger} dashboard={dashboard} onNew={()=>setModal('ledger')} onPaid={markPaid}/>;
    if(view==='agenda')return <Agenda tasks={tasks} appointments={appointments} onTask={()=>setModal('task')} onAppointment={()=>setModal('appointment')} onTaskStatus={updateTask} onAppointmentStatus={updateAppointment}/>;
    if(view==='documents')return <Documents/>;
    if(view==='team')return <Team policies={policies} onEdit={p=>setModal(`policy:${p.action_type}`)}/>;
    if(view==='marketing')return <MarketingCenter workspaceId={activeWorkspace?.id||''}/>;
    if(view==='compliance')return <ComplianceCenter/>;
    if(view==='integrations')return <Integrations current={integrations}/>;
    return <Settings members={members} workspace={activeWorkspace} onInvite={()=>setModal('invite')} onNewWorkspace={()=>setModal('workspace')}/>;
  }

  function renderModal():ReactNode{
    const close=()=>setModal(null);const submit=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();close();await refresh()}catch(e:any){setError(e?.message||'Erro ao salvar.')}finally{setBusy(false)}};
    if(modal==='contact')return <Form title="Novo contato" submit={e=>{const f=data(e);return submit(()=>post('/v1/crm/contacts',{kind:f.kind,name:f.name,email:f.email||null,phone:f.phone||null,companyName:f.companyName||null,source:f.source||null,tags:String(f.tags||'').split(',').map(x=>x.trim()).filter(Boolean)}))}}><Field name="kind" label="Tipo" select={['person:Pessoa','company:Empresa']}/><Field name="name" label="Nome" required/><Field name="companyName" label="Empresa / organização"/><Field name="email" label="E-mail" type="email"/><Field name="phone" label="Telefone / WhatsApp"/><Field name="source" label="Origem"/><Field name="tags" label="Tags" placeholder="cliente, indicação, prioridade"/></Form>;
    if(modal==='deal')return <Form title="Nova oportunidade" submit={e=>{const f=data(e);return submit(()=>post('/v1/crm/deals',{contactId:f.contactId||null,title:f.title,stage:f.stage,valueMinor:Math.round(Number(f.value||0)*100),source:f.source||null,nextAction:f.nextAction||null}))}}><Field name="contactId" label="Contato" options={contacts.map(c=>[c.id,c.name])}/><Field name="title" label="Oportunidade" required/><Field name="stage" label="Etapa" select={stages.map(s=>`${s}:${stageLabel[s]}`)}/><Field name="value" label="Valor potencial (R$)" type="number"/><Field name="source" label="Origem"/><Field name="nextAction" label="Próxima ação"/></Form>;
    if(modal==='ledger')return <Form title="Novo lançamento" submit={e=>{const f=data(e);return submit(()=>post('/v1/ledger',{contactId:f.contactId||null,accountId:f.accountId||null,direction:f.direction,category:f.category,description:f.description,amountMinor:Math.round(Number(f.amount)*100),status:f.status,dueAt:toIso(f.dueAt)}))}}><Field name="direction" label="Tipo" select={['income:Receita','expense:Despesa']}/><Field name="description" label="Descrição" required/><Field name="category" label="Categoria" required/><Field name="amount" label="Valor (R$)" type="number" required/><Field name="status" label="Status" select={['open:Em aberto','planned:Planejado','paid:Pago','overdue:Vencido']}/><Field name="dueAt" label="Vencimento" type="datetime-local"/><Field name="contactId" label="Contato" options={contacts.map(c=>[c.id,c.name])}/><Field name="accountId" label="Conta" options={accounts.map(a=>[a.id,a.name])}/></Form>;
    if(modal==='task')return <Form title="Nova tarefa" submit={e=>{const f=data(e);return submit(()=>post('/v1/tasks',{title:f.title,description:f.description||null,priority:f.priority,dueAt:toIso(f.dueAt),contactId:f.contactId||null}))}}><Field name="title" label="Tarefa" required/><Field name="description" label="Descrição"/><Field name="priority" label="Prioridade" select={['normal:Normal','high:Alta','critical:Crítica','low:Baixa']}/><Field name="dueAt" label="Prazo" type="datetime-local"/><Field name="contactId" label="Contato" options={contacts.map(c=>[c.id,c.name])}/></Form>;
    if(modal==='appointment')return <Form title="Novo compromisso" submit={e=>{const f=data(e);return submit(()=>post('/v1/appointments',{title:f.title,startsAt:toIso(f.startsAt),endsAt:toIso(f.endsAt),contactId:f.contactId||null,status:'scheduled'}))}}><Field name="title" label="Compromisso" required/><Field name="startsAt" label="Início" type="datetime-local" required/><Field name="endsAt" label="Fim" type="datetime-local"/><Field name="contactId" label="Contato" options={contacts.map(c=>[c.id,c.name])}/></Form>;
    if(modal==='invite')return <Form title="Convidar para a empresa" submit={e=>{const f=data(e);return submit(async()=>{const r=await post<any>('/v1/members/invite',{email:f.email,role:f.role});await navigator.clipboard?.writeText(r.inviteUrl||r.inviteToken);alert(`Convite criado. Link copiado:\n${r.inviteUrl||r.inviteToken}`)})}}><Field name="email" label="E-mail" type="email" required/><Field name="role" label="Perfil" select={['member:Membro','admin:Administrador','viewer:Somente leitura']}/></Form>;
    if(modal==='workspace')return <Form title="Novo workspace" submit={e=>{const f=data(e);return submit(async()=>{const w=await post<any>('/v1/workspaces',{name:f.name,vertical:f.vertical});session.setWorkspace(w.id);await loadMe()})}}><Field name="name" label="Nome do negócio" required/><Field name="vertical" label="Perfil inicial" select={['general:Geral','legal:Jurídico','health:Saúde','condo:Condomínios','commerce:Comércio']}/></Form>;
    if(modal?.startsWith('policy:')){const actionType=modal.slice(7);const p=policies.find(x=>x.action_type===actionType);return <Form title={`Autonomia · ${actionType}`} submit={e=>{const f=data(e);return submit(()=>put(`/v1/autonomy-policies/${encodeURIComponent(actionType)}`,{mode:f.mode}))}}><Field name="mode" label="Modo" defaultValue={p?.mode} select={['approval_required:Pedir aprovação','notify:Executar/organizar e avisar','automatic:Automático']}/><p className="formHint">Ações sensíveis continuam bloqueadas pelas políticas do core. Use automático somente em rotinas de baixo risco.</p></Form>}
    return null;
  }
}

function AuthScreen({onDone}:{onDone:(token:string,workspaceId?:string)=>Promise<void>}){const invite=new URLSearchParams(location.search).get('invite')||'';const [mode,setMode]=useState<'login'|'register'>(invite?'register':'login');const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=data(e);try{if(mode==='login'){const r=await post<any>('/v1/auth/login',{email:f.email,password:f.password});await onDone(r.token)}else{const r=await post<any>('/v1/auth/register',{name:f.name,email:f.email,password:f.password,businessName:invite?undefined:f.businessName,vertical:f.vertical||'general',inviteToken:invite||undefined});await onDone(r.token,r.workspace?.id)}}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <div className="authPage"><div className="authBrand"><div className="brandMark large">N</div><h1>NexOffice</h1><p>O sistema operacional do seu negócio.</p><div className="authPromise"><span>CRM</span><span>Agenda</span><span>Financeiro</span><span>Documentos</span><span>Equipe digital</span><span>Growth</span></div></div><form className="authCard" onSubmit={submit}><p className="eyebrow">{mode==='login'?'ENTRAR':'COMEÇAR'}</p><h2>{mode==='login'?'Acesse seu negócio':invite?'Aceitar convite':'Crie seu NexOffice'}</h2>{mode==='register'&&<><Field name="name" label="Seu nome" required/>{!invite&&<><Field name="businessName" label="Nome do negócio" required/><Field name="vertical" label="Perfil inicial" select={['general:Geral','legal:Jurídico','health:Saúde','condo:Condomínios','commerce:Comércio']}/></>} </>}<Field name="email" label="E-mail" type="email" required/><Field name="password" label="Senha" type="password" required/>{mode==='register'&&<small className="formHint">Use pelo menos 8 caracteres.</small>}{error&&<div className="formError">{error}</div>}<button className="primary authSubmit" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar':invite?'Entrar na empresa':'Criar workspace'}</button>{!invite&&<button type="button" className="linkButton" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Ainda não tenho conta':'Já tenho conta'}</button>}</form></div>}

function CRM({contacts,deals,onNewContact,onNewDeal,onMove}:{contacts:Contact[];deals:Deal[];onNewContact:()=>void;onNewDeal:()=>void;onMove:(id:string,stage:string)=>void}){return <><div className="moduleIntro split"><div><p className="eyebrow">CRM CORE</p><h2>Relacionamento comercial único</h2><p>Leads, clientes, atividades e oportunidades conectados à agenda, ao financeiro e à equipe digital.</p></div><div className="buttons"><button onClick={onNewContact}>+ Contato</button><button className="primary" onClick={onNewDeal}>+ Oportunidade</button></div></div><div className="crmStats"><Kpi label="Contatos" value={String(contacts.length)} hint="base ativa"/><Kpi label="Pipeline" value={money(deals.filter(d=>!['won','lost'].includes(d.stage)).reduce((s,d)=>s+Number(d.value_minor),0))} hint="oportunidades abertas"/><Kpi label="Ganhos" value={String(deals.filter(d=>d.stage==='won').length)} hint="negócios"/></div><div className="kanban">{stages.map(s=><div className="column" key={s}><div className="columnHead"><b>{stageLabel[s]}</b><span>{deals.filter(d=>d.stage===s).length}</span></div>{deals.filter(d=>d.stage===s).map(d=><article className="deal" key={d.id}><b>{d.title}</b><span>{d.contact_name||'Sem contato vinculado'}</span><strong>{money(d.value_minor)}</strong><small>{d.next_action||'Sem próxima ação'}</small><select value={d.stage} onChange={e=>onMove(d.id,e.target.value)}>{stages.map(x=><option value={x} key={x}>{stageLabel[x]}</option>)}</select></article>)}</div>)}</div><Panel eyebrow="BASE" title="Contatos"><div className="table"><div className="tr head"><span>Nome</span><span>Contato</span><span>Origem</span><span>Tags</span></div>{contacts.slice(0,100).map(c=><div className="tr" key={c.id}><span><b>{c.name}</b><small>{c.company_name}</small></span><span><small>{c.email}</small><small>{c.phone}</small></span><span>{c.source||'—'}</span><span>{(c.tags||[]).join(', ')||'—'}</span></div>)}</div></Panel></>}
function Finance({ledger,dashboard,onNew,onPaid}:{ledger:Ledger[];dashboard:Dashboard;onNew:()=>void;onPaid:(id:string)=>void}){return <><div className="moduleIntro split"><div><p className="eyebrow">ERP LITE</p><h2>Financeiro operacional</h2><p>Receitas, despesas, recebíveis e caixa sem transformar a operação em um ERP pesado.</p></div><button className="primary" onClick={onNew}>+ Lançamento</button></div><div className="kpis"><Kpi label="Recebido" value={money(dashboard.finance?.income_paid_minor)} hint="realizado"/><Kpi label="Pago" value={money(dashboard.finance?.expense_paid_minor)} hint="despesas realizadas"/><Kpi label="A receber" value={money(dashboard.finance?.receivable_minor)} hint={`${dashboard.finance?.overdue_count||0} vencidos`}/><Kpi label="A pagar" value={money(dashboard.finance?.payable_minor)} hint="em aberto"/></div><Panel eyebrow="LANÇAMENTOS" title="Movimentações"><div className="table financeTable"><div className="tr head"><span>Descrição</span><span>Tipo</span><span>Vencimento</span><span>Status</span><span>Valor</span><span></span></div>{ledger.map(l=><div className="tr" key={l.id}><span><b>{l.description}</b><small>{l.category}{l.contact_name?` · ${l.contact_name}`:''}</small></span><span>{l.direction==='income'?'Receita':'Despesa'}</span><span>{date(l.due_at)}</span><span><Status value={l.status}/></span><span className={l.direction==='income'?'positive':'negative'}>{money(l.amount_minor)}</span><span>{l.status!=='paid'&&l.status!=='cancelled'&&<button onClick={()=>onPaid(l.id)}>Marcar pago</button>}</span></div>)}</div></Panel></>}
function Agenda({tasks,appointments,onTask,onAppointment,onTaskStatus,onAppointmentStatus}:{tasks:Task[];appointments:Appointment[];onTask:()=>void;onAppointment:()=>void;onTaskStatus:(id:string,s:string)=>void;onAppointmentStatus:(id:string,s:string)=>void}){return <><div className="moduleIntro split"><div><p className="eyebrow">ROTINA</p><h2>Agenda & Tarefas</h2><p>Compromissos e próximos passos compartilhados com CRM e Secretária Digital.</p></div><div className="buttons"><button onClick={onTask}>+ Tarefa</button><button className="primary" onClick={onAppointment}>+ Compromisso</button></div></div><div className="twoCol"><Panel eyebrow="AGENDA" title="Próximos compromissos">{appointments.length?appointments.slice(0,20).map(a=><article className="rowCard" key={a.id}><div><b>{a.title}</b><span>{date(a.starts_at)}{a.contact_name?` · ${a.contact_name}`:''}</span></div><select value={a.status} onChange={e=>onAppointmentStatus(a.id,e.target.value)}><option value="scheduled">Agendado</option><option value="confirmed">Confirmado</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option><option value="no_show">Não compareceu</option></select></article>):<Empty text="Nenhum compromisso no período."/>}</Panel><Panel eyebrow="TAREFAS" title="Próximas ações">{tasks.length?tasks.slice(0,30).map(t=><article className="rowCard" key={t.id}><div><b>{t.title}</b><span>{t.due_at?date(t.due_at):'Sem prazo'}{t.contact_name?` · ${t.contact_name}`:''}</span></div><select value={t.status} onChange={e=>onTaskStatus(t.id,e.target.value)}><option value="todo">A fazer</option><option value="doing">Em andamento</option><option value="done">Concluída</option><option value="cancelled">Cancelada</option></select></article>):<Empty text="Nenhuma tarefa aberta."/>}</Panel></div></>}
function Documents(){return <><div className="moduleIntro"><p className="eyebrow">DOCUMENT ENGINE</p><h2>Documentos no fluxo do negócio</h2><p>Referências e estados ficam no NexOffice; leitura, inteligência, assinatura e validação serão executadas pelo DocWallet.</p></div><div className="moduleGrid"><ModuleCard title="Arquivos" text="Documentos vinculados a clientes, tarefas e operações."/><ModuleCard title="Assinaturas" text="Envio, aceite e acompanhamento via DocWallet."/><ModuleCard title="Leitura & extração" text="OCR e dados estruturados entrando no ERP/CRM após revisão."/><ModuleCard title="Aprovações" text="Fluxos humanos antes de ações sensíveis."/></div></>}
function Team({policies,onEdit}:{policies:Policy[];onEdit:(p:Policy)=>void}){const agents=[['Sofia','Secretária','Agenda, confirmações, remarcações e rotina.'],['Alex','Atendimento','Conversas, triagem e respostas.'],['Clara','CRM','Pipeline, follow-ups e relacionamento.'],['Nico','ERP','Lançamentos e organização operacional.'],['Theo','Cobrança & Controller','Recebíveis, inadimplência, caixa e alertas.'],['Dora','Documentos','Leitura, assinatura e aprovações.'],['Maya','Growth','Conteúdo, campanhas e oportunidades.']];return <><div className="moduleIntro"><p className="eyebrow">EQUIPE DIGITAL</p><h2>Especialistas sobre a mesma memória empresarial</h2><p>Cada agente tem um papel; as políticas abaixo determinam quando pode agir, avisar ou pedir autorização.</p></div><div className="agentGrid">{agents.map(([name,role,text])=><article className="agentCard" key={name}><div className="avatar">{name[0]}</div><div><h3>{name}</h3><b>{role}</b><p>{text}</p><button>Conversar em breve</button></div></article>)}</div><Panel eyebrow="GOVERNANÇA" title="Políticas de autonomia"><div className="policyList">{policies.map(p=><div className="policy" key={p.id}><code>{p.action_type}</code><span>{p.mode==='automatic'?'Automático':p.mode==='notify'?'Avisar':'Pedir aprovação'}</span><button onClick={()=>onEdit(p)}>Alterar</button></div>)}</div></Panel></>}
function Integrations({current}:{current:Integration[]}){const known=[['DocWallet','Documentos, OCR, assinatura e aprovação'],['Staff','Voz, conversa, memória e agenda'],['SmartBots','WhatsApp, atendimento e follow-up'],['NextGen','Cobrança, Pix e conciliação'],['MODO','Growth, campanhas e conteúdo'],['TaxAgent','NFS-e e infraestrutura fiscal']];return <><div className="moduleIntro"><p className="eyebrow">AV INTEGRATION HUB</p><h2>Uma experiência, várias capabilities</h2><p>NexOffice continua sendo a interface. Os engines especializados trabalham por trás via adapters.</p></div><div className="moduleGrid">{known.map(([name,text])=>{const c=current.find(i=>i.provider.toLowerCase()===name.toLowerCase());return <article key={name}><div className="moduleIcon">◇</div><h3>{name}</h3><p>{text}</p><Status value={c?.status||'planned'}/></article>})}</div></>}
function Settings({members,workspace,onInvite,onNewWorkspace}:{members:Member[];workspace?:Workspace;onInvite:()=>void;onNewWorkspace:()=>void}){return <><div className="moduleIntro split"><div><p className="eyebrow">WORKSPACE</p><h2>{workspace?.name||'Sua empresa'}</h2><p>Usuários, papéis e acesso ao sistema operacional do negócio.</p></div><div className="buttons"><button onClick={onNewWorkspace}>+ Workspace</button><button className="primary" onClick={onInvite}>+ Convidar</button></div></div><Panel eyebrow="ACESSOS" title="Equipe"><div className="table"><div className="tr head"><span>Nome</span><span>E-mail</span><span>Perfil</span><span>Status</span></div>{members.map(m=><div className="tr" key={m.id}><span><b>{m.name}</b></span><span>{m.email}</span><span>{m.role}</span><span><Status value={m.active?'active':'disabled'}/></span></div>)}</div></Panel></>}

function ActionCard({action,onDecision}:{action:Action;onDecision:(d:'approved'|'rejected'|'dismissed')=>void}){return <article className={`action ${action.priority}`}><div className="agent">{roleNames[action.agent_role]||action.agent_role}</div><h4>{action.title}</h4><p>{action.summary}</p><small>{action.autonomy==='approval_required'?'Precisa da sua aprovação':action.autonomy==='notify'?'Organizado para sua ciência':'Pode executar automaticamente'}</small><div className="buttons">{action.autonomy==='approval_required'&&<><button className="primary" onClick={()=>onDecision('approved')}>Aprovar</button><button onClick={()=>onDecision('rejected')}>Recusar</button></>}<button onClick={()=>onDecision('dismissed')}>Dispensar</button></div></article>}
function Panel({eyebrow,title,badge,children}:{eyebrow:string;title:string;badge?:number;children:ReactNode}){return <div className="panel"><div className="sectionHead"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div>{badge!==undefined&&<span>{badge}</span>}</div>{children}</div>}
function Kpi({label,value,hint}:{label:string;value:string;hint:string}){return <div className="kpi"><span>{label}</span><b>{value}</b><small>{hint}</small></div>}
function Pulse({label,value,detail}:{label:string;value:string;detail:string}){return <div className="pulse"><div><b>{label}</b><span>{value}</span></div><small>{detail}</small></div>}
function Status({value}:{value:string}){const labels:Record<string,string>={paid:'Pago',open:'Em aberto',overdue:'Vencido',planned:'Planejado',active:'Ativo',connected:'Conectado',disconnected:'Desconectado',disabled:'Inativo'};return <span className={`status status-${value}`}>{labels[value]||value}</span>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function ModuleCard({title,text}:{title:string;text:string}){return <article><div className="moduleIcon">◇</div><h3>{title}</h3><p>{text}</p></article>}
function Modal({children,onClose}:{children:ReactNode;onClose:()=>void}){return <div className="modalBack" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><button className="modalClose" onClick={onClose}>×</button>{children}</div></div>}
function Form({title,submit,children}:{title:string;submit:(e:FormEvent<HTMLFormElement>)=>void|Promise<void>;children:ReactNode}){return <form className="form" onSubmit={submit}><p className="eyebrow">NEXOFFICE</p><h2>{title}</h2><div className="formGrid">{children}</div><button className="primary formSave">Salvar</button></form>}
function Field({name,label,type='text',required=false,placeholder='',select,options,defaultValue}:{name:string;label:string;type?:string;required?:boolean;placeholder?:string;select?:string[];options?:string[][];defaultValue?:string}){return <label className="field"><span>{label}</span>{select?<select name={name} defaultValue={defaultValue}>{select.map(s=>{const [v,l]=s.split(':');return <option key={v} value={v}>{l||v}</option>})}</select>:options?<select name={name}><option value="">Nenhum</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input name={name} type={type} required={required} placeholder={placeholder} defaultValue={defaultValue}/>}</label>}
function data(e:FormEvent<HTMLFormElement>):Record<string,string>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>}
function title(view:string){return ({command:'Central de Comando',crm:'CRM',finance:'Financeiro',agenda:'Agenda & Tarefas',documents:'Documentos',team:'Equipe Digital',marketing:'Marketing',compliance:'Compliance & Proteção',integrations:'Integrações',settings:'Empresa & Acessos'} as Record<string,string>)[view]||'NexOffice'}