import {useEffect,useState} from 'react';
import {api,patch,post,session} from './api';

type Priority={source:string;severity:string;title:string;reason:string;action:string;dimension:string;signalId?:string|null};
type Driver={type:string;key:string;label:string;delta:number;direction:'better'|'worse'|'neutral';text:string};
type SectorMetric={key:string;label:string;value:string;quality:'automatic'|'informed'};
type SectorInsight={level:'good'|'attention'|'info';title:string;message:string};
type Radar={generatedAt:string;status:string;score:number|null;scoreDelta:number|null;trend:string;drivers:Driver[];priorities:Priority[];knowledge:{percent:number;missing:string[]};recurring:{monthlyIncomeMinor:number;monthlyExpenseMinor:number;incomeSharePct:number|null;activeIncomeRules:number;expiring60Days:number};sector:{kind:string;metrics:SectorMetric[];insights:SectorInsight[]};snapshotAt?:string|null};
type TrackedAction={id:string;signal_id?:string|null;task_id?:string|null;title:string;status:string;task_status?:string|null;metric_key?:string|null;baseline_value?:number|string|null;observed_value?:number|string|null;completed_at?:string|null;evaluation_due_at?:string|null;evaluated_at?:string|null;evaluation_status?:string|null;effect_summary?:string|null;effect_pct?:number|string|null;due_at?:string|null;rule_code?:string|null;rule_version?:number|null};

const sectorNames:Record<string,string>={general:'seu negócio',services:'serviços',professional_services:'serviços profissionais',health:'saúde',beauty:'beleza e bem-estar',commerce:'comércio',restaurant:'alimentação',education:'educação',automotive:'automotivo',real_estate:'imobiliário',creator:'criação de conteúdo'};
const metricNames:Record<string,string>={overdue_receivable_share_pct:'Recebíveis vencidos',cash_coverage_months:'Cobertura de caixa',pipeline_coverage_months:'Cobertura do pipeline',top_client_share_pct:'Concentração no maior cliente',task_overdue_rate_pct:'Tarefas atrasadas',appointment_problem_rate_pct:'Perdas na agenda'};
const shortDate=(v?:string|null)=>{if(!v)return'';try{return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit'}).format(new Date(v))}catch{return''}};
const metricValue=(key:string|undefined|null,v:number|string|null|undefined)=>{if(v===null||v===undefined||v==='')return'—';const num=Number(v);if(!Number.isFinite(num))return String(v);if(String(key||'').endsWith('_pct'))return`${num.toFixed(1)}%`;if(String(key||'').endsWith('_months'))return`${num.toFixed(1)} meses`;return Number.isInteger(num)?String(num):num.toFixed(1)};
const actionLabel=(a:TrackedAction)=>{if(a.task_status==='cancelled'||a.status==='cancelled')return{label:'Cancelada',kind:'cancelled'};if(a.evaluation_status==='improved')return{label:'Resultado: melhorou',kind:'improved'};if(a.evaluation_status==='stable')return{label:'Resultado: estável',kind:'stable'};if(a.evaluation_status==='worsened')return{label:'Resultado: piorou',kind:'worsened'};if(a.evaluation_status==='insufficient_data')return{label:'Ainda sem dado comparável',kind:'waiting'};if(a.task_status==='done'||a.status==='done')return{label:a.evaluation_due_at?`Concluída · revisão ${shortDate(a.evaluation_due_at)}`:'Concluída · aguardando leitura',kind:'waiting'};return{label:a.due_at?`Em andamento · prazo ${shortDate(a.due_at)}`:'Em andamento',kind:'active'}};

export default function BusinessRadarCenter(){
  const [open,setOpen]=useState(false);const [radar,setRadar]=useState<Radar|null>(null);const [actions,setActions]=useState<TrackedAction[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [actionBusy,setActionBusy]=useState<string|number|null>(null);const [actionMessage,setActionMessage]=useState('');
  const [sessionKey,setSessionKey]=useState(()=>`${session.token()}|${session.workspace()}`);const authenticated=Boolean(session.token()&&session.workspace());
  useEffect(()=>{const timer=setInterval(()=>{const key=`${session.token()}|${session.workspace()}`;setSessionKey(prev=>prev===key?prev:key)},700);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!authenticated){setOpen(false);setRadar(null);setActions([]);return}void load()},[sessionKey]);
  async function loadActions(){try{setActions(await api<TrackedAction[]>('/v1/intelligence/actions'))}catch{setActions([])}}
  async function load(){setBusy(true);setError('');try{const [nextRadar]=await Promise.all([api<Radar>('/v1/intelligence/radar'),loadActions()]);setRadar(nextRadar)}catch(e:any){setError(e?.message||'Não foi possível montar seu radar.')}finally{setBusy(false)}}
  async function createAction(index:number){setActionBusy(index);setActionMessage('');setError('');try{const r=await post<any>('/v1/intelligence/actions/task',{priorityIndex:index});setActionMessage(r?.existing?'Esta prioridade já estava sendo acompanhada.':`Tarefa criada: ${r?.task?.title||'prioridade do Radar'}. O NexOffice vai acompanhar o resultado.`);await loadActions()}catch(e:any){setError(e?.message||'Não foi possível criar a tarefa.')}finally{setActionBusy(null)}}
  async function completeAction(action:TrackedAction){if(!action.task_id)return;setActionBusy(action.id);setActionMessage('');setError('');try{await patch(`/v1/tasks/${action.task_id}`,{status:'done'});await loadActions();setActionMessage('Tarefa concluída. O NexOffice aguardará uma nova leitura comparável antes de avaliar o efeito.')}catch(e:any){setError(e?.message||'Não foi possível concluir a tarefa.')}finally{setActionBusy(null)}}
  if(!authenticated)return null;
  const attention=(radar?.priorities||[]).filter(x=>x.severity==='critical'||x.severity==='attention').length;
  return <>
    <button className={`businessRadarLauncher ${attention?'hasAttention':''}`} onClick={()=>setOpen(true)}><span>◈</span><b>Radar de Hoje</b>{radar?.score!==null&&radar?.score!==undefined?<strong>{radar.score}</strong>:null}</button>
    {open&&<div className="businessRadarBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="businessRadarPanel">
      <header className="businessRadarHeader"><div><small>NEXOFFICE · RADAR DO NEGÓCIO</small><h2>O que merece sua atenção hoje</h2><p>Prioridades, mudanças e sinais do seu negócio em linguagem simples.</p></div><div className="businessRadarActions"><button onClick={()=>void load()} disabled={busy}>{busy?'Atualizando…':'Atualizar'}</button><button className="close" onClick={()=>setOpen(false)}>×</button></div></header>
      {error&&<div className="businessRadarError">{error}</div>}{actionMessage&&<div className="businessRadarSuccess">{actionMessage}</div>}
      <div className="businessRadarBody">{radar?<>
        <section className="businessRadarScore"><div><small>SAÚDE DO NEGÓCIO</small><b>{radar.score??'—'}<i>/100</i></b><span>{radar.scoreDelta===null?'Primeira comparação':`${radar.scoreDelta>0?'+':''}${radar.scoreDelta} ponto(s) desde a leitura anterior`}</span></div><div><small>CONHECIMENTO DO NEGÓCIO</small><b>{radar.knowledge?.percent??0}<i>%</i></b><span>{radar.knowledge?.percent>=70?'Boa base para interpretar sua empresa':'Quanto mais você usa o NexOffice, melhor fica a leitura'}</span></div></section>

        <section className="businessRadarSection"><div className="businessRadarTitle"><div><small>PRIORIDADES</small><h3>As coisas mais importantes agora</h3></div><span>{radar.priorities.length}</span></div><div className="businessRadarPriorities">{radar.priorities.length?radar.priorities.map((p,i)=>{const tracked=Boolean(p.signalId&&actions.some(a=>a.signal_id===p.signalId&&!['done','cancelled'].includes(String(a.task_status||a.status))));return <article key={`${p.title}-${i}`} className={p.severity}><div className="priorityNumber">{i+1}</div><div><b>{p.title}</b><p>{p.reason}</p><div className="priorityAction"><small>Próximo passo</small><span>{p.action}</span><button className="priorityTaskButton" disabled={actionBusy!==null||tracked} onClick={()=>void createAction(i)}>{tracked?'Já acompanhando':actionBusy===i?'Criando…':'Criar tarefa e acompanhar'}</button></div></div></article>}):<div className="businessRadarEmpty">Nenhuma prioridade importante agora. Continue registrando sua operação.</div>}</div></section>

        <section className="businessRadarSection"><div className="businessRadarTitle"><div><small>AÇÕES ACOMPANHADAS</small><h3>Você está trabalhando nestes pontos</h3></div><span>{actions.length}</span></div>{actions.length?<div className="trackedActions">{actions.slice(0,8).map(a=>{const state=actionLabel(a);const done=a.task_status==='done'||a.status==='done';const evaluated=Boolean(a.evaluated_at&&['improved','stable','worsened'].includes(String(a.evaluation_status)));return <article key={a.id} className={state.kind}><div className="trackedActionTop"><div><b>{a.title.replace(/^Ação NexOffice · /,'')}</b><span className={`trackedStatus ${state.kind}`}>{state.label}</span></div>{!done&&a.task_status!=='cancelled'&&a.task_id?<button disabled={actionBusy!==null} onClick={()=>void completeAction(a)}>{actionBusy===a.id?'Concluindo…':'Marcar como concluída'}</button>:null}</div>{a.metric_key?<div className="trackedMetric"><small>{metricNames[a.metric_key]||a.metric_key}</small><b>{metricValue(a.metric_key,a.baseline_value)}{a.observed_value!==null&&a.observed_value!==undefined?` → ${metricValue(a.metric_key,a.observed_value)}`:''}</b>{evaluated&&a.effect_pct!==null&&a.effect_pct!==undefined?<span>{Number(a.effect_pct)>0?'+':''}{Number(a.effect_pct).toFixed(1)}% após a ação</span>:null}</div>:null}{a.effect_summary?<p>{a.effect_summary}</p>:done?<p>O NexOffice aguardará uma nova leitura do indicador antes de avaliar o efeito.</p>:<p>Conclua a tarefa quando executar o próximo passo recomendado.</p>}</article>})}</div>:<div className="businessRadarEmpty">Quando você transformar uma prioridade em tarefa, ela aparecerá aqui com acompanhamento do resultado.</div>}<div className="trackedFootnote">A comparação mostra o que aconteceu depois da ação; ela não presume causalidade.</div></section>

        <section className="businessRadarSection"><div className="businessRadarTitle"><div><small>O QUE MUDOU</small><h3>Por que seu índice se movimentou</h3></div></div>{radar.drivers.length?<div className="businessRadarDrivers">{radar.drivers.map(d=><article key={`${d.type}-${d.key}`} className={d.direction}><span>{d.direction==='better'?'↑':d.direction==='worse'?'↓':'→'}</span><div><b>{d.label}</b><p>{d.text}</p></div></article>)}</div>:<div className="businessRadarEmpty">Ainda não há histórico suficiente para explicar mudanças. A comparação fica melhor a cada nova leitura.</div>}</section>

        <section className="businessRadarSection"><div className="businessRadarTitle"><div><small>SEU MODELO DE NEGÓCIO</small><h3>Indicadores úteis para {sectorNames[radar.sector.kind]||'sua empresa'}</h3></div></div><div className="businessRadarMetrics">{radar.sector.metrics.map(m=><article key={m.key}><small>{m.label}</small><b>{m.value}</b><span>{m.quality==='automatic'?'Calculado pelo NexOffice':'Informado pela empresa'}</span></article>)}</div><div className="businessRadarSectorInsights">{radar.sector.insights.map((x,i)=><article key={`${x.title}-${i}`} className={x.level}><b>{x.title}</b><p>{x.message}</p></article>)}</div></section>

        {radar.knowledge?.missing?.length>0&&<section className="businessRadarSection"><div className="businessRadarTitle"><div><small>MAIS PRECISÃO</small><h3>O que pode melhorar nossa leitura</h3></div></div><div className="businessRadarMissing">{radar.knowledge.missing.slice(0,5).map(x=><span key={x}>+ {x}</span>)}</div></section>}
        <footer>O Radar ajuda na gestão e não representa aprovação, negativa ou oferta de crédito.</footer>
      </>:<div className="businessRadarEmpty">Preparando o radar da empresa…</div>}</div>
    </section></div>}
  </>;
}
