import {useEffect,useState,type FormEvent} from 'react';
import {api,post,put,session} from './api';

type Coverage={key:string;label:string;earned:number;max:number;covered:boolean;source:string;why:string;action:string};
type Knowledge={
  percent:number;liveEstimate:number;level:{key:string;label:string;message:string};profileCompletenessPct:number;profile:any;
  onboarding:{shouldPrompt:boolean;estimatedMinutes:number;steps:number};coverage:Coverage[];
  nextSteps:Array<{key:string;title:string;gainPotential:number;why:string;source:string}>;
  suggestions:Array<{field:string;value:any;reason:string}>;milestones:Array<{target:number;reached:boolean;label:string}>;
  observed:{ledgerEntries:number;contacts:number;deals:number;tasks:number;appointments90:number;futureAppointments:number;manualMetrics:number;events30:number;interactions30:number;documents:number;recurringIncomeRules:number;lastEventAt?:string|null};
  snapshotAt?:string|null;note:string;
};

const sectorOptions=[['general','Geral'],['services','Serviços'],['professional_services','Serviços profissionais'],['health','Saúde'],['beauty','Beleza e bem-estar'],['commerce','Comércio'],['restaurant','Restaurante / alimentação'],['education','Educação'],['automotive','Oficina / automotivo'],['real_estate','Imobiliário'],['creator','Criador de conteúdo']];
const revenueOptions=[['mixed','Mista'],['transactional','Por venda'],['recurring','Recorrente'],['project','Por projeto'],['commission','Comissão'],['appointment','Por atendimento']];
const percent=(v:number,max:number)=>Math.max(0,Math.min(100,max?Math.round(v/max*100):0));

export default function BusinessKnowledgeCenter(){
  const [sessionKey,setSessionKey]=useState(()=>`${session.token()}|${session.workspace()}`);const authenticated=Boolean(session.token()&&session.workspace());
  const [knowledge,setKnowledge]=useState<Knowledge|null>(null);const [open,setOpen]=useState(false);const [profileOpen,setProfileOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  useEffect(()=>{const timer=setInterval(()=>{const next=`${session.token()}|${session.workspace()}`;setSessionKey(prev=>prev===next?prev:next)},700);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!authenticated){setKnowledge(null);setOpen(false);return}void load()},[sessionKey]);
  async function load(){setError('');try{setKnowledge(await api<Knowledge>('/v1/intelligence/knowledge'))}catch(e:any){setError(e?.message||'Não foi possível medir o conhecimento do negócio.')}}
  async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{
    await put('/v1/intelligence/profile',{sector:String(f.get('sector')||'general'),subsector:String(f.get('subsector')||'')||null,revenueModel:String(f.get('revenueModel')||'mixed'),sellsProducts:f.get('sellsProducts')==='on',sellsServices:f.get('sellsServices')==='on',recurringRevenue:f.get('recurringRevenue')==='on',usesAgenda:f.get('usesAgenda')==='on',usesInventory:f.get('usesInventory')==='on',usesContracts:f.get('usesContracts')==='on',employeeCount:f.get('employeeCount')?Number(f.get('employeeCount')):null,activeCustomersEstimate:f.get('activeCustomersEstimate')?Number(f.get('activeCustomersEstimate')):null,primarySalesChannel:String(f.get('primarySalesChannel')||'')||null,seasonality:String(f.get('seasonality')||'')||null,mainDependency:String(f.get('mainDependency')||'')||null});
    await post('/v1/intelligence/health/refresh',{});await load();setProfileOpen(false);setNotice('Perfil atualizado. A leitura do negócio foi recalculada com o novo contexto.');
  }catch(e:any){setError(e?.message||'Não foi possível salvar o perfil.')}finally{setBusy(false)}}
  if(!authenticated)return null;
  const p=knowledge?.profile||{};const shown=knowledge?.percent??null;const pendingEstimate=knowledge&&knowledge.liveEstimate>knowledge.percent?knowledge.liveEstimate:null;
  return <>
    <button className={`businessKnowledgeLauncher ${knowledge?.onboarding?.shouldPrompt?'needsProfile':''}`} onClick={()=>setOpen(true)}><span>◌</span><div><small>NEXOFFICE CONHECE</small><b>{shown===null?'…':`${shown}%`}</b></div></button>
    {open&&<div className="businessKnowledgeBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="businessKnowledgePanel">
      <header className="businessKnowledgeHeader"><div><small>NEXOFFICE · CONHECIMENTO DO NEGÓCIO</small><h2>Quanto entendemos da sua empresa</h2><p>Você opera normalmente. O NexOffice transforma essa rotina em contexto para decisões melhores.</p></div><div><button onClick={()=>void load()}>Atualizar</button><button className="close" onClick={()=>setOpen(false)}>×</button></div></header>
      {error&&<div className="businessKnowledgeError">{error}</div>}{notice&&<div className="businessKnowledgeNotice">{notice}</div>}
      <div className="businessKnowledgeBody">{knowledge?<>
        <section className="knowledgeHero"><div className="knowledgeHeroScore"><b>{knowledge.percent}%</b><span>{knowledge.level.label}</span></div><div><h3>{knowledge.level.message}</h3><p>{knowledge.note}</p>{pendingEstimate!==null&&<div className="knowledgePending">Pela atividade já registrada, a próxima leitura pode chegar perto de <b>{pendingEstimate}%</b>.</div>}</div></section>
        {knowledge.onboarding.shouldPrompt&&<section className="knowledgeOnboarding"><div><small>COMECE PELO CONTEXTO</small><h3>Em cerca de {knowledge.onboarding.estimatedMinutes} minutos, a leitura fica muito melhor.</h3><p>Setor, forma de receita, porte e dependências mudam totalmente a interpretação dos mesmos números.</p></div><button onClick={()=>setProfileOpen(true)}>Completar perfil inteligente</button></section>}
        <section className="knowledgeSection"><div className="knowledgeTitle"><div><small>COBERTURA</small><h3>De onde vêm os dados que usamos</h3></div><span>{knowledge.coverage.filter(x=>x.covered).length}/{knowledge.coverage.length}</span></div><div className="knowledgeCoverage">{knowledge.coverage.map(item=><article key={item.key} className={item.covered?'covered':''}><div className="knowledgeCoverageTop"><div><b>{item.label}</b><small>{item.source}</small></div><strong>{Math.round(item.earned)}/{item.max}</strong></div><div className="knowledgeBar"><span style={{width:`${percent(item.earned,item.max)}%`}}/></div><p>{item.why}</p>{!item.covered&&<em>{item.action}</em>}</article>)}</div></section>
        <section className="knowledgeSection"><div className="knowledgeTitle"><div><small>PRÓXIMOS PASSOS</small><h3>O que mais aumenta a precisão agora</h3></div></div>{knowledge.nextSteps.length?<div className="knowledgeNext">{knowledge.nextSteps.map((x,i)=><article key={x.key}><span>{i+1}</span><div><b>{x.title}</b><p>{x.why}</p><small>Potencial de até +{Math.round(x.gainPotential)} pontos de contexto · {x.source}</small></div>{x.key==='profile'?<button onClick={()=>setProfileOpen(true)}>Fazer agora</button>:null}</article>)}</div>:<div className="knowledgeComplete">Sua base já cobre os blocos principais. Agora o ganho vem de histórico, frequência de uso e indicadores específicos do setor.</div>}</section>
        {knowledge.suggestions.length>0&&<section className="knowledgeSection"><div className="knowledgeTitle"><div><small>DETECTADO AUTOMATICAMENTE</small><h3>Coisas que a própria operação já nos contou</h3></div></div><div className="knowledgeDetected">{knowledge.suggestions.map((s,i)=><article key={`${s.field}-${i}`}><b>{humanSuggestion(s)}</b><p>{s.reason}</p></article>)}</div><button className="knowledgeProfileReview" onClick={()=>setProfileOpen(true)}>Revisar no perfil</button></section>}
        <section className="knowledgeSection"><div className="knowledgeTitle"><div><small>MARCOS</small><h3>A profundidade cresce com o uso</h3></div></div><div className="knowledgeMilestones">{knowledge.milestones.map(m=><div key={m.target} className={m.reached?'reached':''}><span>{m.reached?'✓':m.target}</span><b>{m.label}</b><small>{m.target}%</small></div>)}</div></section>
        <section className="knowledgeObserved"><div><small>EVENTOS OBSERVADOS · 30 DIAS</small><b>{knowledge.observed.events30}</b></div><div><small>CLIENTES</small><b>{knowledge.observed.contacts}</b></div><div><small>OPORTUNIDADES</small><b>{knowledge.observed.deals}</b></div><div><small>MOVIMENTOS FINANCEIROS</small><b>{knowledge.observed.ledgerEntries}</b></div><div><small>INTERAÇÕES · 30 DIAS</small><b>{knowledge.observed.interactions30}</b></div></section>
      </>:<div className="knowledgeLoading">Montando o mapa de conhecimento do negócio…</div>}</div>
      {profileOpen&&<div className="knowledgeProfileBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setProfileOpen(false)}}><form className="knowledgeProfile" onSubmit={saveProfile}><header><div><small>ONBOARDING INTELIGENTE · ~2 MIN</small><h3>Conte somente o que muda nossa análise</h3><p>Não repetimos dados operacionais que o NexOffice consegue aprender pelo uso.</p></div><button type="button" onClick={()=>setProfileOpen(false)}>×</button></header>
        <section><div className="knowledgeStep"><span>1</span><div><b>Seu modelo de negócio</b><small>O que você vende e como a receita acontece.</small></div></div><div className="knowledgeProfileGrid"><label>Setor<select name="sector" defaultValue={p.sector||'general'}>{sectorOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Subsetor<input name="subsector" defaultValue={p.subsector||''} placeholder="Ex.: odontologia, autopeças, consultoria"/></label><label>Como a receita acontece<select name="revenueModel" defaultValue={p.revenue_model||'mixed'}>{revenueOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></section>
        <section><div className="knowledgeStep"><span>2</span><div><b>Como a operação funciona</b><small>Marque apenas o que realmente faz parte do dia a dia.</small></div></div><div className="knowledgeChecks"><label><input name="sellsProducts" type="checkbox" defaultChecked={Boolean(p.sells_products)}/>Vende produtos</label><label><input name="sellsServices" type="checkbox" defaultChecked={Boolean(p.sells_services)}/>Presta serviços</label><label><input name="recurringRevenue" type="checkbox" defaultChecked={Boolean(p.recurring_revenue)}/>Receita recorrente</label><label><input name="usesAgenda" type="checkbox" defaultChecked={Boolean(p.uses_agenda)}/>Depende de agenda</label><label><input name="usesInventory" type="checkbox" defaultChecked={Boolean(p.uses_inventory)}/>Usa estoque</label><label><input name="usesContracts" type="checkbox" defaultChecked={Boolean(p.uses_contracts)}/>Depende de contratos</label></div></section>
        <section><div className="knowledgeStep"><span>3</span><div><b>Porte e contexto</b><small>Isso ajuda a comparar e interpretar sem confundir negócios muito diferentes.</small></div></div><div className="knowledgeProfileGrid"><label>Funcionários<input name="employeeCount" type="number" min="0" defaultValue={p.employee_count??''}/></label><label>Clientes ativos aproximados<input name="activeCustomersEstimate" type="number" min="0" defaultValue={p.active_customers_estimate??''}/></label><label>Principal canal de vendas<input name="primarySalesChannel" defaultValue={p.primary_sales_channel||''} placeholder="WhatsApp, indicação, loja, Instagram…"/></label><label className="wide">Sazonalidade<input name="seasonality" defaultValue={p.seasonality||''} placeholder="Ex.: dezembro forte, janeiro fraco"/></label><label className="wide">Maior dependência do negócio<input name="mainDependency" defaultValue={p.main_dependency||''} placeholder="Ex.: cliente principal, profissional-chave, fornecedor"/></label></div></section>
        <button className="knowledgeSave" disabled={busy}>{busy?'Salvando e recalculando…':'Salvar e melhorar a leitura'}</button>
      </form></div>}
    </section></div>}
  </>;
}

function humanSuggestion(s:{field:string;value:any}){
  if(s.field==='usesAgenda')return'Parece que sua empresa depende de agenda';
  if(s.field==='recurringRevenue')return'Parece que há receita recorrente';
  if(s.field==='primarySalesChannel')return`Seu canal mais frequente parece ser ${String(s.value)}`;
  if(s.field==='sellsServices')return'Parece que sua empresa presta serviços';
  return'Encontramos um padrão novo na operação';
}
