import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {api,post,put,session} from './api';
import FiscalHomologationConsole from './FiscalHomologationConsole';
import './business-operation-center.css';

type Contact={id:string;name:string;phone?:string|null;document_number?:string|null};
type Deal={id:string;contact_id?:string|null;title:string;value_minor:number|string;stage:string};
type PaymentProfile={configured:boolean;encryptionConfigured:boolean;method:string;pixKeyType?:string;maskedPixKey?:string;beneficiaryName?:string;documentLabel?:string;instructions?:string};
type Operation={id:string;contact_id:string;deal_id?:string|null;document_ref_id?:string|null;invoice_action_id?:string|null;communication_action_id?:string|null;ledger_entry_id?:string|null;title:string;description:string;amount_minor:number|string;currency:string;due_at?:string|null;status:string;contact_name?:string;contact_phone?:string|null;deal_title?:string|null;document_title?:string|null;document_provider?:string|null;invoice_action_status?:string|null;communication_action_status?:string|null;ledger_status?:string|null;fiscal_external_ref?:string|null;fiscal_status?:string|null};
type Draft={message:string;recipient?:string|null;contactName?:string|null;secretPersisted:boolean;externalEffect:boolean};
type ReadinessCheck={key:string;label:string;ready:boolean;required:boolean;detail:string};
type FiscalReadiness={operationId:string;environment:'test'|'production';ready:boolean;alreadyPrepared:boolean;humanApprovalRequired:true;checks:ReadinessCheck[];blockers:Array<{key:string;label:string;detail:string}>;warnings:string[];suggestedDefaults:{customerCityCode?:string|null};integration:{connected:boolean;status?:string|null;companyMapped:boolean;credentialConfigured:boolean;baseUrlConfigured:boolean};safety:{externalEffect:false;remoteTaxAgentCall:false;productionExecutionEnabled:boolean;municipalRegistrationAssumedRequired:false};externalEffect:false};
type ReadinessPanel={operation:Operation;data:FiscalReadiness};

const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const date=(value?:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(value)):'—';
const toIso=(value:string)=>value?new Date(value).toISOString():null;
const stageLabel:Record<string,string>={draft:'Rascunho',contract_ready:'Contrato vinculado',invoice_pending:'Nota em aprovação',invoice_queued:'Nota na fila',invoice_authorized:'Nota autorizada',collection_ready:'Cobrança pronta',communication_pending:'Lembrete em aprovação',paid:'Pago',closed:'Concluído',cancelled:'Cancelado',attention:'Atenção'};
const fiscalLabel:Record<string,string>={created:'Criada',queued:'Na fila',processing:'Processando',retrying:'Reprocessando',authorized:'Autorizada',rejected:'Rejeitada',cancelled:'Cancelada'};

export default function BusinessOperationCenter(){
  const [active,setActive]=useState(false),[open,setOpen]=useState(false),[operations,setOperations]=useState<Operation[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[deals,setDeals]=useState<Deal[]>([]),[profile,setProfile]=useState<PaymentProfile|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showNew,setShowNew]=useState(false),[showPix,setShowPix]=useState(false),[showHomologation,setShowHomologation]=useState(false),[draft,setDraft]=useState<Draft|null>(null),[readiness,setReadiness]=useState<ReadinessPanel|null>(null);
  const authenticated=Boolean(session.token()&&session.workspace());
  useEffect(()=>{const timer=setInterval(()=>{const selected=document.querySelector<HTMLButtonElement>('.sidebar nav button.active');const text=selected?.textContent||'';setActive(text.includes('CRM')||text.includes('Financeiro'))},400);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(authenticated&&active)void load()},[authenticated,active,session.workspace()]);
  async function load(){setError('');try{const [ops,c,d,p]=await Promise.all([api<Operation[]>('/v1/business-operations'),api<Contact[]>('/v1/crm/contacts'),api<Deal[]>('/v1/crm/deals'),api<PaymentProfile>('/v1/collections/payment-profile')]);setOperations(ops);setContacts(c);setDeals(d);setProfile(p)}catch(e:any){setError(e?.message||'Não foi possível carregar as operações comerciais.')}}
  const openValue=useMemo(()=>operations.filter(o=>!['paid','closed','cancelled'].includes(o.status)).reduce((s,o)=>s+Number(o.amount_minor||0),0),[operations]);
  async function run(key:string,fn:()=>Promise<any>,success:string){setBusy(key);setError('');setNotice('');try{await fn();setNotice(success);await load()}catch(e:any){setError(e?.message||'Não foi possível concluir a ação.')}finally{setBusy('')}}
  async function createOperation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const contactId=String(f.get('contactId')||''),dealId=String(f.get('dealId')||'')||null,title=String(f.get('title')||''),description=String(f.get('description')||''),amountMinor=Math.round(Number(f.get('amount')||0)*100),dueAt=toIso(String(f.get('dueAt')||''));await run('new',()=>post('/v1/business-operations',{contactId,dealId,title,description,amountMinor,dueAt}),'Operação comercial criada.');setShowNew(false)}
  async function savePix(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run('pix',()=>put('/v1/collections/payment-profile',{pixKeyType:String(f.get('pixKeyType')),pixKey:String(f.get('pixKey')),beneficiaryName:String(f.get('beneficiaryName')),documentLabel:String(f.get('documentLabel')||'')||null,instructions:String(f.get('instructions')||'')||null}),'Dados Pix protegidos e salvos.');setShowPix(false)}
  async function checkFiscalReadiness(op:Operation){setBusy(`readiness:${op.id}`);setError('');setNotice('');setDraft(null);try{const data=await api<FiscalReadiness>(`/v1/business-operations/${op.id}/fiscal-readiness?environment=test`);setReadiness({operation:op,data})}catch(e:any){setError(e?.message||'Não foi possível verificar a prontidão fiscal.')}finally{setBusy('')}}
  async function prepareInvoice(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!readiness)return;const f=new FormData(e.currentTarget);const cityCode=String(f.get('customerCityCode')||'').replace(/\D/g,''),serviceCode=String(f.get('nationalServiceCode')||'').trim()||null,nbs=String(f.get('nbs')||'').replace(/\D/g,'')||null;if(cityCode.length!==7){setError('Informe um código IBGE de 7 dígitos para preparar a nota.');return}const hardBlockers=readiness.data.blockers.filter(item=>item.key!=='customer_city_code');if(hardBlockers.length){setError('Resolva os bloqueadores fiscais indicados antes de preparar a nota.');return}await run(`invoice:${readiness.operation.id}`,()=>post(`/v1/business-operations/${readiness.operation.id}/prepare-invoice`,{environment:'test',customerCityCode:cityCode,nationalServiceCode:serviceCode,nbs:nbs&&nbs.length===9?nbs:null}),'Emissão fiscal de teste preparada para aprovação humana. Nenhuma nota foi emitida por esta tela.');setReadiness(null)}
  async function syncInvoice(op:Operation){await run(`sync:${op.id}`,()=>post(`/v1/business-operations/${op.id}/sync-invoice`,{}),'Status fiscal atualizado a partir do TaxAgent.');}
  async function prepareCollection(op:Operation){await run(`collection:${op.id}`,()=>post(`/v1/business-operations/${op.id}/prepare-collection`,{}),'Recebível criado com o Pix do próprio negócio.');}
  async function viewDraft(op:Operation){setBusy(`draft:${op.id}`);setError('');try{const d=await post<Draft>(`/v1/business-operations/${op.id}/communication-draft`,{});setDraft(d);setReadiness(null)}catch(e:any){setError(e?.message||'Não foi possível montar a cobrança.')}finally{setBusy('')}}
  async function prepareCommunication(op:Operation){await run(`comm:${op.id}`,()=>post(`/v1/business-operations/${op.id}/prepare-communication`,{}),'Lembrete preparado para aprovação humana. Nenhum dado Pix sensível foi enviado ao SmartBots.');}
  async function markPaid(op:Operation){await run(`paid:${op.id}`,()=>post(`/v1/business-operations/${op.id}/mark-paid`,{}),'Pagamento marcado como recebido.');}
  async function copyDraft(){if(!draft?.message)return;await navigator.clipboard.writeText(draft.message);setNotice('Mensagem com os dados Pix copiada.');}
  if(!authenticated||!active)return null;
  return <aside className={`boc ${open?'open':'closed'}`} aria-label="Operações Comerciais"><button className="bocToggle" onClick={()=>setOpen(v=>!v)}>{open?'×':'↗'}</button>{open&&<div className="bocBody">
    <header><div><small>NEXOFFICE · REVENUE OPERATIONS</small><h3>Operação Comercial</h3><p>CRM → contrato → nota → cobrança → comunicação → recebido</p></div><button onClick={()=>void load()}>↻</button></header>
    <div className="bocKpis"><span><small>Operações</small><b>{operations.length}</b></span><span><small>Em aberto</small><b>{money(openValue)}</b></span><span><small>Pix próprio</small><b>{profile?.configured?'✓':'—'}</b></span></div>
    {error&&<div className="bocError">{error}</div>}{notice&&<div className="bocNotice">{notice}</div>}
    <div className="bocActions"><button className="primary" onClick={()=>setShowNew(v=>!v)}>+ Nova operação</button><button onClick={()=>setShowPix(v=>!v)}>{profile?.configured?'Atualizar Pix':'Cadastrar Pix'}</button><button onClick={()=>setShowHomologation(v=>!v)}>{showHomologation?'Fechar homologação':'Homologação fiscal'}</button></div>
    {showHomologation&&<FiscalHomologationConsole onClose={()=>setShowHomologation(false)}/>}    
    {profile?.configured&&<div className="bocSafe"><b>Recebimento proprietário</b><span>{profile.beneficiaryName} · {profile.maskedPixKey}</span><small>O NexOffice organiza a cobrança. O dinheiro vai direto para o Pix cadastrado pelo seu negócio; NexOffice e Nexa não custodiam nem movimentam o valor.</small></div>}
    {showPix&&<form className="bocForm" onSubmit={savePix}><b>Dados de recebimento Pix</b><select name="pixKeyType" defaultValue={profile?.pixKeyType||'cnpj'}><option value="cnpj">CNPJ</option><option value="cpf">CPF</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Chave aleatória</option></select><input name="pixKey" placeholder="Chave Pix" required/><input name="beneficiaryName" placeholder="Nome do favorecido" defaultValue={profile?.beneficiaryName||''} required/><input name="documentLabel" placeholder="Identificação opcional" defaultValue={profile?.documentLabel||''}/><textarea name="instructions" placeholder="Instruções opcionais" defaultValue={profile?.instructions||''}/><button className="primary" disabled={busy==='pix'}>{busy==='pix'?'Salvando…':'Salvar protegido'}</button></form>}
    {showNew&&<form className="bocForm" onSubmit={createOperation}><b>Nova operação comercial</b><select name="contactId" required><option value="">Cliente</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="dealId"><option value="">Sem oportunidade vinculada</option>{deals.filter(d=>d.stage!=='lost').map(d=><option key={d.id} value={d.id}>{d.title} · {money(d.value_minor)}</option>)}</select><input name="title" placeholder="Ex.: Projeto site institucional" required/><textarea name="description" placeholder="Serviço / objeto da operação" required/><input name="amount" type="number" min="0" step="0.01" placeholder="Valor (R$)" required/><input name="dueAt" type="datetime-local"/><button className="primary" disabled={busy==='new'}>{busy==='new'?'Criando…':'Criar operação'}</button></form>}
    <section className="bocList">{operations.length?operations.map(op=><article key={op.id}><div className="bocTitle"><div><b>{op.title}</b><small>{op.contact_name||'Cliente'} · {stageLabel[op.status]||op.status}</small></div><strong>{money(op.amount_minor)}</strong></div><div className="bocChain"><span className={op.document_ref_id?'done':''}>Contrato<b>{op.document_ref_id?'✓':'○'}</b></span><span className={op.fiscal_status==='authorized'?'done':op.invoice_action_id?'active':''}>Nota<b>{op.fiscal_status==='authorized'?'✓':op.invoice_action_id?'…':'○'}</b></span><span className={op.ledger_entry_id?'done':''}>Cobrança<b>{op.ledger_entry_id?'✓':'○'}</b></span><span className={op.communication_action_id?'done':''}>Comunicar<b>{op.communication_action_id?'✓':'○'}</b></span><span className={op.status==='paid'?'done':''}>Recebido<b>{op.status==='paid'?'✓':'○'}</b></span></div><p>{op.description}</p><small>Vencimento: {date(op.due_at)}{op.document_title?` · Contrato: ${op.document_title}`:''}{op.fiscal_status?` · Fiscal: ${fiscalLabel[op.fiscal_status]||op.fiscal_status}`:''}{op.fiscal_external_ref?` · TaxAgent ${op.fiscal_external_ref.slice(0,8)}…`:''}</small><div className="bocRow">{!op.invoice_action_id&&<button onClick={()=>void checkFiscalReadiness(op)} disabled={busy===`readiness:${op.id}`}>{busy===`readiness:${op.id}`?'Verificando…':'Checar nota'}</button>}{op.invoice_action_id&&op.fiscal_status!=='authorized'&&<button onClick={()=>void syncInvoice(op)} disabled={busy.startsWith('sync:')}>Atualizar nota</button>}{!op.ledger_entry_id&&<button onClick={()=>void prepareCollection(op)} disabled={busy.startsWith('collection:')}>Gerar cobrança Pix</button>}{op.ledger_entry_id&&op.status!=='paid'&&<button onClick={()=>void viewDraft(op)} disabled={busy.startsWith('draft:')}>Ver mensagem Pix</button>}{op.ledger_entry_id&&!op.communication_action_id&&op.status!=='paid'&&<button onClick={()=>void prepareCommunication(op)} disabled={busy.startsWith('comm:')}>Lembrete via SmartBots</button>}{op.ledger_entry_id&&op.status!=='paid'&&<button onClick={()=>void markPaid(op)} disabled={busy.startsWith('paid:')}>Marcar recebido</button>}</div></article>):<div className="bocEmpty">Crie a primeira operação para ligar CRM, documentos, fiscal e cobrança.</div>}</section>
    {readiness&&<div className="bocReadiness"><div className="bocReadinessHead"><div><small>PRONTIDÃO FISCAL · TESTE</small><b>{readiness.operation.title}</b></div><button onClick={()=>setReadiness(null)}>×</button></div><div className={`bocReadinessState ${readiness.data.blockers.filter(item=>item.key!=='customer_city_code').length?'blocked':'ready'}`}><b>{readiness.data.blockers.filter(item=>item.key!=='customer_city_code').length?'Existem bloqueadores antes da preparação':'Base pronta para preparar em ambiente de teste'}</b><span>Esta checagem é local, não chama o TaxAgent e não emite nota.</span></div><div className="bocChecks">{readiness.data.checks.map(check=><div key={check.key} className={check.ready?'ok':'missing'}><b>{check.ready?'✓':'!'} {check.label}</b><span>{check.detail}</span></div>)}</div>{readiness.data.warnings.map((warning,index)=><div className="bocWarning" key={index}>{warning}</div>)}<form className="bocForm" onSubmit={prepareInvoice}><b>Preparar emissão para aprovação</b><small>Ambiente fixado em <strong>teste</strong>. Preparar cria uma ação governada; não significa emissão automática.</small><label>Município do cliente · código IBGE<input name="customerCityCode" inputMode="numeric" pattern="\d{7}" maxLength={7} defaultValue={readiness.data.suggestedDefaults.customerCityCode||''} placeholder="7 dígitos" required/></label><label>Código nacional do serviço · opcional<input name="nationalServiceCode" placeholder="Conforme classificação fiscal aplicável"/></label><label>NBS · opcional<input name="nbs" inputMode="numeric" pattern="\d{9}" maxLength={9} placeholder="9 dígitos"/></label><button className="primary" disabled={busy.startsWith('invoice:')||readiness.data.blockers.some(item=>item.key!=='customer_city_code')}>{busy.startsWith('invoice:')?'Preparando…':'Preparar em teste para aprovação'}</button></form><small className="bocReadinessFoot">Inscrição Municipal não é presumida como requisito universal pelo NexOffice. Exigências municipais específicas permanecem sob autoridade do TaxAgent/município. Produção não é habilitada por esta tela.</small></div>}
    {draft&&<div className="bocDraft"><div><b>Mensagem Pix do seu negócio</b><button onClick={()=>setDraft(null)}>×</button></div><textarea readOnly rows={10} value={draft.message}/><button className="primary" onClick={()=>void copyDraft()}>Copiar mensagem</button><small>Esta visualização exige sessão autenticada. A chave Pix é decriptada apenas para montar esta resposta e não é persistida na Operação Comercial, aprovação ou integração SmartBots.</small></div>}
  </div>}</aside>;
}
