import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {api,post,put,session} from './api';
import './business-operation-center.css';

type Contact={id:string;name:string;phone?:string|null;document_number?:string|null};
type Deal={id:string;contact_id?:string|null;title:string;value_minor:number|string;stage:string};
type PaymentProfile={configured:boolean;encryptionConfigured:boolean;method:string;pixKeyType?:string;maskedPixKey?:string;beneficiaryName?:string;documentLabel?:string;instructions?:string};
type Operation={id:string;contact_id:string;deal_id?:string|null;document_ref_id?:string|null;invoice_action_id?:string|null;communication_action_id?:string|null;ledger_entry_id?:string|null;title:string;description:string;amount_minor:number|string;currency:string;due_at?:string|null;status:string;contact_name?:string;contact_phone?:string|null;deal_title?:string|null;document_title?:string|null;document_provider?:string|null;invoice_action_status?:string|null;communication_action_status?:string|null;ledger_status?:string|null;fiscal_external_ref?:string|null};
type Draft={message:string;recipient?:string|null;contactName?:string|null;secretPersisted:boolean;externalEffect:boolean};

const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const date=(value?:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(value)):'—';
const toIso=(value:string)=>value?new Date(value).toISOString():null;
const stageLabel:Record<string,string>={draft:'Rascunho',contract_ready:'Contrato vinculado',invoice_pending:'Nota em aprovação',invoice_queued:'Nota na fila',invoice_authorized:'Nota autorizada',collection_ready:'Cobrança pronta',communication_pending:'Lembrete em aprovação',paid:'Pago',closed:'Concluído',cancelled:'Cancelado',attention:'Atenção'};

export default function BusinessOperationCenter(){
  const [active,setActive]=useState(false),[open,setOpen]=useState(false),[operations,setOperations]=useState<Operation[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[deals,setDeals]=useState<Deal[]>([]),[profile,setProfile]=useState<PaymentProfile|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showNew,setShowNew]=useState(false),[showPix,setShowPix]=useState(false),[draft,setDraft]=useState<Draft|null>(null);
  const authenticated=Boolean(session.token()&&session.workspace());
  useEffect(()=>{const timer=setInterval(()=>{const selected=document.querySelector<HTMLButtonElement>('.sidebar nav button.active');const text=selected?.textContent||'';setActive(text.includes('CRM')||text.includes('Financeiro'))},400);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(authenticated&&active)void load()},[authenticated,active,session.workspace()]);
  async function load(){setError('');try{const [ops,c,d,p]=await Promise.all([api<Operation[]>('/v1/business-operations'),api<Contact[]>('/v1/crm/contacts'),api<Deal[]>('/v1/crm/deals'),api<PaymentProfile>('/v1/collections/payment-profile')]);setOperations(ops);setContacts(c);setDeals(d);setProfile(p)}catch(e:any){setError(e?.message||'Não foi possível carregar as operações comerciais.')}}
  const openValue=useMemo(()=>operations.filter(o=>!['paid','closed','cancelled'].includes(o.status)).reduce((s,o)=>s+Number(o.amount_minor||0),0),[operations]);
  async function run(key:string,fn:()=>Promise<any>,success:string){setBusy(key);setError('');setNotice('');try{await fn();setNotice(success);await load()}catch(e:any){setError(e?.message||'Não foi possível concluir a ação.')}finally{setBusy('')}}
  async function createOperation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const contactId=String(f.get('contactId')||''),dealId=String(f.get('dealId')||'')||null,title=String(f.get('title')||''),description=String(f.get('description')||''),amountMinor=Math.round(Number(f.get('amount')||0)*100),dueAt=toIso(String(f.get('dueAt')||''));await run('new',()=>post('/v1/business-operations',{contactId,dealId,title,description,amountMinor,dueAt}),'Operação comercial criada.');setShowNew(false)}
  async function savePix(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run('pix',()=>put('/v1/collections/payment-profile',{pixKeyType:String(f.get('pixKeyType')),pixKey:String(f.get('pixKey')),beneficiaryName:String(f.get('beneficiaryName')),documentLabel:String(f.get('documentLabel')||'')||null,instructions:String(f.get('instructions')||'')||null}),'Dados Pix protegidos e salvos.');setShowPix(false)}
  async function prepareInvoice(op:Operation){const cityCode=window.prompt('Código IBGE do município do cliente (7 dígitos):','');if(!cityCode)return;const serviceCode=window.prompt('Código nacional do serviço (opcional):','')||null;await run(`invoice:${op.id}`,()=>post(`/v1/business-operations/${op.id}/prepare-invoice`,{environment:'test',customerCityCode:cityCode,nationalServiceCode:serviceCode}),'Emissão fiscal preparada para aprovação humana.');}
  async function prepareCollection(op:Operation){await run(`collection:${op.id}`,()=>post(`/v1/business-operations/${op.id}/prepare-collection`,{}),'Recebível criado com o Pix do próprio negócio.');}
  async function viewDraft(op:Operation){setBusy(`draft:${op.id}`);setError('');try{const d=await post<Draft>(`/v1/business-operations/${op.id}/communication-draft`,{});setDraft(d)}catch(e:any){setError(e?.message||'Não foi possível montar a cobrança.')}finally{setBusy('')}}
  async function prepareCommunication(op:Operation){await run(`comm:${op.id}`,()=>post(`/v1/business-operations/${op.id}/prepare-communication`,{}),'Lembrete preparado para aprovação humana. Nenhum dado Pix sensível foi enviado ao SmartBots.');}
  async function markPaid(op:Operation){await run(`paid:${op.id}`,()=>post(`/v1/business-operations/${op.id}/mark-paid`,{}),'Pagamento marcado como recebido.');}
  async function copyDraft(){if(!draft?.message)return;await navigator.clipboard.writeText(draft.message);setNotice('Mensagem com os dados Pix copiada.');}
  if(!authenticated||!active)return null;
  return <aside className={`boc ${open?'open':'closed'}`} aria-label="Operações Comerciais"><button className="bocToggle" onClick={()=>setOpen(v=>!v)}>{open?'×':'↗'}</button>{open&&<div className="bocBody">
    <header><div><small>NEXOFFICE · REVENUE OPERATIONS</small><h3>Operação Comercial</h3><p>CRM → contrato → nota → cobrança → comunicação → recebido</p></div><button onClick={()=>void load()}>↻</button></header>
    <div className="bocKpis"><span><small>Operações</small><b>{operations.length}</b></span><span><small>Em aberto</small><b>{money(openValue)}</b></span><span><small>Pix próprio</small><b>{profile?.configured?'✓':'—'}</b></span></div>
    {error&&<div className="bocError">{error}</div>}{notice&&<div className="bocNotice">{notice}</div>}
    <div className="bocActions"><button className="primary" onClick={()=>setShowNew(v=>!v)}>+ Nova operação</button><button onClick={()=>setShowPix(v=>!v)}>{profile?.configured?'Atualizar Pix':'Cadastrar Pix'}</button></div>
    {profile?.configured&&<div className="bocSafe"><b>Recebimento proprietário</b><span>{profile.beneficiaryName} · {profile.maskedPixKey}</span><small>O NexOffice organiza a cobrança. O dinheiro vai direto para o Pix cadastrado pelo seu negócio; NexOffice e Nexa não custodiam nem movimentam o valor.</small></div>}
    {showPix&&<form className="bocForm" onSubmit={savePix}><b>Dados de recebimento Pix</b><select name="pixKeyType" defaultValue={profile?.pixKeyType||'cnpj'}><option value="cnpj">CNPJ</option><option value="cpf">CPF</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Chave aleatória</option></select><input name="pixKey" placeholder="Chave Pix" required/><input name="beneficiaryName" placeholder="Nome do favorecido" defaultValue={profile?.beneficiaryName||''} required/><input name="documentLabel" placeholder="Identificação opcional" defaultValue={profile?.documentLabel||''}/><textarea name="instructions" placeholder="Instruções opcionais" defaultValue={profile?.instructions||''}/><button className="primary" disabled={busy==='pix'}>{busy==='pix'?'Salvando…':'Salvar protegido'}</button></form>}
    {showNew&&<form className="bocForm" onSubmit={createOperation}><b>Nova operação comercial</b><select name="contactId" required><option value="">Cliente</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="dealId"><option value="">Sem oportunidade vinculada</option>{deals.filter(d=>d.stage!=='lost').map(d=><option key={d.id} value={d.id}>{d.title} · {money(d.value_minor)}</option>)}</select><input name="title" placeholder="Ex.: Projeto site institucional" required/><textarea name="description" placeholder="Serviço / objeto da operação" required/><input name="amount" type="number" min="0" step="0.01" placeholder="Valor (R$)" required/><input name="dueAt" type="datetime-local"/><button className="primary" disabled={busy==='new'}>{busy==='new'?'Criando…':'Criar operação'}</button></form>}
    <section className="bocList">{operations.length?operations.map(op=><article key={op.id}><div className="bocTitle"><div><b>{op.title}</b><small>{op.contact_name||'Cliente'} · {stageLabel[op.status]||op.status}</small></div><strong>{money(op.amount_minor)}</strong></div><div className="bocChain"><span className={op.document_ref_id?'done':''}>Contrato<b>{op.document_ref_id?'✓':'○'}</b></span><span className={op.invoice_action_id?'done':''}>Nota<b>{op.invoice_action_id?'✓':'○'}</b></span><span className={op.ledger_entry_id?'done':''}>Cobrança<b>{op.ledger_entry_id?'✓':'○'}</b></span><span className={op.communication_action_id?'done':''}>Comunicar<b>{op.communication_action_id?'✓':'○'}</b></span><span className={op.status==='paid'?'done':''}>Recebido<b>{op.status==='paid'?'✓':'○'}</b></span></div><p>{op.description}</p><small>Vencimento: {date(op.due_at)}{op.document_title?` · Contrato: ${op.document_title}`:''}</small><div className="bocRow">{!op.invoice_action_id&&<button onClick={()=>void prepareInvoice(op)} disabled={busy.startsWith('invoice:')}>Preparar nota</button>}{!op.ledger_entry_id&&<button onClick={()=>void prepareCollection(op)} disabled={busy.startsWith('collection:')}>Gerar cobrança Pix</button>}{op.ledger_entry_id&&op.status!=='paid'&&<button onClick={()=>void viewDraft(op)} disabled={busy.startsWith('draft:')}>Ver mensagem Pix</button>}{op.ledger_entry_id&&!op.communication_action_id&&op.status!=='paid'&&<button onClick={()=>void prepareCommunication(op)} disabled={busy.startsWith('comm:')}>Lembrete via SmartBots</button>}{op.ledger_entry_id&&op.status!=='paid'&&<button onClick={()=>void markPaid(op)} disabled={busy.startsWith('paid:')}>Marcar recebido</button>}</div></article>):<div className="bocEmpty">Crie a primeira operação para ligar CRM, documentos, fiscal e cobrança.</div>}</section>
    {draft&&<div className="bocDraft"><div><b>Mensagem Pix do seu negócio</b><button onClick={()=>setDraft(null)}>×</button></div><textarea readOnly rows={10} value={draft.message}/><button className="primary" onClick={()=>void copyDraft()}>Copiar mensagem</button><small>Esta visualização exige sessão autenticada. A chave Pix é decriptada apenas para montar esta resposta e não é persistida na Operação Comercial, aprovação ou integração SmartBots.</small></div>}
  </div>}</aside>;
}
