import {useEffect,useMemo,useState} from 'react';
import {api,post} from './api';
import './business-evidence.css';

type Overview={operational_evidence_completeness:number;components:Array<{id:string;label:string;status:string;count:number|null}>;metrics:{operations:number;paidOrClosed:number;revenueWithoutInvoice:number;operationsWithoutDocument:number;documents:number;documentsWithoutOperation:number;pendingSignatures:number;fiscalAttention:number};regulatory:{status:string;total:number;actionsRequired:number|null};methodology:string};
type InboxItem={type:string;severity:'high'|'medium'|'info';title:string;message:string;operationId?:string|null;documentId?:string;effectiveAt?:string|null;sourceUrl?:string|null;sourceVerifiedByHash?:boolean;requiresAction?:boolean;action?:{label:string;target:string}};
type Closing={period:string;operational_evidence_completeness:number;components:Array<{id:string;label:string;status:string;count:number|null}>;local_metrics:Overview['metrics'];taxagent:{status:string;operational_evidence_completeness:number|null};rule_changes:{status:string;total:number;actions_required:number|null};methodology:string};
type RuleChange={id:string;title:string;summary:string;source_url:string;effective_at?:string|null;published_at?:string|null;requires_action:boolean;source_verified_by_hash:boolean};

const statusLabel=(value:string)=>value==='complete'?'OK':value==='attention'?'Atenção':'Não observado';
const monthNow=()=>new Date().toISOString().slice(0,7);

export default function BusinessEvidenceCenter(){
  const [open,setOpen]=useState(false);const [tab,setTab]=useState<'overview'|'inbox'|'closing'|'rules'>('overview');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const [overview,setOverview]=useState<Overview|null>(null);const [inbox,setInbox]=useState<{items:InboxItem[];counts:{high:number;medium:number;info:number}}|null>(null);const [period,setPeriod]=useState(monthNow());const [closing,setClosing]=useState<Closing|null>(null);const [rules,setRules]=useState<RuleChange[]>([]);const [dossier,setDossier]=useState<any>(null);const [notice,setNotice]=useState('');
  useEffect(()=>{if(open)void refresh()},[open]);
  async function refresh(){setLoading(true);setError('');try{const [o,i,c,r]=await Promise.all([api<Overview>('/v1/business-evidence/overview'),api<any>('/v1/business-evidence/inbox'),api<Closing>(`/v1/fiscal/closing?period=${encodeURIComponent(period)}`),api<any>('/v1/fiscal/rule-changes')]);setOverview(o);setInbox(i);setClosing(c);setRules(Array.isArray(r?.changes)?r.changes:[])}catch(e:any){setError(e?.message||'Não foi possível carregar Evidência & Fiscal.')}finally{setLoading(false)}}
  async function changePeriod(value:string){setPeriod(value);if(!value)return;setLoading(true);try{setClosing(await api<Closing>(`/v1/fiscal/closing?period=${encodeURIComponent(value)}`))}catch(e:any){setError(e?.message||'Não foi possível calcular o fechamento.')}finally{setLoading(false)}}
  async function snapshot(){if(!period)return;setLoading(true);setError('');try{await post('/v1/fiscal/closing/snapshot',{period});setNotice('Fotografia do fechamento registrada com métricas seguras.')}catch(e:any){setError(e?.message||'Não foi possível registrar a fotografia.')}finally{setLoading(false)}}
  async function openDossier(operationId?:string|null){if(!operationId)return;setLoading(true);setError('');try{setDossier(await api(`/v1/business-evidence/operations/${encodeURIComponent(operationId)}/dossier`))}catch(e:any){setError(e?.message||'Não foi possível abrir o dossiê.')}finally{setLoading(false)}}
  const urgent=useMemo(()=>inbox?.items?.filter(x=>x.severity==='high').length||0,[inbox]);
  return <>
    <button className="evidenceLauncher" onClick={()=>setOpen(true)}><span>🧾</span><b>Evidência & Fiscal</b>{urgent>0&&<em>{urgent}</em>}</button>
    {open&&<div className="evidenceBackdrop" role="dialog" aria-modal="true"><section className="evidenceCenter">
      <header><div><small>NEXOFFICE · EVIDÊNCIA & FISCAL</small><h2>Documento + Fiscal + Financeiro</h2><p>Uma linha de evidência para saber o que aconteceu, o que falta e o que merece atenção.</p></div><button className="close" onClick={()=>setOpen(false)}>×</button></header>
      <nav>{([['overview','Visão geral'],['inbox','Caixa de entrada'],['closing','Fechamento'],['rules','Mudanças fiscais']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      {error&&<div className="evidenceError">{error}</div>}{notice&&<div className="evidenceNotice">{notice}</div>}{loading&&<div className="evidenceLoading">Atualizando…</div>}
      {tab==='overview'&&<div className="evidenceBody">{overview?<><div className="evidenceScore"><strong>{overview.operational_evidence_completeness}%</strong><div><b>Completude operacional</b><small>Não é certificação contábil ou jurídica.</small></div></div><div className="evidenceKpis"><article><span>Receita sem nota</span><b>{overview.metrics.revenueWithoutInvoice}</b></article><article><span>Operação sem documento</span><b>{overview.metrics.operationsWithoutDocument}</b></article><article><span>Assinaturas pendentes</span><b>{overview.metrics.pendingSignatures}</b></article><article><span>Ações fiscais</span><b>{overview.regulatory.actionsRequired??'—'}</b></article></div><div className="evidenceComponents">{overview.components.map(c=><article key={c.id}><div><b>{c.label}</b><small>{c.count===null?'Fonte ainda não observada':`${c.count} ocorrência(s)`}</small></div><span className={c.status}>{statusLabel(c.status)}</span></article>)}</div></>:<Empty/>}</div>}
      {tab==='inbox'&&<div className="evidenceBody"><div className="inboxHeader"><div><b>O que entrou na sua empresa e pede atenção?</b><small>{inbox?`${inbox.counts.high} urgente(s) · ${inbox.counts.medium} acompanhamento(s)`:'—'}</small></div><button onClick={refresh}>Atualizar</button></div><div className="evidenceInbox">{inbox?.items?.length?inbox.items.map((item,index)=><article key={`${item.type}-${item.operationId||item.documentId||index}`} className={item.severity}><div><small>{item.type.replaceAll('_',' ').toUpperCase()}</small><b>{item.title}</b><p>{item.message}</p>{item.effectiveAt&&<em>Vigência: {String(item.effectiveAt).slice(0,10)}</em>}{item.sourceVerifiedByHash&&<em> · fonte preservada por hash</em>}</div><div className="inboxActions">{item.operationId&&<button onClick={()=>openDossier(item.operationId)}>Ver dossiê</button>}{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer">Fonte oficial</a>}</div></article>):<Empty text="Nenhuma pendência operacional encontrada."/>}</div></div>}
      {tab==='closing'&&<div className="evidenceBody"><div className="closingControls"><label>Mês<input type="month" value={period} onChange={e=>void changePeriod(e.target.value)}/></label><button onClick={snapshot} disabled={!closing}>Registrar fotografia</button></div>{closing?<><div className="evidenceScore"><strong>{closing.operational_evidence_completeness}%</strong><div><b>Fechamento operacional</b><small>{period} · documento, fiscal, assinatura e atenção operacional.</small></div></div><div className="evidenceComponents">{closing.components.map(c=><article key={c.id}><div><b>{c.label}</b><small>{c.count===null?'Não observado':`${c.count} ocorrência(s)`}</small></div><span className={c.status}>{statusLabel(c.status)}</span></article>)}</div><p className="methodology">{closing.methodology}</p></>:<Empty/>}</div>}
      {tab==='rules'&&<div className="evidenceBody"><div className="rulesIntro"><b>Mudanças fiscais aplicáveis à empresa</b><small>O NexOffice mostra impacto operacional. A fonte e a interpretação fiscal permanecem rastreáveis.</small></div><div className="evidenceInbox">{rules.length?rules.map(rule=><article key={rule.id} className={rule.requires_action?'high':'info'}><div><small>{rule.requires_action?'AÇÃO REQUERIDA':'INFORMATIVO'}</small><b>{rule.title}</b><p>{rule.summary}</p><em>{rule.effective_at?`Vigência: ${String(rule.effective_at).slice(0,10)}`:'Vigência não informada'}{rule.source_verified_by_hash?' · fonte preservada por hash':''}</em></div><a href={rule.source_url} target="_blank" rel="noreferrer">Fonte oficial</a></article>):<Empty text="Nenhuma mudança fiscal aplicável registrada."/>}</div></div>}
      {dossier&&<div className="dossierPanel"><div className="between"><div><small>DOSSIÊ DA OPERAÇÃO</small><h3>{dossier.operation?.title}</h3></div><button onClick={()=>setDossier(null)}>Fechar</button></div><div className="evidenceScore compact"><strong>{dossier.operational_evidence_completeness}%</strong><div><b>Linhas de evidência observadas</b><small>{dossier.methodology}</small></div></div><div className="evidenceComponents">{dossier.components?.map((c:any)=><article key={c.id}><b>{c.label}</b><span className={c.status}>{statusLabel(c.status)}</span></article>)}</div></div>}
      <footer>Conteúdo bruto de documentos e payload fiscal não são copiados para esta visão. Ações externas continuam dependentes dos fluxos de confirmação/aprovação existentes.</footer>
    </section></div>}
  </>
}
function Empty({text='Ainda não há dados suficientes para esta visão.'}:{text?:string}){return <div className="evidenceEmpty">{text}</div>}
