import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {api,post,put,session} from './api';

type Health={snapshot:any;profile:any;scores:{overall:number;finance:number;sales:number;customers:number;operation:number;resilience:number};knowledge:{percent:number;missing:string[]};metrics:any;signals:any[];sectorInsights:any[]};
type HistoryRow={id:string;as_of:string;overall_score:number;finance_score:number;sales_score:number;customer_score:number;operation_score:number;resilience_score:number;knowledge_pct:number;status:string;trend:string;summary:string};
const labels={finance:'Financeiro',sales:'Vendas',customers:'Clientes',operation:'Operação',resilience:'Resistência'} as const;
const sectorOptions=[['general','Geral'],['services','Serviços'],['professional_services','Serviços profissionais'],['health','Saúde'],['beauty','Beleza e bem-estar'],['commerce','Comércio'],['restaurant','Restaurante / alimentação'],['education','Educação'],['automotive','Oficina / automotivo'],['real_estate','Imobiliário'],['creator','Criador de conteúdo']];
const revenueOptions=[['mixed','Mista'],['transactional','Por venda'],['recurring','Recorrente'],['project','Por projeto'],['commission','Comissão'],['appointment','Por atendimento']];
const statusLabel=(value:string)=>value==='healthy'?'Saudável':value==='attention'?'Atenção':value==='critical'?'Precisa agir':'Aprendendo';
const trendLabel=(value:string)=>value==='improving'?'Melhorando':value==='worsening'?'Piorando':'Estável';
const date=(value?:string)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(value)):'—';

export default function BusinessHealthCenter(){
  const [sessionKey,setSessionKey]=useState(()=>`${session.token()}|${session.workspace()}`);const authenticated=Boolean(session.token()&&session.workspace());
  const [open,setOpen]=useState(false);const [health,setHealth]=useState<Health|null>(null);const [history,setHistory]=useState<HistoryRow[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [profileOpen,setProfileOpen]=useState(false);
  useEffect(()=>{const timer=setInterval(()=>{const next=`${session.token()}|${session.workspace()}`;setSessionKey(prev=>prev===next?prev:next)},700);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!authenticated){setOpen(false);return}if(open)load()},[sessionKey,open]);
  async function load(refresh=false){setBusy(true);setError('');try{const [h,his]=await Promise.all([refresh?post<Health>('/v1/intelligence/health/refresh',{}):api<Health>('/v1/intelligence/health'),api<HistoryRow[]>('/v1/intelligence/history?limit=30')]);setHealth(h);setHistory(his)}catch(e:any){setError(e?.message||'Não foi possível analisar seu negócio.')}finally{setBusy(false)}}
  async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await put('/v1/intelligence/profile',{sector:String(f.get('sector')||'general'),subsector:String(f.get('subsector')||'')||null,revenueModel:String(f.get('revenueModel')||'mixed'),sellsProducts:f.get('sellsProducts')==='on',sellsServices:f.get('sellsServices')==='on',recurringRevenue:f.get('recurringRevenue')==='on',usesAgenda:f.get('usesAgenda')==='on',usesInventory:f.get('usesInventory')==='on',usesContracts:f.get('usesContracts')==='on',employeeCount:f.get('employeeCount')?Number(f.get('employeeCount')):null,activeCustomersEstimate:f.get('activeCustomersEstimate')?Number(f.get('activeCustomersEstimate')):null,primarySalesChannel:String(f.get('primarySalesChannel')||'')||null,seasonality:String(f.get('seasonality')||'')||null,mainDependency:String(f.get('mainDependency')||'')||null});setProfileOpen(false);await load(true)}catch(e:any){setError(e?.message||'Não foi possível salvar o perfil.')}finally{setBusy(false)}}
  const sortedSignals=useMemo(()=>[...(health?.signals||[])].sort((a,b)=>({critical:0,attention:1,info:2}[a.severity as 'critical'|'attention'|'info']??3)-({critical:0,attention:1,info:2}[b.severity as 'critical'|'attention'|'info']??3)),[health]);
  if(!authenticated)return null;
  const s=health?.scores,p=health?.profile,knowledge=Number(health?.knowledge?.percent||0);
  return <>
    <button className="businessHealthLauncher" onClick={()=>setOpen(true)}>◎ <span>Saúde do Negócio</span>{s&&<b>{s.overall}</b>}</button>
    {open&&<div className="businessHealthBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="businessHealthPanel">
      <header className="businessHealthHeader"><div><small>NEXOFFICE · SAÚDE DO NEGÓCIO</small><h2>Como está sua empresa</h2><p>Uma leitura simples do que está melhorando, do que merece atenção e do que fazer agora.</p></div><div className="businessHealthHeaderActions"><button onClick={()=>setProfileOpen(true)}>Perfil do negócio</button><button onClick={()=>load(true)}>Atualizar leitura</button><button className="close" onClick={()=>setOpen(false)}>×</button></div></header>
      {busy&&<div className="businessHealthBusy"/>}{error&&<div className="businessHealthError">{error}</div>}
      <div className="businessHealthBody">{health?<>
        <section className={`businessHealthHero ${health.snapshot.status}`}><div className="businessScoreRing"><strong>{s?.overall??'—'}</strong><span>de 100</span></div><div><small>{statusLabel(health.snapshot.status)} · {trendLabel(health.snapshot.trend)}</small><h3>{health.snapshot.summary}</h3><p>O índice não é uma nota de crédito. Ele resume sinais da sua operação para ajudar você a decidir melhor.</p></div></section>
        <section className="businessScoreGrid">{Object.entries(labels).map(([key,label])=><article key={key}><div><small>{label}</small><b>{(s as any)?.[key]??'—'}</b></div><span className={`scoreBand score-${band(Number((s as any)?.[key]||0))}`}>{scoreText(Number((s as any)?.[key]||0))}</span></article>)}</section>
        <section className="businessKnowledge"><div><div><small>QUANTO O NEXOFFICE CONHECE DO SEU NEGÓCIO</small><b>{knowledge}%</b></div><p>Quanto mais você usa clientes, vendas, financeiro, agenda e rotinas, melhor fica a leitura.</p></div><div className="knowledgeTrack"><span style={{width:`${knowledge}%`}}/></div>{health.knowledge.missing?.length>0&&<div className="knowledgeMissing">{health.knowledge.missing.map((x:string)=><span key={x}>+ {x}</span>)}</div>}</section>
        <div className="businessHealthColumns"><section><div className="businessSectionTitle"><div><small>PRIORIDADES</small><h3>O que merece sua atenção</h3></div><span>{sortedSignals.filter(x=>x.severity!=='info').length}</span></div><div className="businessSignals">{sortedSignals.length?sortedSignals.map(sig=><article key={sig.id||sig.code} className={sig.severity}><i/><div><b>{sig.title}</b><p>{sig.message}</p>{sig.why_it_matters&&<small>{sig.why_it_matters}</small>}{sig.recommendation&&<div className="businessRecommendation"><strong>Próximo passo</strong><span>{sig.recommendation}</span></div>}</div></article>):<div className="businessEmpty">Nenhum alerta importante agora.</div>}</div></section>
          <section><div className="businessSectionTitle"><div><small>SEU SETOR</small><h3>Leitura que faz sentido para o seu negócio</h3></div></div><div className="sectorInsights">{(health.sectorInsights||[]).map((x:any,i:number)=><article key={`${x.title}-${i}`} className={x.level}><b>{x.title}</b><p>{x.message}</p></article>)}</div><div className="profileSummary"><small>PERFIL ATUAL</small><b>{sectorName(p?.sector)}{p?.subsector?` · ${p.subsector}`:''}</b><span>{revenueName(p?.revenue_model)} · perfil {p?.completeness_pct||0}% completo</span><button onClick={()=>setProfileOpen(true)}>Completar perfil</button></div></section></div>
        <section className="businessHistory"><div className="businessSectionTitle"><div><small>EVOLUÇÃO</small><h3>Seu negócio ao longo do tempo</h3></div></div>{history.length?<div className="historyRows">{history.slice(0,12).reverse().map(row=><div key={row.id}><span>{date(row.as_of)}</span><b>{row.overall_score??'—'}</b><i className={`dot ${row.status}`}/></div>)}</div>:<div className="businessEmpty">O histórico começará a ser construído automaticamente conforme você usa o NexOffice.</div>}</section>
        <footer>O NexOffice usa apenas os dados empresariais necessários para ajudar na gestão. Sinais são explicáveis e não representam aprovação ou negativa de crédito.</footer>
      </>:<div className="businessEmpty">Preparando a primeira leitura da sua empresa…</div>}</div>
      {profileOpen&&<div className="businessProfileBack" onMouseDown={e=>{if(e.target===e.currentTarget)setProfileOpen(false)}}><form className="businessProfileForm" onSubmit={saveProfile}><div className="businessProfileHead"><div><small>PERFIL INTELIGENTE</small><h3>Ajude o NexOffice a entender seu negócio</h3><p>Pedimos apenas informações que mudam a forma de analisar sua operação.</p></div><button type="button" onClick={()=>setProfileOpen(false)}>×</button></div><div className="businessProfileGrid"><label>Setor<select name="sector" defaultValue={p?.sector||'general'}>{sectorOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Subsetor<input name="subsector" defaultValue={p?.subsector||''} placeholder="Ex.: odontologia, barbearia, autopeças"/></label><label>Como a receita acontece<select name="revenueModel" defaultValue={p?.revenue_model||'mixed'}>{revenueOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Funcionários<input name="employeeCount" type="number" min="0" defaultValue={p?.employee_count??''}/></label><label>Clientes ativos aproximados<input name="activeCustomersEstimate" type="number" min="0" defaultValue={p?.active_customers_estimate??''}/></label><label>Principal canal de vendas<input name="primarySalesChannel" defaultValue={p?.primary_sales_channel||''} placeholder="Indicação, WhatsApp, loja, Instagram…"/></label><label className="wide">Sazonalidade<input name="seasonality" defaultValue={p?.seasonality||''} placeholder="Ex.: dezembro forte; janeiro fraco"/></label><label className="wide">Maior dependência do negócio<input name="mainDependency" defaultValue={p?.main_dependency||''} placeholder="Ex.: cliente principal, profissional-chave, fornecedor"/></label></div><div className="businessChecks"><label><input name="sellsProducts" type="checkbox" defaultChecked={Boolean(p?.sells_products)}/>Vende produtos</label><label><input name="sellsServices" type="checkbox" defaultChecked={Boolean(p?.sells_services)}/>Presta serviços</label><label><input name="recurringRevenue" type="checkbox" defaultChecked={Boolean(p?.recurring_revenue)}/>Tem receita recorrente</label><label><input name="usesAgenda" type="checkbox" defaultChecked={Boolean(p?.uses_agenda)}/>Depende de agenda</label><label><input name="usesInventory" type="checkbox" defaultChecked={Boolean(p?.uses_inventory)}/>Usa estoque</label><label><input name="usesContracts" type="checkbox" defaultChecked={Boolean(p?.uses_contracts)}/>Depende de contratos</label></div><button className="primary profileSave" disabled={busy}>Salvar e atualizar análise</button></form></div>}
    </section></div>}
  </>;
}
function band(score:number){return score>=80?'good':score>=60?'attention':'critical'}
function scoreText(score:number){return score>=80?'Bom':score>=60?'Atenção':'Melhorar'}
function sectorName(value?:string){return sectorOptions.find(x=>x[0]===value)?.[1]||'Geral'}
function revenueName(value?:string){return revenueOptions.find(x=>x[0]===value)?.[1]||'Mista'}
