import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {api,post} from './api';
import './document-workspace-center.css';

type Allowance={tier:'included'|'signatures_plus';included:number;used:number;remaining:number;limitReached:boolean;specialPlanRequired:boolean;periodStart:string;nextPeriodStart:string;policy:{perSignatureCharge:false;oneDocumentOneUsage:true;modeChangesPrice:false;cancelledStillCounts:true;workspacesPlanInferred:false;billingActivated:false}};
type SignatureModeId='electronic'|'icp_brasil';
type SignatureMode={id:SignatureModeId;label:string;available:boolean;signatureStandard:string;description:string};
type SignatureModes={modes:SignatureMode[];providerContractReady:boolean;externalActionsEnabled:boolean;privacy:any};
type DocRef={id:string;external_ref:string;title:string;status:string;document_type?:string|null;signature_status?:string|null;contact_name?:string|null;metadata?:any;updated_at?:string};
type Usage={id:string;document_ref_id:string;business_operation_id?:string|null;external_signature_request_id:string;status:string;signature_mode?:SignatureModeId;icp_status?:string|null;period_start:string;created_at:string;title:string};
type Center={documents:DocRef[];signatureUsage:Usage[];allowance:Allowance;signatureModes:SignatureModes;capabilities:{contracts:boolean;templates:boolean;signatures:boolean;icpBrasil:boolean;intelligence:boolean;docflow:boolean;validation:boolean;certificates:boolean};privacy:any;externalEffect:false};
type SignatureParty={id:string;name:string;email:string;status:string;signedAt?:string|null;url:string};
type Signature={id:string;title:string;status:string;contentHash:string;finalHash:string;totalParties:number;signedCount:number;pendingCount:number;progressPercent:number;parties:SignatureParty[]};
type IcpSession={id:string;status:string;signatureStandard:string;providerStatus?:string|null;completedAt?:string|null;hasCertificateEvidence:boolean;hasSignedDocument:boolean};
type IcpState={status:string;sessions:IcpSession[];requiresRetry?:boolean;message?:string};

const pct=(n:number,d:number)=>d?Math.min(100,Math.round((n/d)*100)):0;
const date=(value?:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(value)):'—';

export default function DocumentWorkspaceCenter(){
  const[data,setData]=useState<Center|null>(null),[selected,setSelected]=useState<DocRef|null>(null),[signature,setSignature]=useState<Signature|null>(null),[selectedMode,setSelectedMode]=useState<SignatureModeId>('electronic'),[activeMode,setActiveMode]=useState<SignatureModeId>('electronic'),[icp,setIcp]=useState<IcpState|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const pending=useMemo(()=>data?.signatureUsage.filter(item=>item.status==='pending')||[],[data]);
  const modeList=data?.signatureModes?.modes||[];
  const electronic=modeList.find(item=>item.id==='electronic');
  const icpMode=modeList.find(item=>item.id==='icp_brasil');
  const icpUsable=Boolean(icpMode?.available&&data?.signatureModes?.externalActionsEnabled);
  useEffect(()=>{void load()},[]);

  async function load(){setBusy(true);setError('');try{const next=await api<Center>('/v1/documents/docwallet-center');setData(next)}catch(e:any){setError(e?.message||'Não consegui carregar o centro documental.')}finally{setBusy(false)}}
  async function requestSignature(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const parties=[1,2,3,4].map(i=>({name:String(f.get(`name${i}`)||'').trim(),email:String(f.get(`email${i}`)||'').trim()})).filter(p=>p.name);if(!parties.length){setError('Informe pelo menos uma pessoa para assinar.');return}if(selectedMode==='icp_brasil'&&!icpUsable){setError('A assinatura ICP-Brasil ainda não está habilitada neste ambiente.');return}setBusy(true);setError('');try{const result=await post<{signature:Signature;mode:SignatureModeId;icp:IcpState|null;allowance:Allowance}>(`/v1/documents/${selected.id}/signatures`,{parties,mode:selectedMode,humanConfirmed:selectedMode==='icp_brasil'});setSignature(result.signature);setActiveMode(result.mode);setIcp(result.icp||null);setNotice(result.mode==='icp_brasil'?'Solicitação criada e etapa ICP-Brasil preparada. Cada signatário conclui com seu próprio certificado digital no fluxo seguro da DocWallet.':'Documento enviado para assinatura eletrônica. Os links individuais foram preparados pela DocWallet.');await load()}catch(e:any){setError(e?.message||'Não foi possível solicitar assinatura.')}finally{setBusy(false)}}
  async function inspectSignature(id:string){setBusy(true);setError('');try{const result=await api<{signature:Signature;mode:SignatureModeId;icp:IcpState|null}>(`/v1/documents/signatures/${id}`);setSignature(result.signature);setActiveMode(result.mode||'electronic');setIcp(result.icp||null)}catch(e:any){setError(e?.message||'Não foi possível atualizar a assinatura.')}finally{setBusy(false)}}
  async function prepareIcpAgain(){if(!signature)return;setBusy(true);setError('');try{const result=await post<{icp:IcpState}>(`/v1/documents/signatures/${signature.id}/icp/prepare`,{humanConfirmed:true});setIcp(result.icp);setNotice('Etapa ICP-Brasil preparada novamente. O signatário segue pelo fluxo seguro da DocWallet.')}catch(e:any){setError(e?.message||'Não foi possível preparar a etapa ICP-Brasil.')}finally{setBusy(false)}}
  async function remind(party?:SignatureParty){if(!signature)return;setBusy(true);try{await post(`/v1/documents/signatures/${signature.id}/reminder`,{partyId:party?.id||null});setNotice('Lembrete preparado na DocWallet. O envio pelo canal aprovado será conectado sem expor o link técnico nesta tela.')}catch(e:any){setError(e?.message||'Não foi possível preparar o lembrete.')}finally{setBusy(false)}}

  const quota=data?.allowance;
  return <div className="dwWorkspace">
    <section className="dwWorkspaceHero"><div><p>DOCUMENTOS · DORA + DOCWALLET</p><h2>Documentos que trabalham junto com o seu negócio.</h2><span>Crie contratos, colete assinaturas, acompanhe prazos e transforme documentos em processos sem sair do NexOffice.</span></div>{quota&&<div className="dwQuota"><div><b>{quota.remaining}</b><span>assinaturas restantes</span></div><small>{quota.used} de {quota.included} usadas neste mês</small><div className="dwQuotaBar"><i style={{width:`${pct(quota.used,quota.included)}%`}}/></div>{quota.tier==='included'?<em>6 documentos/mês incluídos no NexOffice</em>:<em>Assinaturas+ ativo · {quota.included}/mês</em>}</div>}</section>

    <div className="dwFeatureGrid">
      <article><i>✎</i><b>Contratos & modelos</b><p>Escolha um modelo, vincule o cliente e crie o contrato com a DocWallet por baixo.</p><small>Use “Novo contrato” nesta tela.</small></article>
      <article><i>✓</i><b>Assinaturas</b><p>Eletrônica para o dia a dia ou ICP-Brasil quando precisar de certificado digital.</p><small>A modalidade não muda o consumo da franquia.</small></article>
      <article><i>◈</i><b>Inteligência</b><p>Dora encontra partes, valores, obrigações, renovações, vencimentos e alertas.</p><small>O arquivo bruto continua na DocWallet.</small></article>
      <article><i>⚡</i><b>DocFlow</b><p>Receba, extraia, revise, aprove e arquive documentos como processos.</p><small>Motor DocFlow disponível por baixo da experiência.</small></article>
      <article><i>#</i><b>Validação & certificados</b><p>Hashes e evidências verificáveis continuam sob responsabilidade da DocWallet.</p><small>Sem expor infraestrutura técnica ao cliente.</small></article>
    </div>

    {quota?.limitReached&&<section className="dwPlus"><div><b>Você usou as {quota.included} assinaturas incluídas deste mês.</b><p>Assinaturas+ aumenta a franquia mensal. Não há cobrança automática nem tarifa por assinatura avulsa.</p></div><button onClick={()=>setNotice('Interesse em Assinaturas+ registrado apenas como intenção nesta versão. Nenhuma cobrança foi criada.')}>Quero mais assinaturas</button></section>}
    {error&&<div className="dwCenterError">{error}</div>}{notice&&<div className="dwCenterNotice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}

    <section className="dwDocs"><div className="dwSectionHead"><div><p>MEUS DOCUMENTOS</p><h3>Contratos e documentos vinculados</h3></div><button onClick={()=>void load()} disabled={busy}>Atualizar</button></div>{data?.documents.length?<div className="dwDocGrid">{data.documents.map(doc=>{const use=pending.find(item=>item.document_ref_id===doc.id);return <article key={doc.id}><div><small>{doc.document_type||'documento'}{doc.contact_name?` · ${doc.contact_name}`:''}</small><b>{doc.title}</b><span>{doc.signature_status?`Assinatura: ${doc.signature_status}`:`Status: ${doc.status}`}{use?.signature_mode==='icp_brasil'?' · ICP-Brasil':''}</span></div><div className="dwDocActions">{use?<button onClick={()=>void inspectSignature(use.external_signature_request_id)}>Acompanhar assinatura</button>:<button disabled={Boolean(quota?.limitReached)} onClick={()=>{setSelected(doc);setSignature(null);setIcp(null);setSelectedMode('electronic')}}>Enviar para assinatura</button>}</div></article>})}</div>:<div className="dwEmpty">Ainda não há documentos DocWallet vinculados. Use <b>Novo contrato</b> para começar.</div>}</section>

    {selected&&!signature&&<section className="dwSignatureComposer"><div className="dwSectionHead"><div><p>ASSINATURA</p><h3>{selected.title}</h3><span>Escolha a modalidade e informe quem precisa assinar.</span></div><button className="secondary" onClick={()=>setSelected(null)}>Fechar</button></div><div className="dwSignatureModes"><button type="button" className={selectedMode==='electronic'?'active':''} onClick={()=>setSelectedMode('electronic')}><b>✓ Assinatura eletrônica</b><span>{electronic?.description||'Aceite eletrônico com trilha de evidências DocWallet.'}</span><small>Mais simples para contratos e documentos do dia a dia.</small></button><button type="button" disabled={!icpUsable} className={selectedMode==='icp_brasil'?'active':''} onClick={()=>icpUsable&&setSelectedMode('icp_brasil')}><b>◆ ICP-Brasil · certificado digital</b><span>{icpMode?.description||'Assinatura digital PAdES com certificado ICP-Brasil.'}</span><small>{icpUsable?'A1, A3 ou certificado em nuvem, conforme disponibilidade do signatário.':'Disponível quando o ambiente ICP-Brasil estiver habilitado.'}</small></button></div><form onSubmit={requestSignature}>{[1,2,3,4].map((n,index)=><div className="dwParty" key={n}><label>Nome {index===0?'*':''}<input name={`name${n}`} required={index===0} placeholder={index===0?'Cliente / responsável':'Outra parte (opcional)'}/></label><label>E-mail<input name={`email${n}`} type="email" placeholder="email@empresa.com"/></label></div>)}<footer><small>1 documento enviado = 1 uso da franquia, em qualquer modalidade e independentemente da quantidade de pessoas. {selectedMode==='icp_brasil'?'Ao continuar, você confirma a preparação da assinatura ICP-Brasil; o certificado e sua senha nunca passam pelo NexOffice.':'O conteúdo não passa pelo NexOffice.'}</small><button disabled={busy||Boolean(quota?.limitReached)||(selectedMode==='icp_brasil'&&!icpUsable)}>{busy?'Preparando…':selectedMode==='icp_brasil'?'Preparar assinatura ICP-Brasil':'Enviar para assinatura eletrônica'}</button></footer></form></section>}

    {signature&&<section className="dwSignatureStatus"><div className="dwSectionHead"><div><p>{activeMode==='icp_brasil'?'ASSINATURA DIGITAL ICP-BRASIL':'ASSINATURA ELETRÔNICA'}</p><h3>{signature.title}</h3><span>{signature.signedCount} de {signature.totalParties} concluída(s) · {signature.progressPercent}%</span></div><button onClick={()=>void inspectSignature(signature.id)} disabled={busy}>Atualizar</button></div>{activeMode==='icp_brasil'&&<div className={`dwIcpState ${icp?.status==='prepare_failed'?'attention':''}`}><div><b>ICP-Brasil · {icp?.status||'aguardando'}</b><span>O certificado, senha e sessão segura permanecem fora do NexOffice. Cada signatário conclui pelo fluxo da DocWallet.</span></div>{icp?.requiresRetry&&<button onClick={()=>void prepareIcpAgain()} disabled={busy}>Preparar novamente</button>}</div>}<div className="dwProgress"><i style={{width:`${signature.progressPercent}%`}}/></div><div className="dwSignerList">{signature.parties.map(p=><article key={p.id}><div><b>{p.name}</b><span>{p.email||'Sem e-mail'} · {p.status==='signed'?`assinado ${date(p.signedAt)}`:'pendente'}</span></div>{p.status!=='signed'&&<button onClick={()=>void remind(p)}>Preparar lembrete</button>}</article>)}</div><small className="dwPrivacy">Evidências sensíveis, IP, CPF, assinatura desenhada, geolocalização e dados do certificado permanecem na DocWallet/provedor seguro. O NexOffice recebe apenas progresso, referências, hashes e estado da modalidade.</small></section>}
  </div>;
}
