import {useEffect,useMemo,useState} from 'react';
import {api,post} from './api';
import './financial-engine-collections.css';

type Engine={configured:boolean;actionsEnabled:boolean;capabilities:string[];degraded?:boolean;requiresHumanApproval?:boolean;externalEffect:false};
type Receivable={id:string;description:string;amount_minor:number|string;due_at?:string;status:string;contact_name?:string;days_overdue?:number};
type Collections={summary:{overdue_count:number;overdue_minor:number|string};receivables:Receivable[]};
type Action={id:string;title:string;summary:string;status:string;autonomy:string;approval_id?:string|null;subject_id?:string|null;primary_action?:{type?:string;payload?:any}};
type ChargeOperation={configured:boolean;operation:any|null;externalEffect:false};
type RecurringRule={id:string;description:string;amount_minor:number|string;frequency:string;interval_count:number;next_run_at:string;active:boolean;contact_id?:string|null;metadata?:any};
type RecurringOperation={id:string;recurring_rule_id:string;provider_status:string;amount_minor:number|string;receipt:any;description?:string;frequency?:string;next_run_at?:string;contact_name?:string};

const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const date=(v?:string)=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(v)):'—';

export default function FinancialEngineCollectionsCenter(){
  const[engine,setEngine]=useState<Engine|null>(null),[collections,setCollections]=useState<Collections|null>(null),[actions,setActions]=useState<Action[]>([]),[charges,setCharges]=useState<Record<string,any>>({}),[rules,setRules]=useState<RecurringRule[]>([]),[recurring,setRecurring]=useState<RecurringOperation[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const financialActions=useMemo(()=>actions.filter(a=>{const type=String(a.primary_action?.type||'');return type.startsWith('payment.charge')||type.startsWith('payment.recurring')}),[actions]);
  useEffect(()=>{void load()},[]);

  async function load(){setError('');try{
    const[e,c,a,r,ro]=await Promise.all([
      api<Engine>('/v1/collections/payment-engine'),
      api<Collections>('/v1/collections/overview'),
      api<Action[]>('/v1/command/actions?includeDone=true'),
      api<RecurringRule[]>('/v1/recurring-rules'),
      api<RecurringOperation[]>('/v1/collections/recurring').catch(()=>[])
    ]);setEngine(e);setCollections(c);setActions(a);setRules(r);setRecurring(ro);
    const relevant=(c.receivables||[]).slice(0,30);const results=await Promise.all(relevant.map(async item=>[item.id,await api<ChargeOperation>(`/v1/collections/ledger/${item.id}/charge`).catch(()=>({configured:false,operation:null,externalEffect:false}))] as const));setCharges(Object.fromEntries(results.map(([id,result])=>[id,result.operation])));
  }catch(e:any){setError(e?.message||'Não foi possível carregar cobranças Pix.')}}
  function chargeActionFor(ledgerId:string){return financialActions.find(a=>a.primary_action?.type==='payment.charge.create'&&String(a.primary_action?.payload?.ledgerEntryId||a.subject_id||'')===ledgerId&&!['rejected','dismissed'].includes(a.status))}
  async function prepareCharge(id:string){setBusy(id);setError('');try{const result=await post<any>(`/v1/collections/ledger/${id}/create-charge`,{});setNotice(result?.action?.approval_id?'Cobrança preparada. Revise e aprove antes de gerar o Pix.':'Cobrança preparada na Central de Comando.');await load()}catch(e:any){setError(e?.message||'Não foi possível preparar a cobrança.')}finally{setBusy('')}}
  async function approve(action:Action){setBusy(action.id);setError('');try{await post(`/v1/command/actions/${action.id}/decision`,{decision:'approved'});setNotice('Ação aprovada. Nenhuma movimentação ocorreu ainda: confirme no próximo passo.');await load()}catch(e:any){setError(e?.message||'Não foi possível aprovar.')}finally{setBusy('')}}
  async function executeCharge(action:Action){if(!window.confirm('Gerar esta cobrança Pix agora? Esta confirmação cria a cobrança no provider financeiro.'))return;setBusy(action.id);setError('');try{await post(`/v1/collections/actions/${action.id}/execute-charge`,{humanConfirmed:true});setNotice('Cobrança Pix criada. O recebível continua aberto até a confirmação de pagamento.');await load()}catch(e:any){setError(e?.message||'Não foi possível gerar o Pix.')}finally{setBusy('')}}
  async function reconcile(id:string){setBusy(id);setError('');try{const result=await post<any>(`/v1/collections/ledger/${id}/reconcile-charge`,{});setNotice(result.ledgerMarkedPaid?'Pagamento confirmado. O recebível foi marcado como pago.':`Status atualizado: ${result.status||'aguardando pagamento'}.`);await load()}catch(e:any){setError(e?.message||'Não foi possível atualizar o pagamento.')}finally{setBusy('')}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Código Pix copiado.')}catch{setError('Não foi possível copiar automaticamente.')}}
  async function prepareRecurring(rule:RecurringRule){setBusy(rule.id);setError('');try{const result=await post<any>(`/v1/collections/recurring-rules/${rule.id}/prepare-pix-recurring`,{});setNotice(result?.action?.approval_id?'Pix recorrente preparado e aguardando aprovação.':'Pix recorrente preparado para revisão.');await load()}catch(e:any){setError(e?.message||'Não foi possível preparar o Pix recorrente.')}finally{setBusy('')}}
  async function executeRecurring(action:Action){if(!window.confirm('Ativar este Pix recorrente agora?'))return;setBusy(action.id);setError('');try{await post(`/v1/collections/actions/${action.id}/execute-recurring`,{humanConfirmed:true});setNotice('Pix recorrente ativado.');await load()}catch(e:any){setError(e?.message||'Não foi possível ativar a recorrência.')}finally{setBusy('')}}
  async function prepareCancel(operation:RecurringOperation){setBusy(operation.id);setError('');try{await post(`/v1/collections/recurring/${operation.id}/prepare-cancel`,{});setNotice('Cancelamento preparado e aguardando aprovação.');await load()}catch(e:any){setError(e?.message||'Não foi possível preparar o cancelamento.')}finally{setBusy('')}}
  async function executeCancel(action:Action){if(!window.confirm('Cancelar esta recorrência Pix agora?'))return;setBusy(action.id);setError('');try{await post(`/v1/collections/actions/${action.id}/execute-recurring-cancel`,{humanConfirmed:true});setNotice('Recorrência Pix cancelada.');await load()}catch(e:any){setError(e?.message||'Não foi possível cancelar.')}finally{setBusy('')}}

  const recurringActions=financialActions.filter(a=>['payment.recurring.create','payment.recurring.cancel','payment.charge.recurring.create','payment.charge.recurring.cancel'].includes(String(a.primary_action?.type||'')));
  return <section className="pixEngine">
    <header className="pixEngineHead"><div><small>COBRANÇAS & RECORRÊNCIA</small><h3>Pix conectado ao seu financeiro</h3><p>Gere cobranças a partir dos recebíveis e concilie o pagamento sem duplicar lançamentos.</p></div><div className={`pixEngineStatus ${engine?.configured?'ready':''}`}><b>{engine?.configured?'Motor Pix conectado':'Pix automatizado não conectado'}</b><span>{engine?.configured?(engine.actionsEnabled?'Ações financeiras habilitadas com aprovação humana.':'Leitura pronta · criação real ainda bloqueada no ambiente.'):'Você pode continuar usando o Pix manual do NexOffice.'}</span></div></header>
    {error&&<div className="pixEngineError">{error}</div>}{notice&&<div className="pixEngineNotice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}

    <div className="pixEngineSection"><div className="pixEngineTitle"><b>Contas a receber</b><span>{collections?.summary?.overdue_count||0} vencida(s) · {money(collections?.summary?.overdue_minor)}</span></div><div className="pixEngineList">{collections?.receivables?.length?collections.receivables.slice(0,30).map(item=>{const action=chargeActionFor(item.id),operation=charges[item.id],receipt=operation?.receipt||{};return <article key={item.id}><div className="pixEngineMain"><small>{item.contact_name||'Cliente'} · {item.due_at?`vence ${date(item.due_at)}`:'sem vencimento'}</small><b>{item.description}</b><strong>{money(item.amount_minor)}</strong>{operation&&<span className={`pixBadge ${String(operation.provider_status).toLowerCase()}`}>Pix: {operation.provider_status}</span>}</div><div className="pixEngineActions">{!operation&&!action&&<button disabled={!engine?.configured||busy===item.id} onClick={()=>void prepareCharge(item.id)}>Preparar Pix</button>}{action?.status==='open'&&action.approval_id&&<button className="secondary" disabled={busy===action.id} onClick={()=>void approve(action)}>Revisar e aprovar</button>}{action?.status==='approved'&&<button disabled={!engine?.actionsEnabled||busy===action.id} onClick={()=>void executeCharge(action)}>Gerar Pix</button>}{operation&&receipt.brCode&&<button className="secondary" onClick={()=>void copy(receipt.brCode)}>Copiar Pix</button>}{operation&&receipt.paymentLinkUrl&&<a href={receipt.paymentLinkUrl} target="_blank" rel="noreferrer">Abrir cobrança ↗</a>}{operation&&!['PAID','CANCELED','EXPIRED'].includes(String(operation.provider_status))&&<button className="secondary" disabled={busy===item.id} onClick={()=>void reconcile(item.id)}>Atualizar pagamento</button>}</div></article>}):<div className="pixEngineEmpty">Nenhum recebível vencido ou aberto para cobrar agora.</div>}</div></div>

    <div className="pixEngineSection"><div className="pixEngineTitle"><b>Pix recorrente</b><span>Mensalidades e cobranças repetidas, sempre com aprovação.</span></div>{recurringActions.length>0&&<div className="pixPendingActions">{recurringActions.filter(a=>!['done','rejected','dismissed'].includes(a.status)).map(action=><article key={action.id}><div><b>{action.title}</b><span>{action.summary}</span></div>{action.status==='open'&&action.approval_id?<button className="secondary" onClick={()=>void approve(action)}>Aprovar</button>:action.status==='approved'?<button disabled={!engine?.actionsEnabled} onClick={()=>void(String(action.primary_action?.type||'').endsWith('.cancel')?executeCancel(action):executeRecurring(action))}>{String(action.primary_action?.type||'').endsWith('.cancel')?'Confirmar cancelamento':'Ativar recorrência'}</button>:null}</article>)}</div>}
      <div className="pixRecurringGrid">{rules.filter(r=>r.active&&r.frequency!=='yearly'&&Number(r.interval_count)===1).slice(0,12).map(rule=>{const op=recurring.find(item=>item.recurring_rule_id===rule.id&&item.provider_status!=='CANCELED');return <article key={rule.id}><small>{rule.frequency==='weekly'?'Semanal':'Mensal'} · próxima {date(rule.next_run_at)}</small><b>{rule.description}</b><strong>{money(rule.amount_minor)}</strong>{op?<><span className="pixBadge">{op.provider_status}</span><button className="secondary" onClick={()=>void prepareCancel(op)}>Preparar cancelamento</button></>:<button disabled={!engine?.configured||busy===rule.id} onClick={()=>void prepareRecurring(rule)}>Preparar Pix recorrente</button>}</article>})}</div>
    </div>
    <footer>O NexOffice registra aprovação e reconciliação. O provider financeiro permanece invisível e nenhuma transferência de saída faz parte deste módulo.</footer>
  </section>;
}
