import {useEffect,useState,type FormEvent} from 'react';
import {api,post,session} from './api';

type Signal={id:string;code:string;level:'info'|'attention'|'critical';title:string;message:string;evidence:Record<string,unknown>};
type Recommendation={id:string;priority:string;title:string;message:string;status:string;rationale:Record<string,unknown>;options:Array<{label:string;action:string}>};
type Intelligence={snapshot:{id:string;as_of:string};metrics:any;signals:Signal[];recommendations:Recommendation[];decisions:any[]};
type Simulation={baseProjectedCashMinor:number;simulatedProjectedCashMinor:number;deltaMinor:number;risk:string;message:string;assumptions:any};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const pct=(value:any)=>value===null||value===undefined?'—':`${Number(value).toFixed(1)}%`;
const shortDate=(value?:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(value)):'—';

export default function FinancialIntelligenceCenter(){
  const [sessionKey,setSessionKey]=useState(()=>`${session.token()}|${session.workspace()}`);const authenticated=Boolean(session.token()&&session.workspace());
  const [open,setOpen]=useState(false);const [data,setData]=useState<Intelligence|null>(null);const [simulation,setSimulation]=useState<Simulation|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{const timer=setInterval(()=>{const next=`${session.token()}|${session.workspace()}`;setSessionKey(prev=>prev===next?prev:next)},700);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!authenticated){setOpen(false);return}if(open)load()},[sessionKey,open]);
  async function load(refresh=false){setBusy(true);setError('');try{setData(refresh?await post<Intelligence>('/v1/finance/intelligence/refresh',{}):await api<Intelligence>('/v1/finance/intelligence'))}catch(e:any){setError(e?.message||'Não foi possível analisar o financeiro.')}finally{setBusy(false)}}
  async function decide(id:string,decision:'accepted'|'dismissed'){setBusy(true);try{await post(`/v1/finance/recommendations/${id}/decision`,{decision,note:decision==='accepted'?'Ação aceita pelo usuário.':'Recomendação dispensada.',expected:{}});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function simulate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{setSimulation(await post<Simulation>('/v1/finance/intelligence/simulate',{revenueChangePct:Number(f.get('revenueChangePct')||0),expenseChangePct:Number(f.get('expenseChangePct')||0),oneOffInflowMinor:Math.round(Number(f.get('oneOffInflow')||0)*100),oneOffOutflowMinor:Math.round(Number(f.get('oneOffOutflow')||0)*100)}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  if(!authenticated)return null;
  const m=data?.metrics||{},actualMarketing=m.marketing?.actual||null;
  return <>
    <button className="financeIntelLauncher" onClick={()=>setOpen(true)}>◉ <span>Visão financeira</span></button>
    {open&&<div className="financeIntelBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="financeIntelPanel">
      <header><div><small>NEXOFFICE · FINANÇAS</small><h2>Visão financeira</h2><p>O que está acontecendo, o que pode acontecer e onde vale agir.</p></div><div className="financeIntelHeaderActions"><button onClick={()=>load(true)}>Atualizar análise</button><button className="close" onClick={()=>setOpen(false)}>×</button></div></header>
      {busy&&<div className="financeIntelBusy"/>}{error&&<div className="financeIntelError">{error}</div>}
      <div className="financeIntelBody">{data?<>
        <div className="financeIntelSummary"><article><small>Caixa estimado agora</small><b>{money(m.currentCashMinor)}</b><span>contas cadastradas + entradas − saídas realizadas</span></article><article><small>Projeção em 30 dias</small><b className={Number(m.projectedCash30Minor)<0?'risk':''}>{money(m.projectedCash30Minor)}</b><span>{money(m.incoming30Minor)} a entrar · {money(m.outgoing30Minor)} a sair</span></article><article><small>A receber</small><b>{money(m.receivableMinor)}</b><span>{money(m.overdueReceivableMinor)} vencidos</span></article><article><small>Margem de caixa · 90 dias</small><b>{pct(m.operatingCashMarginPct)}</b><span>entradas recebidas menos despesas pagas</span></article></div>
        {m.firstShortfallAt&&<div className="financeIntelHeadline"><div><small>ATENÇÃO</small><h3>Com os lançamentos atuais, pode faltar caixa por volta de {shortDate(m.firstShortfallAt)}.</h3><p>Essa projeção não inclui recebíveis já vencidos como entrada garantida. Atualize os lançamentos sempre que houver mudanças.</p></div><b>{money(m.firstShortfallBalanceMinor)}</b></div>}
        <div className="financeIntelGrid"><section><div className="financeIntelSectionTitle"><div><small>ALERTAS</small><h3>O que merece atenção</h3></div><span>{data.signals.length}</span></div><div className="financeIntelSignals">{data.signals.map(s=><article key={s.id} className={s.level}><i/><div><b>{s.title}</b><p>{s.message}</p><Evidence evidence={s.evidence}/></div></article>)}</div></section>
        <section><div className="financeIntelSectionTitle"><div><small>PRÓXIMOS PASSOS</small><h3>O que você pode fazer</h3></div></div><div className="financeIntelRecommendations">{data.recommendations.filter(r=>r.status==='open').length?data.recommendations.filter(r=>r.status==='open').map(r=><article key={r.id}><div className="recTop"><span>{r.priority==='urgent'?'Prioridade máxima':r.priority==='high'?'Alta prioridade':'Recomendação'}</span></div><b>{r.title}</b><p>{r.message}</p><div className="recActions"><button className="primary" onClick={()=>decide(r.id,'accepted')}>Vou fazer</button><button onClick={()=>decide(r.id,'dismissed')}>Agora não</button></div></article>):<div className="financeIntelEmpty">Nenhuma recomendação aberta agora.</div>}</div></section></div>
        <section className="financeIntelScenario"><div><small>E SE?</small><h3>Simule uma mudança antes de decidir</h3><p>Veja o efeito aproximado no caixa de 30 dias. A simulação usa os lançamentos atuais e não movimenta dinheiro.</p></div><form onSubmit={simulate}><label>Receita muda<input name="revenueChangePct" type="number" defaultValue="0" step="1"/><span>%</span></label><label>Despesas mudam<input name="expenseChangePct" type="number" defaultValue="0" step="1"/><span>%</span></label><label>Entrada extra<input name="oneOffInflow" type="number" defaultValue="0" step="0.01"/><span>R$</span></label><label>Saída extra<input name="oneOffOutflow" type="number" defaultValue="0" step="0.01"/><span>R$</span></label><button className="primary">Simular</button></form>{simulation&&<div className={`financeIntelSimulation ${simulation.risk}`}><div><small>PROJEÇÃO DO CENÁRIO</small><b>{money(simulation.simulatedProjectedCashMinor)}</b></div><p>{simulation.message}</p><span>{simulation.deltaMinor>=0?'+':''}{money(simulation.deltaMinor)} versus o cenário atual</span></div>}</section>
        <section className="financeIntelContext"><div><small>NEGÓCIO</small><b>{money(m.weightedPipelineMinor)}</b><span>pipeline ponderado estimado</span></div><div><small>CONCENTRAÇÃO</small><b>{m.topClientName||'—'}</b><span>{m.topClientSharePct?`${m.topClientSharePct}% das entradas em 90 dias`:'sem leitura suficiente'}</span></div><div><small>{actualMarketing?'MARKETING · REAL':'MARKETING'}</small><b>{actualMarketing?money(actualMarketing.costMinor):m.marketing?.configured?money(m.marketing.monthlyBudgetMinor):'Não conectado'}</b><span>{actualMarketing?`${actualMarketing.clicks||0} cliques · ${actualMarketing.conversions||0} conversões${actualMarketing.roas!==null&&actualMarketing.roas!==undefined?` · ROAS ${Number(actualMarketing.roas).toFixed(2)}x`:''}`:m.marketing?.configured?`${m.marketing.projects||0} projetos · ${m.marketing.readyCampaigns||0} prontos · orçamento planejado`:'MODO pode enriquecer esta visão'}</span></div><div><small>FISCAL</small><b>{m.fiscal?.connected?'Conectado':'Não conectado'}</b><span>{m.fiscal?.connected?'contexto fiscal disponível':'TaxAgent poderá ampliar a leitura'}</span></div></section>
        <footer>Última análise: {new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(data.snapshot.as_of))}. Projeções são estimativas baseadas nos dados registrados no NexOffice.</footer>
      </>:<div className="financeIntelEmpty">Carregando sua visão financeira…</div>}</div>
    </section></div>}
  </>;
}
function Evidence({evidence}:{evidence:Record<string,unknown>}){const labels:Record<string,string>={overdueReceivableMinor:'Vencido',projectedCash30Minor:'Caixa 30d',incoming30Minor:'Entradas 30d',outgoing30Minor:'Saídas 30d',sharePct:'Participação',monthlyBurnMinor:'Déficit mensal',runwayMonths:'Reserva'};const items=Object.entries(evidence||{}).filter(([,v])=>v!==null&&v!==undefined).slice(0,4);return items.length?<div className="financeIntelEvidence">{items.map(([k,v])=><span key={k}><small>{labels[k]||k}</small><b>{k.toLowerCase().includes('minor')?money(v):k.toLowerCase().includes('pct')||k==='sharePct'?`${v}%`:String(v)}</b></span>)}</div>:null}
