import {useEffect,useState,type FormEvent} from 'react';
import {api,post} from './api';
import './fiscal-center-v2.css';

type Stage={id:string;label:string;status:string;detail?:string};
type Journey={connected:boolean;companyId?:string;environment?:'test'|'production';fiscal_status:string;onboarding_status?:string;route?:{resolved_route?:string;resolved_provider?:string};stages?:Stage[];blockers?:string[];next_action?:any;company?:{id:string;name?:string;city_code?:string;tax_regime?:string};safeguards?:Record<string,unknown>};
type FiscalStatus={recentActions:Array<{id:string;title:string;summary:string;status:string;approval_id?:string|null;created_at:string}>};

const labels:Record<string,string>={ACTION_REQUIRED:'Ação necessária',READY_FOR_ASSESSMENT:'Pronto para avaliação',READY_FOR_PREFLIGHT:'Pronto para validação',HOMOLOGATION_READY:'Fiscal preparado',PARTIAL_VERIFICATION:'Verificação parcial',PREFLIGHT_BLOCKED:'Validação bloqueada',NOT_CONFIGURED:'Fiscal não ativado'};

export default function FiscalCenterV2(){
  const [journey,setJourney]=useState<Journey|null>(null);const [history,setHistory]=useState<FiscalStatus['recentActions']>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
  useEffect(()=>{void load()},[]);
  async function load(){setError('');try{const [j,s]=await Promise.all([api<Journey>('/v1/fiscal/onboarding'),api<FiscalStatus>('/v1/fiscal/status')]);setJourney(j);setHistory(s.recentActions||[])}catch(e:any){setError(e?.message||'Não foi possível carregar o Fiscal.')}}
  async function act<T>(name:string,fn:()=>Promise<T>,message:string){setBusy(name);setError('');setNotice('');try{const result=await fn();setNotice(message);await load();return result}catch(e:any){setError(e?.message||'Operação fiscal não concluída.');return null}finally{setBusy('')}}
  async function activate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await act('activate',()=>post('/v1/fiscal/onboarding/activate',{organizationName:String(f.get('organizationName')||'').trim(),companyName:String(f.get('companyName')||'').trim(),taxId:String(f.get('taxId')||'').trim(),cityCode:String(f.get('cityCode')||'').trim(),municipalRegistration:String(f.get('municipalRegistration')||'').trim()||undefined,taxRegime:String(f.get('taxRegime')||'regular').trim(),environment:String(f.get('environment')||'test')}),'Fiscal ativado. O TaxAgent identificou a rota e montou seu checklist.')}
  async function profile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body:any={};for(const [form,key] of [['cityCode','city_code'],['municipalRegistration','municipal_registration'],['taxRegime','tax_regime']] as const){const value=String(f.get(form)||'').trim();if(value)body[key]=value}await act('profile',()=>post('/v1/fiscal/onboarding/profile',body),'Perfil fiscal atualizado e reavaliado.')}
  async function certificate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file');if(!(file instanceof File)||!file.size){setError('Selecione o certificado A1.');return}const password=String(f.get('password')||'');if(!password){setError('Informe a senha do A1.');return}await act('certificate',async()=>post('/v1/fiscal/onboarding/certificate',{pfxBase64:await fileToBase64(file),password}),'A1 validado e enviado diretamente ao cofre fiscal.');(e.currentTarget as HTMLFormElement).reset()}
  async function providerCredentials(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),provider=String(f.get('provider')||'').trim(),login=String(f.get('login')||'').trim(),password=String(f.get('password')||'');const credentials:any={};if(login)credentials.login=login;if(password)credentials.password=password;await act('credentials',()=>post('/v1/fiscal/onboarding/provider-credentials',{provider,credentials,note:'NexOffice Fiscal Center'}),'Credencial armazenada no cofre fiscal do TaxAgent.');(e.currentTarget as HTMLFormElement).reset()}
  async function advance(){await act('advance',()=>post('/v1/fiscal/onboarding/advance',{}),'Validação fiscal executada sem emissão.')}
  async function prepare(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const result:any=await act('invoice',()=>post('/v1/fiscal/invoices/prepare',{customer:{taxId:String(f.get('taxId')||'').trim(),name:String(f.get('customerName')||'').trim(),cityCode:String(f.get('customerCityCode')||'').trim()},service:{description:String(f.get('description')||'').trim(),amount:Number(f.get('amount')||0),nationalServiceCode:String(f.get('nationalServiceCode')||'').trim()||undefined,serviceLocationCityCode:String(f.get('serviceCityCode')||'').trim()||undefined}}),'NFS-e preparada. A transmissão continua dependendo da aprovação na Central de Comando.');if(result)(e.currentTarget as HTMLFormElement).reset()}
  const ready=journey?.fiscal_status==='HOMOLOGATION_READY';
  return <div className="fiscalV2">
    <div className="fiscalHero"><div><small>FISCAL · TAXAGENT</small><h4>{journey?.connected?'Fiscal da sua empresa':'Ative o Fiscal em poucos passos'}</h4><p>O NexOffice cuida da experiência. O TaxAgent continua sendo o motor fiscal e decide a rota, requisitos e validações.</p></div>{journey?.connected&&<span className={`fiscalState ${ready?'ready':''}`}>{labels[journey.fiscal_status]||journey.fiscal_status}</span>}</div>
    {error&&<div className="opsError">{error}</div>}{notice&&<div className="opsNotice">{notice}</div>}
    {!journey?.connected?<form className="fiscalActivate" onSubmit={activate}><div className="opsSection"><b>Dados da empresa</b><small>O TaxAgent reutiliza a empresa pelo CNPJ quando ela já existir. Nenhuma API key precisa ser informada.</small></div><input name="organizationName" placeholder="Nome da organização" required/><input name="companyName" placeholder="Razão social" required/><input name="taxId" placeholder="CNPJ" required/><input name="cityCode" pattern="[0-9]{7}" placeholder="Município IBGE" required/><input name="municipalRegistration" placeholder="Inscrição Municipal, se já souber"/><input name="taxRegime" defaultValue="regular" placeholder="Regime tributário"/><select name="environment" defaultValue="test"><option value="test">Homologação / teste</option><option value="production">Produção</option></select><button disabled={busy==='activate'}>{busy==='activate'?'Ativando…':'Ativar Fiscal'}</button></form>:<>
      <div className="fiscalSummary"><div><span>Rota</span><b>{journey.route?.resolved_route||'—'}</b></div><div><span>Provedor</span><b>{journey.route?.resolved_provider||'—'}</b></div><div><span>Ambiente</span><b>{journey.environment==='production'?'Produção':'Teste'}</b></div></div>
      <div className="opsSection"><b>Preparação fiscal</b><small>O checklist muda conforme município, rota e requisitos reais.</small></div><div className="fiscalStages">{journey.stages?.map(stage=><article key={stage.id}><span className={`stageDot ${stage.status}`}/><div><b>{stage.label}</b><small>{stage.detail||stage.status}</small></div><em>{stage.status.replaceAll('_',' ')}</em></article>)}</div>
      {journey.blockers?.length?<div className="fiscalBlockers"><b>O que falta agora</b>{journey.blockers.map(x=><span key={x}>• {x}</span>)}</div>:null}
      <form className="opsMiniForm fiscalV2Form" onSubmit={profile}><b>Perfil fiscal</b><input name="cityCode" defaultValue={journey.company?.city_code||''} pattern="[0-9]{7}" placeholder="Município IBGE"/><input name="municipalRegistration" placeholder="Inscrição Municipal / CCM"/><input name="taxRegime" defaultValue={journey.company?.tax_regime||''} placeholder="Regime tributário"/><button disabled={busy==='profile'}>Salvar e reavaliar</button></form>
      <form className="opsMiniForm fiscalV2Form" onSubmit={certificate}><b>Certificado A1</b><small>O arquivo passa pelo NexOffice somente em memória e segue direto para o Certificate Vault do TaxAgent.</small><input name="file" type="file" accept=".pfx,.p12,application/x-pkcs12"/><input name="password" type="password" autoComplete="new-password" placeholder="Senha do A1"/><button disabled={busy==='certificate'}>Enviar A1</button></form>
      <form className="opsMiniForm fiscalV2Form" onSubmit={providerCredentials}><b>Credencial municipal/provedor</b><small>Use apenas se o checklist pedir. O NexOffice não persiste login ou senha.</small><input name="provider" placeholder="Provedor, ex.: giss"/><input name="login" placeholder="Login"/><input name="password" type="password" autoComplete="new-password" placeholder="Senha/token"/><button disabled={busy==='credentials'}>Salvar no cofre</button></form>
      <div className="fiscalAdvance"><div><b>{ready?'Fiscal preparado':'Validar preparação'}</b><small>{ready?'A empresa está pronta para um teste fiscal autorizado. Emissão automática continua desabilitada.':'O preflight só roda quando todos os requisitos locais estiverem completos e nunca emite nota.'}</small></div><button onClick={advance} disabled={busy==='advance'}>{ready?'Revalidar':'Validar e avançar'}</button></div>
      <div className={`fiscalInvoice ${ready?'enabled':''}`}><div className="opsSection"><b>Preparar NFS-e</b><small>{ready?'A preparação cria uma ação aprovável; transmitir continua exigindo aprovação humana.':'Disponível quando o onboarding fiscal chegar a Fiscal preparado.'}</small></div><form className="opsMiniForm fiscalForm" onSubmit={prepare}><input name="taxId" placeholder="CPF/CNPJ do tomador" required/><input name="customerName" placeholder="Nome do tomador" required/><input name="customerCityCode" pattern="[0-9]{7}" placeholder="Município IBGE do tomador" required/><input name="description" placeholder="Descrição do serviço" required/><input name="amount" type="number" step="0.01" min="0.01" placeholder="Valor R$" required/><input name="nationalServiceCode" placeholder="Código tributação nacional"/><input name="serviceCityCode" pattern="[0-9]{7}" placeholder="Município IBGE da prestação"/><button disabled={!ready||busy==='invoice'}>Preparar para aprovação</button></form></div>
      <div className="opsSection"><b>Histórico recente</b></div><div className="opsList">{history.length?history.map(a=><article key={a.id}><div className="opsRowTop"><div><b>{a.title}</b><small>{a.summary}</small></div><span className={`opsStatus ${a.status}`}>{a.status}</span></div><div className="opsMeta"><span>{a.approval_id?'Aprovação vinculada':'Sem aprovação'}</span><span>{new Date(a.created_at).toLocaleDateString('pt-BR')}</span></div></article>):<div className="opsEmpty">Nenhuma emissão fiscal preparada ainda.</div>}</div>
    </>}
    <div className="fiscalSafety">A1 e credenciais ficam no TaxAgent. O NexOffice mantém somente vínculo, status e evidências necessárias para operar.</div>
  </div>
}

async function fileToBase64(file:File){const buffer=await file.arrayBuffer();const bytes=new Uint8Array(buffer);let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(binary)}
