import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {api,patch,post} from './api';
import './fiscal-homologation-console.css';

type Operation={id:string;title:string;contact_name?:string|null};
type CaseStatus='planned'|'ready'|'blocked'|'passed'|'failed'|'skipped';
type RegistrationContext='available'|'not_applicable'|'unavailable'|'unknown';
type HomologationCase={id:string;operation_id?:string|null;municipality_name:string;municipality_ibge:string;provider_hint?:string|null;municipal_registration_context:RegistrationContext;integration_path?:string|null;scenario_label:string;status:CaseStatus;environment:'test';result_code?:string|null;result_message?:string|null;safe_references?:{accessKey?:string|null;providerReference?:string|null};evidence?:Record<string,string|number|boolean|null>;notes?:string|null;created_at:string;updated_at:string};
type MatrixResponse={cases:HomologationCase[];summary:{total:number;byStatus:Record<string,number>;byMunicipality:Record<string,number>};policy:{environment:'test';executionAvailable:false;manualEvidenceOnly:true;productionEnabled:false;municipalRegistrationUniversallyRequired:false};externalEffect:false};

type Props={onClose:()=>void};

const statusLabel:Record<CaseStatus,string>={planned:'Planejado',ready:'Pronto p/ teste',blocked:'Bloqueado',passed:'Aprovado',failed:'Falhou',skipped:'Ignorado'};
const registrationLabel:Record<RegistrationContext,string>={available:'IM disponível',not_applicable:'IM não aplicável',unavailable:'IM indisponível',unknown:'IM desconhecida'};

export default function FiscalHomologationConsole({onClose}:Props){
  const [matrix,setMatrix]=useState<MatrixResponse|null>(null),[operations,setOperations]=useState<Operation[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[resultCase,setResultCase]=useState<HomologationCase|null>(null);
  useEffect(()=>{void load()},[]);
  async function load(){setError('');try{const [m,ops]=await Promise.all([api<MatrixResponse>('/v1/fiscal/homologation/cases'),api<Operation[]>('/v1/business-operations')]);setMatrix(m);setOperations(ops)}catch(e:any){setError(e?.message||'Não foi possível carregar a matriz de homologação.')}}
  const municipalities=useMemo(()=>Object.keys(matrix?.summary.byMunicipality||{}).length,[matrix]);
  async function createCase(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy('create');setError('');setNotice('');try{await post('/v1/fiscal/homologation/cases',{operationId:String(f.get('operationId')||'')||null,municipalityName:String(f.get('municipalityName')||''),municipalityIbge:String(f.get('municipalityIbge')||'').replace(/\D/g,''),providerHint:String(f.get('providerHint')||'').trim()||null,municipalRegistrationContext:String(f.get('municipalRegistrationContext')||'unknown'),integrationPath:String(f.get('integrationPath')||'').trim()||null,scenarioLabel:String(f.get('scenarioLabel')||''),notes:String(f.get('notes')||'').trim()||null});form.reset();setNotice('Caso de homologação criado em ambiente de teste. Nenhuma emissão foi executada.');await load()}catch(e:any){setError(e?.message||'Não foi possível criar o caso.')}finally{setBusy('')}}
  async function recordResult(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!resultCase)return;const form=e.currentTarget,f=new FormData(form);setBusy(`result:${resultCase.id}`);setError('');setNotice('');try{const evidenceNote=String(f.get('evidenceNote')||'').trim();await patch(`/v1/fiscal/homologation/cases/${resultCase.id}/result`,{status:String(f.get('status')||'ready'),resultCode:String(f.get('resultCode')||'').trim()||null,resultMessage:String(f.get('resultMessage')||'').trim()||null,safeReferences:{accessKey:String(f.get('accessKey')||'').trim()||null,providerReference:String(f.get('providerReference')||'').trim()||null},evidence:evidenceNote?{operatorNote:evidenceNote}:{},notes:String(f.get('notes')||'').trim()||null});setResultCase(null);setNotice('Resultado registrado manualmente. O NexOffice não executou o teste fiscal.');await load()}catch(e:any){setError(e?.message||'Não foi possível registrar o resultado.')}finally{setBusy('')}}
  return <div className="fhc" role="dialog" aria-label="Homologação Fiscal"><div className="fhcHead"><div><small>TAXAGENT · HOMOLOGAÇÃO</small><h4>Homologation Console</h4><p>Matriz operacional de testes fiscais. Registro e evidência somente; execução externa indisponível.</p></div><button onClick={onClose}>×</button></div>
    <div className="fhcPolicy"><b>Ambiente fixo: TESTE</b><span>executionAvailable=false · productionEnabled=false · manualEvidenceOnly=true</span><small>Inscrição Municipal não é presumida como requisito universal. O contexto é registrado por caso.</small></div>
    {error&&<div className="fhcError">{error}</div>}{notice&&<div className="fhcNotice">{notice}</div>}
    <div className="fhcStats"><span><small>Casos</small><b>{matrix?.summary.total||0}</b></span><span><small>Municípios</small><b>{municipalities}</b></span><span><small>Aprovados</small><b>{matrix?.summary.byStatus?.passed||0}</b></span><span><small>Bloqueados</small><b>{matrix?.summary.byStatus?.blocked||0}</b></span></div>
    <form className="fhcForm" onSubmit={createCase}><b>Novo caso</b><select name="operationId"><option value="">Sem operação vinculada</option>{operations.map(op=><option key={op.id} value={op.id}>{op.title}{op.contact_name?` · ${op.contact_name}`:''}</option>)}</select><div className="fhcGrid"><input name="municipalityName" placeholder="Município" required/><input name="municipalityIbge" inputMode="numeric" pattern="\d{7}" maxLength={7} placeholder="IBGE · 7 dígitos" required/></div><select name="municipalRegistrationContext" defaultValue="unknown"><option value="unknown">IM desconhecida</option><option value="available">IM disponível</option><option value="not_applicable">IM não aplicável</option><option value="unavailable">IM indisponível</option></select><input name="providerHint" placeholder="Provider/caminho municipal · opcional"/><input name="integrationPath" placeholder="Caminho de integração · opcional"/><input name="scenarioLabel" placeholder="Cenário · ex.: prestador sem IM em Santos" required/><textarea name="notes" placeholder="Notas internas · opcional"/><button className="primary" disabled={busy==='create'}>{busy==='create'?'Criando…':'Adicionar à matriz'}</button><small>Adicionar um caso não prepara nem emite nota.</small></form>
    <section className="fhcCases">{matrix?.cases.length?matrix.cases.map(item=><article key={item.id}><div className="fhcCaseHead"><div><b>{item.scenario_label}</b><small>{item.municipality_name} · {item.municipality_ibge} · {registrationLabel[item.municipal_registration_context]}</small></div><span className={`fhcStatus ${item.status}`}>{statusLabel[item.status]}</span></div><p>{item.provider_hint||'Provider não informado'}{item.integration_path?` · ${item.integration_path}`:''}</p>{item.result_message&&<small>Resultado: {item.result_message}</small>}<div className="fhcCaseActions"><button onClick={()=>setResultCase(item)}>Registrar resultado</button></div></article>):<div className="fhcEmpty">Nenhum caso cadastrado. Comece pelos municípios/caminhos fiscais que realmente precisam ser homologados.</div>}</section>
    {resultCase&&<form className="fhcResult" onSubmit={recordResult}><div className="fhcResultHead"><div><small>RESULTADO MANUAL</small><b>{resultCase.scenario_label}</b></div><button type="button" onClick={()=>setResultCase(null)}>×</button></div><select name="status" defaultValue="ready"><option value="ready">Pronto p/ teste</option><option value="blocked">Bloqueado</option><option value="passed">Aprovado</option><option value="failed">Falhou</option><option value="skipped">Ignorado</option></select><input name="resultCode" placeholder="Código/erro retornado · opcional"/><textarea name="resultMessage" placeholder="Resumo do resultado · opcional"/><input name="accessKey" placeholder="Access key segura · opcional"/><input name="providerReference" placeholder="Provider reference segura · opcional"/><textarea name="evidenceNote" placeholder="Evidência operacional curta · sem payload fiscal bruto"/><textarea name="notes" placeholder="Notas adicionais · opcional"/><button className="primary" disabled={busy.startsWith('result:')}>{busy.startsWith('result:')?'Salvando…':'Registrar resultado manual'}</button><small>Este formulário registra evidência de um teste realizado fora do console. Ele não executa TaxAgent.</small></form>}
  </div>;
}
