import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {api,session} from './api';
import './home-v2.css';

type Dashboard={finance?:{receivable_minor?:number;overdue_count?:number};crm?:{open_deals?:number;open_pipeline_minor?:number};appointments?:{today_appointments?:number}};
type Area={id:string;attention:number};
type Overview={areas:Area[];pendingApprovals:number};
type Founder={health?:{score:number|null;summary?:string|null};money?:{overdueMinor:number;overdueCount:number};sales?:{pipelineMinor:number;openDeals:number};operations?:{overdueTasks:number;appointmentsToday:number}};
type Role='secretary'|'crm'|'erp'|'controller'|'documents'|'growth';
type QuickAction={id:string;title:string;description:string;target:string;icon:string;role?:Role;prompt?:string;featured?:boolean};
type Assistant={name:string;initial:string;role:string;power:string;target:string};

const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(minor||0)/100);
const quickActions:QuickAction[]=[
  {id:'bot',title:'Criar um Bot para minha empresa',description:'Atendimento, recepção, dúvidas e captação de contatos.',target:'Assistentes IA',icon:'◉',role:'secretary',prompt:'Quero criar um Bot para minha empresa. Me ajude a definir o que ele deve atender, quais informações precisa saber e como colocá-lo no ar com segurança.',featured:true},
  {id:'bot-crm',title:'Colocar Bot + CRM no ar',description:'O Bot atende, identifica o lead e organiza a oportunidade no funil.',target:'Assistentes IA',icon:'◎',role:'crm',prompt:'Quero colocar um Bot + CRM no ar. Estruture o fluxo de atendimento, captura do lead, qualificação, cadastro no CRM e follow-up.'},
  {id:'campaign',title:'Criar uma campanha publicitária',description:'Objetivo, público, anúncio, imagem, texto e preparação da mídia.',target:'Assistentes IA',icon:'✦',role:'growth',prompt:'Quero criar uma campanha publicitária. Organize objetivo, público, oferta, mensagem, criativos e próximos passos para revisão antes de publicar.',featured:true},
  {id:'instagram',title:'Criar conteúdo para Instagram',description:'Ideias, imagens, legendas e calendário de conteúdo.',target:'Assistentes IA',icon:'▣',role:'growth',prompt:'Quero criar conteúdo para Instagram. Monte ideias de posts, legendas, imagens sugeridas e uma sequência simples de publicação para minha empresa.'},
  {id:'funnel',title:'Criar um funil de vendas para meu site',description:'Captura → lead → contato → proposta → venda.',target:'Assistentes IA',icon:'▽',role:'crm',prompt:'Quero criar um funil de vendas ligado ao meu site. Estruture captura, qualificação, CRM, follow-up, proposta e fechamento.'},
  {id:'charge',title:'Criar uma cobrança',description:'Gere Pix, acompanhe pagamento e controle vencidos.',target:'Financeiro',icon:'$',featured:true},
  {id:'clients',title:'Gerenciar clientes e vendas',description:'Contatos, oportunidades, propostas e follow-ups.',target:'Clientes',icon:'◌'},
  {id:'day',title:'Organizar meu dia',description:'Agenda, tarefas, compromissos e prioridades.',target:'Operação',icon:'✓'},
  {id:'invoice',title:'Emitir uma nota fiscal',description:'Cliente, serviço e valor → revisar → aprovar → emitir.',target:'Financeiro',icon:'#'},
  {id:'document',title:'Criar contrato ou enviar para assinatura',description:'Contrato novo ou documento pronto para assinatura.',target:'Documentos',icon:'▱'},
  {id:'money',title:'Entender meu dinheiro',description:'Caixa, recebíveis, atrasados, despesas e resultado.',target:'Financeiro',icon:'◈'},
  {id:'team',title:'Perguntar para minha equipe de IA',description:'Use Maya, Theo, Dora, Clara, Nico e Sofia com o contexto da empresa.',target:'Assistentes IA',icon:'M',role:'growth',prompt:'Faça uma leitura do meu negócio agora e me diga o que merece minha atenção, o que mudou e qual é a melhor próxima ação.'}
];
const assistants:Assistant[]=[
  {name:'Maya',initial:'M',role:'Coordenação',power:'Cruza o contexto da empresa, organiza prioridades e coordena os demais especialistas.',target:'Assistentes IA'},
  {name:'Theo',initial:'T',role:'Financeiro',power:'Acompanha caixa, cobranças, Pix, vencimentos e sinais que pedem ação financeira.',target:'Financeiro'},
  {name:'Dora',initial:'D',role:'Documentos',power:'Entende contratos e documentos, encontra obrigações, prazos e pontos que merecem atenção.',target:'Documentos'},
  {name:'Clara',initial:'C',role:'Clientes & CRM',power:'Organiza clientes, oportunidades e follow-ups para não deixar receita escapar.',target:'Clientes'},
  {name:'Nico',initial:'N',role:'Operações',power:'Enxerga tarefas, gargalos e execução diária para manter o trabalho andando.',target:'Operação'},
  {name:'Sofia',initial:'S',role:'Recepção',power:'Cuida da entrada do trabalho, agenda, compromissos e encaminhamentos do dia.',target:'Operação'}
];
const navAliases:Record<string,string[]>={'Hoje':['Hoje','Central de Comando'],'Clientes':['Clientes','CRM'],'Financeiro':['Financeiro'],'Documentos':['Documentos'],'Operação':['Operação','Agenda & Tarefas'],'Crescimento':['Crescimento','Marketing'],'Assistentes IA':['Assistentes IA','Equipe Digital'],'Integrações':['Integrações'],'Configurações':['Configurações','Empresa & Acessos']};
function clickNav(match:string){const aliases=navAliases[match]||[match];const buttons=[...document.querySelectorAll<HTMLButtonElement>('.sidebar nav button')];buttons.find(b=>aliases.some(alias=>(b.textContent||'').toLowerCase().includes(alias.toLowerCase())))?.click()}
function launch(action:QuickAction){sessionStorage.removeItem('nexoffice.quickAction');if(action.role&&action.prompt){sessionStorage.setItem('nexoffice.quickAction',JSON.stringify({id:action.id,label:action.title,role:action.role,prompt:action.prompt,createdAt:new Date().toISOString()}))}else if(['charge','invoice'].includes(action.id)){sessionStorage.setItem('nexoffice.quickAction',JSON.stringify({id:action.id,label:action.title,target:action.target,createdAt:new Date().toISOString()}))}clickNav(action.target)}
function capitalizedFirstName(value:string){const first=value.trim().split(/\s+/)[0]||'';return first?first.charAt(0).toLocaleUpperCase('pt-BR')+first.slice(1):''}

export default function HomeV2(){
  const[host,setHost]=useState<HTMLElement|null>(null),[active,setActive]=useState(false),[dashboard,setDashboard]=useState<Dashboard|null>(null),[overview,setOverview]=useState<Overview|null>(null),[founder,setFounder]=useState<Founder|null>(null),[loading,setLoading]=useState(false),[name,setName]=useState('');
  const[sessionKey,setSessionKey]=useState(()=>`${session.token()}|${session.workspace()}`);
  useEffect(()=>{const sync=()=>{const selected=document.querySelector<HTMLButtonElement>('.sidebar nav button.active');const text=selected?.textContent||'';const on=text.includes('Central de Comando')||text.includes('Hoje');setActive(Boolean(on));setSessionKey(`${session.token()}|${session.workspace()}`);const content=document.querySelector<HTMLElement>('.content');if(content){let mount=document.getElementById('nexo-home-v2-mount');if(!mount){mount=document.createElement('div');mount.id='nexo-home-v2-mount';content.prepend(mount)}setHost(mount)}document.body.classList.toggle('nexoHomeV2Active',Boolean(on))};sync();const o=new MutationObserver(sync);o.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});const t=window.setInterval(sync,900);return()=>{o.disconnect();clearInterval(t);document.body.classList.remove('nexoHomeV2Active')}},[]);
  useEffect(()=>{if(active&&session.token()&&session.workspace())void load()},[active,sessionKey]);
  async function load(){setLoading(true);try{const[d,o,f,me]=await Promise.all([api<Dashboard>('/v1/dashboard').catch(()=>null),api<Overview>('/v1/command/overview').catch(()=>null),api<Founder>('/v1/intelligence/founder-cockpit').catch(()=>null),api<any>('/v1/auth/me').catch(()=>null)]);setDashboard(d);setOverview(o);setFounder(f);setName(String(me?.user?.name||''))}finally{setLoading(false)}}
  if(!active||!host)return null;
  const area=(id:string)=>overview?.areas?.find(x=>x.id===id);
  const overdue=Number(founder?.money?.overdueCount??dashboard?.finance?.overdue_count??0),approvals=Number(overview?.pendingApprovals||0),tasks=Number(founder?.operations?.overdueTasks||0),docs=Number(area('documents')?.attention||0);const attention=approvals+overdue+tasks+docs;const score=founder?.health?.score;const firstName=capitalizedFirstName(name);
  return createPortal(<section className="homeV3">
    <section className="homeMayaHero"><div className="homeMayaIdentity"><span className="homeMayaAvatar">M</span><div><small>COMANDO DO DIA · MAYA</small>{firstName&&<p className="homeGreeting">Olá, {firstName}.</p>}<h2>{attention?`${attention} item${attention===1?'':'s'} merecem sua atenção hoje.`:'Tudo sob controle por enquanto.'}</h2><p>{founder?.health?.summary||'Eu cruzo clientes, financeiro, documentos e operação para mostrar o que realmente merece sua decisão.'}</p></div></div><div className="homeMayaActions"><button className="primary" onClick={()=>launch(quickActions[11])}>Perguntar à Maya</button><button className="icon" onClick={()=>void load()} disabled={loading} title="Atualizar">{loading?'…':'↻'}</button></div></section>
    <section className="homeDoSection"><header><div><small>FAÇA ACONTECER</small><h3>O que você quer fazer hoje?</h3><p>Escolha uma tarefa. O NexOffice abre o caminho certo e chama o especialista quando fizer sentido.</p></div></header><div className="homeDoGrid">{quickActions.map(action=><button key={action.id} className={action.featured?'featured':''} onClick={()=>launch(action)}><span className="homeDoIcon">{action.icon}</span><div><b>{action.title}</b><small>{action.description}</small></div><em>→</em></button>)}</div></section>
    <section className="homePulse" aria-label="Resumo do negócio"><button onClick={()=>clickNav('Financeiro')}><span>A receber</span><b>{money(dashboard?.finance?.receivable_minor)}</b><small>{overdue?`${overdue} vencida${overdue===1?'':'s'}`:'sem vencidos'}</small></button><button onClick={()=>clickNav('Clientes')}><span>Pipeline</span><b>{money(founder?.sales?.pipelineMinor??dashboard?.crm?.open_pipeline_minor)}</b><small>{founder?.sales?.openDeals??dashboard?.crm?.open_deals??0} oportunidades</small></button><button onClick={()=>clickNav('Operação')}><span>Hoje</span><b>{founder?.operations?.appointmentsToday??dashboard?.appointments?.today_appointments??0}</b><small>compromissos</small></button><button onClick={()=>clickNav('Assistentes IA')}><span>Saúde</span><b>{score==null?'—':score}</b><small>{score==null?'base em formação':'de 100'}</small></button></section>
    <section className="homeTeamSection"><header><div><small>SUA EQUIPE DE IA</small><h3>Seis especialistas para ajudar a executar.</h3><p>Você escolhe o que quer fazer; Maya coordena e cada especialista aprofunda sua área.</p></div><button onClick={()=>clickNav('Assistentes IA')}>Abrir equipe →</button></header><div className="homeTeamGrid">{assistants.map((a,i)=><button key={a.name} className={i===0?'lead':''} onClick={()=>clickNav(a.target)}><div className="agentHead"><span className="agentDot">{a.initial}</span><span><b>{a.name}</b><small>{a.role}</small></span><em>→</em></div><p>{a.power}</p><span className="agentAction">Abrir {a.role}</span></button>)}</div></section>
  </section>,host);
}
