import {useEffect,useState,type FormEvent} from 'react';
import {api,post,put,session} from './api';

type Provider={workspace_id:string;display_name:string;headline?:string;bio?:string;categories:string[];specialties:string[];remote_available:boolean;services:Array<{id:string;title:string;category:string;description:string;pricingModel:string;startingPriceMinor?:number}>;portfolio:Array<{id:string;title:string;summary:string;outcomeSummary?:string}>};
type Me={profile:any;services:any[];portfolio:any[]};
type PaymentProfile={configured:boolean;encryptionConfigured:boolean;pixKeyType?:string;maskedPixKey?:string;beneficiaryName?:string;documentLabel?:string;instructions?:string};
type Receivable={id:string;description:string;amount_minor:number;currency:string;due_at?:string;status:string;contact_name?:string};
type Tab='discover'|'provider'|'pix';
const money=(minor:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);

export default function NetworkCenter(){
 const[sessionKey,setSessionKey]=useState(()=>`${session.token()}|${session.workspace()}`),[open,setOpen]=useState(false),[tab,setTab]=useState<Tab>('discover'),[providers,setProviders]=useState<Provider[]>([]),[me,setMe]=useState<Me|null>(null),[payment,setPayment]=useState<PaymentProfile|null>(null),[receivables,setReceivables]=useState<Receivable[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[need,setNeed]=useState('');
 const authenticated=Boolean(session.token()&&session.workspace());
 useEffect(()=>{const t=setInterval(()=>{const n=`${session.token()}|${session.workspace()}`;setSessionKey(p=>p===n?p:n)},700);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!authenticated){setOpen(false);return}if(open)void load(tab)},[sessionKey,open,tab]);
 async function load(next:Tab){setBusy(true);setNotice('');try{if(next==='discover')setProviders(await api('/v1/network/providers'));if(next==='provider')setMe(await api('/v1/network/provider/me'));if(next==='pix'){const[p,r]=await Promise.all([api<PaymentProfile>('/v1/collections/payment-profile'),api<Receivable[]>('/v1/collections/pix-ready')]);setPayment(p);setReceivables(r)}}catch(e:any){setNotice(e?.message||'Não foi possível carregar esta área.')}finally{setBusy(false)}}
 async function request(provider:Provider,service?:Provider['services'][number]){const summary=need.trim();if(summary.length<10){setNotice('Conte em uma frase o que você precisa antes de solicitar um especialista.');return}setBusy(true);try{await post('/v1/network/requests',{providerWorkspaceId:provider.workspace_id,serviceId:service?.id||null,title:service?`Interesse em ${service.title}`:`Solicitação para ${provider.display_name}`,needSummary:summary});setNeed('');setNotice('Solicitação enviada dentro do NexOffice. Nenhum pagamento foi realizado.')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await put('/v1/network/provider/me',{displayName:String(f.get('displayName')||''),headline:String(f.get('headline')||'')||null,bio:String(f.get('bio')||'')||null,categories:list(f.get('categories')),specialties:list(f.get('specialties')),serviceRegions:list(f.get('regions')),remoteAvailable:f.get('remote')==='on',status:String(f.get('published'))==='on'?'published':'draft'});await load('provider');setNotice('Perfil profissional salvo.')}catch(err:any){setNotice(err.message)}finally{setBusy(false)}}
 async function addService(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await post('/v1/network/provider/services',{title:String(f.get('title')||''),category:String(f.get('category')||''),description:String(f.get('description')||''),pricingModel:String(f.get('pricingModel')||'quote'),startingPriceMinor:f.get('price')?Math.round(Number(f.get('price'))*100):null,capabilities:[]});e.currentTarget.reset();await load('provider');setNotice('Serviço adicionado ao seu perfil.')}catch(err:any){setNotice(err.message)}finally{setBusy(false)}}
 async function savePix(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const p=await put<PaymentProfile>('/v1/collections/payment-profile',{pixKeyType:String(f.get('pixKeyType')),pixKey:String(f.get('pixKey')),beneficiaryName:String(f.get('beneficiaryName')),documentLabel:String(f.get('documentLabel')||'')||null,instructions:String(f.get('instructions')||'')||null});setPayment(p);e.currentTarget.reset();setNotice('Dados Pix protegidos e salvos. O NexOffice não movimenta esse dinheiro.')}catch(err:any){setNotice(err.message)}finally{setBusy(false)}}
 async function copyCharge(id:string){setBusy(true);try{const pack=await post<{copyText:string}>(`/v1/collections/ledger/${id}/pix-package`,{});await navigator.clipboard.writeText(pack.copyText);setNotice('Cobrança Pix copiada. Você decide por onde enviar ao cliente.')}catch(err:any){setNotice(err.message)}finally{setBusy(false)}}
 if(!authenticated)return null;
 return <><button className="networkLauncher" onClick={()=>setOpen(true)}>◎ <span>Rede</span></button>{open&&<div className="networkBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="networkPanel"><header><div><small>NEXOFFICE NETWORK</small><h2>Negócios conectados</h2><p>Encontre especialistas, ofereça seus serviços e cobre com seu próprio Pix.</p></div><button className="networkClose" onClick={()=>setOpen(false)}>×</button></header><nav><button className={tab==='discover'?'active':''} onClick={()=>setTab('discover')}>Especialistas</button><button className={tab==='provider'?'active':''} onClick={()=>setTab('provider')}>Oferecer serviços</button><button className={tab==='pix'?'active':''} onClick={()=>setTab('pix')}>Cobrar via Pix</button></nav>{busy&&<div className="networkBusy"/>}{notice&&<div className="networkNotice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<main>{tab==='discover'?<Discover providers={providers} need={need} setNeed={setNeed} request={request}/>:tab==='provider'?<ProviderArea me={me} saveProfile={saveProfile} addService={addService}/>:<PixArea payment={payment} receivables={receivables} save={savePix} copy={copyCharge}/>}</main><footer><span>DocWallet é o motor de contratos e assinaturas.</span><span>Nexa/BaaS não participa deste fluxo.</span></footer></section></div>}</>;
}

function Discover({providers,need,setNeed,request}:{providers:Provider[];need:string;setNeed:(v:string)=>void;request:(p:Provider,s?:Provider['services'][number])=>void}){return <div className="networkDiscover"><div className="networkIntro"><div><small>PRECISO DE AJUDA</small><h3>Descreva o que seu negócio precisa.</h3><p>A rede mostra somente perfis que foram publicados por outros workspaces NexOffice.</p></div><textarea value={need} onChange={e=>setNeed(e.target.value)} placeholder="Ex.: Quero melhorar minhas campanhas e transformar mais leads em agendamentos."/></div><div className="providerGrid">{providers.length?providers.map(p=><article key={p.workspace_id}><div className="providerHead"><div><b>{p.display_name}</b><small>{p.headline||p.categories?.join(' · ')||'Especialista NexOffice'}</small></div>{p.remote_available&&<i>Remoto</i>}</div>{p.bio&&<p>{p.bio}</p>}<div className="chips">{(p.specialties||[]).slice(0,6).map(x=><span key={x}>{x}</span>)}</div><div className="serviceList">{p.services?.length?p.services.slice(0,5).map(s=><div key={s.id}><div><b>{s.title}</b><small>{s.category}{s.startingPriceMinor!=null?` · a partir de ${money(s.startingPriceMinor)}`:''}</small><p>{s.description}</p></div><button onClick={()=>request(p,s)}>Solicitar</button></div>):<button onClick={()=>request(p)}>Solicitar contato</button>}</div>{p.portfolio?.length>0&&<details><summary>Ver portfólio</summary>{p.portfolio.slice(0,4).map(i=><div className="portfolioItem" key={i.id}><b>{i.title}</b><p>{i.summary}</p>{i.outcomeSummary&&<small>{i.outcomeSummary}</small>}</div>)}</details>}</article>):<div className="networkEmpty"><b>A rede está pronta para receber os primeiros especialistas.</b><p>Publique um perfil na aba “Oferecer serviços”.</p></div>}</div></div>}

function ProviderArea({me,saveProfile,addService}:{me:Me|null;saveProfile:(e:FormEvent<HTMLFormElement>)=>void;addService:(e:FormEvent<HTMLFormElement>)=>void}){const p=me?.profile;return <div className="providerArea"><section><small>SEU PERFIL PROFISSIONAL</small><h3>Use o NexOffice e ofereça sua especialidade para a rede.</h3><form onSubmit={saveProfile} className="networkForm"><label>Nome público<input name="displayName" defaultValue={p?.display_name||''} required/></label><label>Título<input name="headline" defaultValue={p?.headline||''} placeholder="Ex.: Gestor de tráfego para clínicas"/></label><label>Sobre<textarea name="bio" defaultValue={p?.bio||''}/></label><label>Categorias<input name="categories" defaultValue={(p?.categories||[]).join(', ')} placeholder="Marketing, Contabilidade"/></label><label>Especialidades<input name="specialties" defaultValue={(p?.specialties||[]).join(', ')} placeholder="Google Ads, Meta Ads, BPO Fiscal"/></label><label>Regiões<input name="regions" defaultValue={(p?.service_regions||[]).join(', ')} placeholder="Brasil, Santos/SP"/></label><label className="networkCheck"><input type="checkbox" name="remote" defaultChecked={p?.remote_available!==false}/>Atendo remotamente</label><label className="networkCheck"><input type="checkbox" name="published" defaultChecked={p?.status==='published'}/>Publicar meu perfil na Rede</label><button className="networkPrimary">Salvar perfil</button></form></section><section><small>SERVIÇOS</small><h3>O que você entrega</h3><div className="myServices">{me?.services?.map(s=><article key={s.id}><b>{s.title}</b><small>{s.category} · {s.pricing_model}</small><p>{s.description}</p></article>)}</div><form onSubmit={addService} className="networkForm compact"><label>Serviço<input name="title" required/></label><label>Categoria<input name="category" required placeholder="Marketing, Fiscal, Design..."/></label><label>Descrição<textarea name="description" required minLength={10}/></label><label>Modelo<select name="pricingModel"><option value="quote">Sob orçamento</option><option value="fixed">Preço fixo</option><option value="monthly">Mensal</option><option value="hourly">Por hora</option></select></label><label>Preço inicial (R$)<input name="price" type="number" min="0" step="0.01"/></label><button className="networkPrimary">Adicionar serviço</button></form></section></div>}

function PixArea({payment,receivables,save,copy}:{payment:PaymentProfile|null;receivables:Receivable[];save:(e:FormEvent<HTMLFormElement>)=>void;copy:(id:string)=>void}){return <div className="pixArea"><section><small>SEU PIX · SEU DINHEIRO</small><h3>NexOffice prepara a cobrança. O pagamento continua direto para você.</h3><p className="privacyText">A chave é armazenada protegida e não aparece integralmente nas consultas. Não há custódia, conta BaaS ou movimentação financeira pelo NexOffice.</p>{payment?.configured&&<div className="pixSaved"><b>{payment.beneficiaryName}</b><span>{payment.pixKeyType?.toUpperCase()} · {payment.maskedPixKey}</span></div>}{payment&&!payment.encryptionConfigured&&<div className="pixWarning">O ambiente ainda precisa de <code>NEXOFFICE_PAYMENT_DATA_KEY</code> antes de salvar dados Pix.</div>}<form onSubmit={save} className="networkForm"><label>Tipo<select name="pixKeyType"><option value="cnpj">CNPJ</option><option value="cpf">CPF</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Aleatória</option></select></label><label>Chave Pix<input name="pixKey" required autoComplete="off"/></label><label>Favorecido<input name="beneficiaryName" required/></label><label>Identificação opcional<input name="documentLabel" placeholder="Ex.: CNPJ 12.345.678/0001-00"/></label><label>Instruções adicionais<textarea name="instructions" placeholder="Ex.: Envie o comprovante após o pagamento."/></label><button className="networkPrimary">Salvar dados de recebimento</button></form></section><section><small>COBRANÇAS</small><h3>Preparar mensagem para o cliente</h3><div className="receivableList">{receivables.length?receivables.map(r=><article key={r.id}><div><b>{r.contact_name||'Cliente'}</b><small>{r.description} · {money(r.amount_minor)}</small></div><button onClick={()=>copy(r.id)} disabled={!payment?.configured}>Copiar cobrança Pix</button></article>):<p className="networkEmpty">Nenhum recebível em aberto agora.</p>}</div></section></div>}
function list(value:FormDataEntryValue|null){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean)}
