import {useEffect,useState,type FormEvent} from 'react';
import {api,post} from './api';
import './network-work-lineage.css';

type RequestSummary={id:string;status:string;title:string;contact_id?:string|null};
type Step={done:boolean;status?:string|null;signatureStatus?:string|null;count?:number};
type Lineage={requestId:string;requestStatus:string;steps:{request:Step;operation:Step;contract:Step;fiscal:Step;collection:Step;communication:Step;payment:Step;outcome:Step};nextAction:string;delegatedAccess?:{status:string;expiresAt:string;scopeCount:number}|null;privacy:{amountExposed:false;pixSecretExposed:false;documentContentExposed:false;fiscalExternalRefExposed:false;providerWorkspaceMembershipGranted:false};externalEffect:false};

const labels:Record<keyof Lineage['steps'],string>={request:'Trabalho',operation:'Operação',contract:'Contrato',fiscal:'Nota',collection:'Cobrança',communication:'Comunicação',payment:'Recebido',outcome:'Outcome'};
const nextLabels:Record<string,string>={create_operation:'Criar Operação Comercial',formalize_contract:'Formalizar contrato no DocWallet',prepare_or_sync_invoice:'Preparar ou atualizar nota no TaxAgent',prepare_collection:'Preparar cobrança',collect_or_follow_up:'Cobrar ou fazer follow-up',record_outcome:'Registrar outcome',review_work:'Revisar trabalho'};

export default function NetworkWorkLineage({request,requester}:{request:RequestSummary;requester:boolean}){
 const[lineage,setLineage]=useState<Lineage|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState('');
 const canCreate=requester&&['accepted','in_progress','completed'].includes(request.status)&&Boolean(request.contact_id)&&!lineage?.steps.operation.done;
 useEffect(()=>{if(['accepted','in_progress','completed'].includes(request.status))void refresh()},[request.id,request.status]);
 async function refresh(){setLoading(true);try{setLineage(await api<Lineage>(`/v1/network/requests/${request.id}/lineage`));setNotice('')}catch(e:any){setNotice(e?.message||'Não foi possível carregar o andamento operacional.')}finally{setLoading(false)}}
 async function createOperation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),amount=Number(f.get('amount')||0),due=String(f.get('dueAt')||'');if(!Number.isFinite(amount)||amount<0)return;setLoading(true);try{await post(`/v1/network/requests/${request.id}/operation`,{amountMinor:Math.round(amount*100),dueAt:due?new Date(`${due}T12:00:00-03:00`).toISOString():null,title:request.title});await refresh();e.currentTarget.reset();setNotice('Operação Comercial vinculada ao trabalho. Nenhuma ação externa foi executada.')}catch(err:any){setNotice(err?.message||'Não foi possível criar a Operação Comercial.')}finally{setLoading(false)}}
 if(!['accepted','in_progress','completed'].includes(request.status))return null;
 return <section className="networkLineage"><div className="networkLineageHead"><div><small>EXECUÇÃO DO TRABALHO</small><b>Do pedido ao resultado</b></div><button type="button" className="secondary" onClick={()=>void refresh()} disabled={loading}>{loading?'Atualizando…':'Atualizar andamento'}</button></div>{lineage&&<><div className="networkLineageSteps">{(Object.keys(labels) as Array<keyof Lineage['steps']>).map(key=>{const step=lineage.steps[key];return <div className={`networkLineageStep ${step.done?'done':''}`} key={key}><i>{step.done?'✓':'·'}</i><span><b>{labels[key]}</b><small>{step.status||((key==='outcome'&&step.count)?`${step.count} registrado(s)`:step.done?'Concluído':'Pendente')}</small></span></div>})}</div><div className="networkLineageNext"><span>Próximo passo sugerido</span><b>{nextLabels[lineage.nextAction]||lineage.nextAction}</b><small>É apenas orientação. Nenhuma ação externa acontece automaticamente.</small></div>{lineage.delegatedAccess&&<small className="networkLineagePrivacy">Contexto delegado: {lineage.delegatedAccess.status} · {lineage.delegatedAccess.scopeCount} escopo(s). Lineage sem valor, Pix secreto, documento bruto ou referência fiscal externa.</small>}</>}{canCreate&&<form className="networkOperationCreate" onSubmit={createOperation}><div><b>Criar Operação Comercial</b><small>Conecta este trabalho ao fluxo Contrato → Nota → Cobrança → Comunicação → Recebido.</small></div><label>Valor do serviço (R$)<input name="amount" type="number" min="0" step="0.01" required/></label><label>Vencimento<input name="dueAt" type="date"/></label><button disabled={loading}>Criar operação</button><small>Isso só cria o registro operacional no NexOffice. Não emite nota, não gera Pix e não envia mensagem.</small></form>}{requester&&!request.contact_id&&!lineage?.steps.operation.done&&<div className="networkLineageWarning">Vincule um contato ao trabalho para criar a Operação Comercial.</div>}{notice&&<div className="networkLineageNotice">{notice}</div>}</section>;
}
