import {useEffect,useState} from 'react';
import {api,post,session} from './api';

type Status={enabled:boolean;configured:boolean;provider:string;persistence:string;defaultContext:string;externalEffects:boolean};
type Answer={answer:string;riskLevel:'baixo'|'medio'|'alto';escalationRecommended:boolean;escalationReason?:string;missingInformation?:string[];safeNextSteps?:string[];limitations?:string[];sourceMode:string;persistence:string;questionPersisted:boolean;businessContextShared:boolean};

export default function NexJudMini(){
  const[authKey,setAuthKey]=useState(()=>`${session.token()}|${session.workspace()}`),[status,setStatus]=useState<Status|null>(null),[open,setOpen]=useState(false),[question,setQuestion]=useState(''),[mode,setMode]=useState<'question'|'light_analysis'>('question'),[includeContext,setIncludeContext]=useState(false),[answer,setAnswer]=useState<Answer|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const timer=setInterval(()=>{const next=`${session.token()}|${session.workspace()}`;setAuthKey(prev=>prev===next?prev:next)},800);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!session.token()||!session.workspace()){setStatus(null);setOpen(false);return}api<Status>('/v1/legal/mini/status').then(setStatus).catch(()=>setStatus(null))},[authKey]);
  if(!status?.enabled||!status?.configured)return null;
  async function ask(){const text=question.trim();if(text.length<4)return;setBusy(true);setError('');setAnswer(null);try{const result=await post<Answer>('/v1/legal/mini',{question:text,mode,includeBusinessContext:includeContext});setAnswer(result)}catch(e:any){setError(e?.message||'NexJud Mini indisponível.')}finally{setBusy(false)}}
  return <><button className="nexjudMiniLauncher" onClick={()=>setOpen(v=>!v)} aria-label="Abrir NexJud Mini">⚖ <span>NexJud Mini</span></button>{open&&<aside className="nexjudMiniPanel"><header><div><small>NEXJUD · ASSISTENTE JURÍDICO LEVE</small><h3>Uma dúvida rápida?</h3><p>Explicações e análises leves dentro do NexOffice.</p></div><button onClick={()=>setOpen(false)}>×</button></header><div className="nexjudMiniBody"><div className="nexjudMiniModes"><button className={mode==='question'?'active':''} onClick={()=>setMode('question')}>Pergunta</button><button className={mode==='light_analysis'?'active':''} onClick={()=>setMode('light_analysis')}>Análise leve</button></div><textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={6000} placeholder="Ex.: Posso colocar multa por atraso neste tipo de prestação de serviço?"/><label className="nexjudMiniContext"><input type="checkbox" checked={includeContext} onChange={e=>setIncludeContext(e.target.checked)}/>Compartilhar apenas nome/vertical/plano/moeda/fuso da minha empresa</label><button className="nexjudMiniAsk" onClick={ask} disabled={busy||question.trim().length<4}>{busy?'Analisando…':'Perguntar ao NexJud'}</button><p className="nexjudMiniPrivacy">A pergunta não é salva pelo NexOffice. Clientes, contratos, processos e dados financeiros detalhados não são enviados automaticamente.</p>{error&&<div className="nexjudMiniError">{error}</div>}{answer&&<div className="nexjudMiniAnswer"><div className="nexjudMiniRisk"><b>Resposta</b><span className={`risk-${answer.riskLevel}`}>Risco {answer.riskLevel}</span></div><p>{answer.answer}</p>{answer.safeNextSteps?.length? <section><b>Próximos passos seguros</b><ul>{answer.safeNextSteps.map((x,i)=><li key={i}>{x}</li>)}</ul></section>:null}{answer.missingInformation?.length?<section><b>Faltaria confirmar</b><ul>{answer.missingInformation.map((x,i)=><li key={i}>{x}</li>)}</ul></section>:null}{answer.escalationRecommended&&<div className="nexjudMiniEscalate"><b>Vale aprofundar</b><p>{answer.escalationReason||'Este tema merece análise profissional ou uso do NexJud completo antes de uma decisão relevante.'}</p></div>}<small>Sem pesquisa jurídica em tempo real nesta resposta. Confirme normas, prazos e decisões relevantes em fonte oficial/profissional.</small></div>}</div><footer>Informação jurídica geral · não substitui aconselhamento profissional</footer></aside>}</>;
}
