import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {api,session} from './api';
import './office-view.css';

type Dashboard={finance?:{receivable_minor?:number;overdue_count?:number};crm?:{open_deals?:number};tasks?:{due_tasks?:number};appointments?:{today_appointments?:number}};
type Role='secretary'|'crm'|'erp'|'controller'|'documents'|'growth';
type RoomAction={label:string;target:string;role?:Role;prompt?:string};
type Room={id:string;name:string;agent:string;role:string;icon:string;actions:RoomAction[];status:(d:Dashboard|null)=>string};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(minor||0)/100);
const rooms:Room[]=[
 {id:'reception',name:'Recepção',agent:'Sofia',role:'Atendimento & agenda',icon:'☎',actions:[{label:'Criar Bot',target:'Assistentes IA',role:'secretary',prompt:'Quero criar um Bot para minha empresa. Me ajude a definir atendimento, conhecimento, captação de contatos e como colocá-lo no ar.'},{label:'Ver agenda',target:'Operação'},{label:'Organizar atendimento',target:'Assistentes IA',role:'secretary',prompt:'Quero organizar meu atendimento, agenda e encaminhamento de contatos.'}],status:d=>`${d?.appointments?.today_appointments||0} compromisso(s) hoje`},
 {id:'sales',name:'Comercial',agent:'Clara',role:'Clientes & vendas',icon:'◎',actions:[{label:'Bot + CRM',target:'Assistentes IA',role:'crm',prompt:'Quero colocar um Bot + CRM no ar, ligando atendimento, qualificação, cadastro do lead e follow-up.'},{label:'Criar funil',target:'Assistentes IA',role:'crm',prompt:'Quero criar um funil de vendas ligado ao meu site, da captura do lead até proposta e fechamento.'},{label:'Ver oportunidades',target:'Clientes'}],status:d=>`${d?.crm?.open_deals||0} oportunidade(s) aberta(s)`},
 {id:'marketing',name:'Marketing',agent:'Maya',role:'Divulgação & crescimento',icon:'✦',actions:[{label:'Criar campanha',target:'Assistentes IA',role:'growth',prompt:'Quero criar uma campanha publicitária. Estruture objetivo, público, oferta, mensagem, criativos e próximos passos para revisão.'},{label:'Post para Instagram',target:'Assistentes IA',role:'growth',prompt:'Quero criar conteúdo para Instagram. Prepare ideias de posts, legendas, imagens sugeridas e sequência de publicação.'},{label:'Gerar imagem + texto',target:'Assistentes IA',role:'growth',prompt:'Quero criar uma peça para divulgar minha empresa: proponha conceito visual, texto, legenda e chamada para ação.'}],status:()=>`Campanhas, conteúdo e aquisição`},
 {id:'board',name:'Diretoria',agent:'Maya',role:'Entendimento do negócio',icon:'▲',actions:[{label:'Resumo do dia',target:'Hoje'},{label:'Entender meu negócio',target:'Assistentes IA',role:'growth',prompt:'Faça uma leitura do meu negócio agora: o que exige atenção, o que mudou e qual é a melhor próxima ação?'},{label:'Ver prontidão',target:'Integrações'}],status:()=>`Visão geral e prioridades`},
 {id:'finance',name:'Financeiro',agent:'Theo',role:'Cobrar, receber & controlar',icon:'$',actions:[{label:'Criar cobrança',target:'Financeiro'},{label:'Controlar recebimentos',target:'Financeiro'},{label:'Emitir NF',target:'Financeiro'}],status:d=>`${money(d?.finance?.receivable_minor)} a receber`},
 {id:'meeting',name:'Sala de Reuniões',agent:'Maya',role:'Equipe de IA',icon:'◉',actions:[],status:()=>`Reúna especialistas para decidir`},
 {id:'documents',name:'Documentos',agent:'Dora',role:'Contratos & assinaturas',icon:'▱',actions:[{label:'Criar contrato',target:'Documentos'},{label:'Enviar para assinatura',target:'Documentos'},{label:'Ver pendências',target:'Documentos'}],status:()=>`Contratos e documentos`},
 {id:'ops',name:'Operações',agent:'Nico',role:'Dia a dia & execução',icon:'⚙',actions:[{label:'Organizar meu dia',target:'Operação'},{label:'Tarefas',target:'Operação'},{label:'Compromissos',target:'Operação'}],status:d=>`${d?.tasks?.due_tasks||0} tarefa(s) próxima(s)`}
];
const navAliases:Record<string,string[]>={'Hoje':['Hoje','Central de Comando'],'Clientes':['Clientes','CRM'],'Financeiro':['Financeiro'],'Documentos':['Documentos'],'Operação':['Operação','Agenda & Tarefas'],'Crescimento':['Crescimento','Marketing'],'Assistentes IA':['Assistentes IA','Equipe Digital'],'Integrações':['Integrações']};
function nav(match:string){const aliases=navAliases[match]||[match];const bs=[...document.querySelectorAll<HTMLButtonElement>('.sidebar nav button')];bs.find(b=>aliases.some(a=>(b.textContent||'').toLowerCase().includes(a.toLowerCase())))?.click()}
export default function OfficeView(){
 const[topbar,setTopbar]=useState<Element|null>(null),[host,setHost]=useState<HTMLElement|null>(null),[mode,setMode]=useState(()=>localStorage.getItem('nexoffice.viewMode')==='office'),[selected,setSelected]=useState<Room|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null),[meeting,setMeeting]=useState(false),[participants,setParticipants]=useState<string[]>(['Maya']),[agenda,setAgenda]=useState('');
 const authenticated=Boolean(session.token()&&session.workspace());
 useEffect(()=>{const sync=()=>{setTopbar(document.querySelector('.topbar'));const content=document.querySelector<HTMLElement>('.content');if(content){let m=document.getElementById('nexo-office-view-mount');if(!m){m=document.createElement('div');m.id='nexo-office-view-mount';content.prepend(m)}setHost(m)}document.body.classList.toggle('nexoOfficeViewActive',mode&&authenticated)};sync();const o=new MutationObserver(sync);o.observe(document.documentElement,{subtree:true,childList:true});return()=>{o.disconnect();document.body.classList.remove('nexoOfficeViewActive')}},[mode,authenticated]);
 useEffect(()=>{if(mode&&authenticated)void api<Dashboard>('/v1/dashboard').then(setDashboard).catch(()=>setDashboard(null))},[mode,authenticated]);
 useEffect(()=>{if(!mode)return;const leaveOffice=(event:Event)=>{const target=event.target as HTMLElement|null;if(!target?.closest('.sidebar nav button'))return;setMode(false);localStorage.setItem('nexoffice.viewMode','dashboard');setSelected(null);setMeeting(false)};document.addEventListener('click',leaveOffice,true);return()=>document.removeEventListener('click',leaveOffice,true)},[mode]);
 const toggle=(office:boolean)=>{setMode(office);localStorage.setItem('nexoffice.viewMode',office?'office':'dashboard');setSelected(null);setMeeting(false)};
 const openModule=(target:string)=>{setMode(false);localStorage.setItem('nexoffice.viewMode','dashboard');setSelected(null);setMeeting(false);requestAnimationFrame(()=>requestAnimationFrame(()=>nav(target)))};
 const openAction=(action:RoomAction)=>{sessionStorage.removeItem('nexoffice.quickAction');if(action.role&&action.prompt){sessionStorage.setItem('nexoffice.quickAction',JSON.stringify({label:action.label,role:action.role,prompt:action.prompt,createdAt:new Date().toISOString()}))}else if(['criar cobrança','emitir nf'].includes(action.label.toLowerCase())){sessionStorage.setItem('nexoffice.quickAction',JSON.stringify({label:action.label,target:action.target,createdAt:new Date().toISOString()}))}openModule(action.target)};
 const people=useMemo(()=>['Maya','Theo','Dora','Clara','Nico','Sofia'],[]);
 if(!authenticated)return null;
 const switcher=topbar?createPortal(<div className="officeSwitcher" aria-label="Modo de visualização"><button className={!mode?'active':''} onClick={()=>toggle(false)}>Dashboard</button><button className={mode?'active':''} onClick={()=>toggle(true)}>Escritório 2D</button></div>,topbar):null;
 if(!mode||!host)return <>{switcher}</>;
 return <>{switcher}{createPortal(<section className="officeView">
   <header className="officeViewHead"><div><small>MEU ESCRITÓRIO</small><h2>Entre em uma sala e resolva o que precisa.</h2><p>Cada sala representa uma parte da empresa. Clique, escolha a tarefa e o NexOffice abre o caminho certo com o especialista daquela área.</p></div><span className="officeLive">● empresa conectada</span></header>
   <div className="officeFloor"><div className="officeHall"><span>NEXOFFICE</span><small>o trabalho passa por aqui</small></div>{rooms.map(room=><button key={room.id} className={`officeRoom room-${room.id}`} onClick={()=>{setSelected(room);if(room.id==='meeting')setMeeting(true)}}><span className="roomIcon">{room.icon}</span><div><b>{room.name}</b><small>{room.agent} · {room.role}</small></div><em>{room.status(dashboard)}</em><span className="agentSprite" title={room.agent}>{room.agent[0]}</span></button>)}</div>
   {selected&&selected.id!=='meeting'&&<aside className="officeDrawer" aria-label={`Sala ${selected.name}`}><button className="officeDrawerClose" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><span className="officeAgentBig">{selected.agent[0]}</span><small>{selected.name.toUpperCase()}</small><h3>O que você quer fazer?</h3><p>{selected.agent} cuida de {selected.role.toLowerCase()}.</p><strong>{selected.status(dashboard)}</strong><div className="officeActionList">{selected.actions.map((action,i)=><button key={action.label} className={i===0?'primary':''} onClick={()=>openAction(action)}>{action.label}<span>→</span></button>)}</div></aside>}
   {meeting&&<div className="meetingBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setMeeting(false)}}><section className="meetingRoom"><button className="officeDrawerClose" onClick={()=>setMeeting(false)} aria-label="Fechar">×</button><small>SALA DE REUNIÕES</small><h3>Reúna sua equipe para resolver um objetivo.</h3><p>Escolha os especialistas, escreva o que você quer alcançar e leve o contexto para a central dos Assistentes.</p><div className="meetingPeople">{people.map(p=><button key={p} className={participants.includes(p)?'selected':''} onClick={()=>setParticipants(v=>v.includes(p)?(p==='Maya'?v:v.filter(x=>x!==p)):[...v,p])}><span>{p[0]}</span><b>{p}</b></button>)}</div><label>O que você quer resolver?<textarea value={agenda} onChange={e=>setAgenda(e.target.value)} placeholder="Ex.: Quero aumentar vendas sem apertar o caixa."/></label><div className="meetingActions"><button onClick={()=>setMeeting(false)}>Cancelar</button><button className="primary" onClick={()=>{if(agenda.trim())sessionStorage.setItem('nexoffice.quickAction',JSON.stringify({label:'Reunião de negócio',role:'growth',prompt:`Quero discutir este objetivo com minha equipe: ${agenda.trim()}. Considere ${participants.join(', ')} como especialistas envolvidos.`,createdAt:new Date().toISOString()}));openModule('Assistentes IA')}} disabled={!agenda.trim()}>Começar reunião →</button></div></section></div>}
  </section>,host)}</>;
}
