import {useEffect,useState,type FormEvent} from 'react';
import {createPortal} from 'react-dom';
import {api,post} from './api';
import './receiving-account-onboarding.css';

type Account={workspaceId:string;legalName:string;taxIdMasked?:string|null;pixKeyMasked:string;pixKeyType:string;providerStatus:string;payoutPolicy:'manual'|'daily';balanceMinor?:number|null;configured:true};
type State={configured:boolean;account:Account|null;actionsEnabled:boolean;providerConfigured:boolean;sandbox?:boolean;degraded?:boolean;receivingMode:string;externalEffect:false};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);

export default function ReceivingAccountOnboardingBridge(){
  const[target,setTarget]=useState<Element|null>(null),[state,setState]=useState<State|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[test,setTest]=useState<any>(null);
  useEffect(()=>{const inspect=()=>setTarget(document.querySelector('.financePixSlot')||document.querySelector('.setupChecklist'));inspect();const o=new MutationObserver(inspect);o.observe(document.documentElement,{subtree:true,childList:true});return()=>o.disconnect()},[]);
  useEffect(()=>{if(target)void load()},[target]);
  async function load(){try{setState(await api<State>('/v1/collections/receiving-account'))}catch{setState({configured:false,account:null,actionsEnabled:false,providerConfigured:false,receivingMode:'subaccount',externalEffect:false})}}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{const result=await post<any>('/v1/collections/receiving-account/setup',{legalName:String(f.get('legalName')||''),taxId:String(f.get('taxId')||''),pixKeyType:String(f.get('pixKeyType')||'CPF'),pixKey:String(f.get('pixKey')||''),payoutPolicy:String(f.get('payoutPolicy')||'daily'),humanConfirmed:true});setNotice(`Pix ativado para ${result?.account?.pixKeyMasked||'a chave informada'}.`);await load()}catch(err:any){setError(err?.message||'Não foi possível ativar o recebimento Pix.')}finally{setBusy(false)}}
  async function refresh(){setBusy(true);setError('');try{const result=await post<any>('/v1/collections/receiving-account/refresh',{});setState(prev=>prev?{...prev,configured:true,account:result.account}:prev);setNotice(`Saldo atualizado: ${money(result?.account?.balanceMinor||0)}.`)}catch(err:any){setError(err?.message||'Não foi possível atualizar o saldo.')}finally{setBusy(false)}}
  async function testCharge(){if(!window.confirm('Gerar cobrança teste de R$ 1,00?'))return;setBusy(true);setError('');try{const result=await post<any>('/v1/collections/receiving-account/test-charge',{amountMinor:100,humanConfirmed:true});setTest(result);setNotice('Cobrança de R$ 1,00 criada.')}catch(err:any){setError(err?.message||'Não foi possível criar a cobrança teste.')}finally{setBusy(false)}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Pix copia e cola copiado.')}catch{setError('Não foi possível copiar automaticamente.')}}

  if(!target)return null;
  const inFinance=target.classList.contains('financePixSlot');
  const configured=Boolean(state?.configured&&state.account);
  const card=<article className={`setupReceiving ${inFinance?'financeReceivingCard ':''}${configured?'done':''}`}><div className="setupStepIcon">{configured?'✓':'$'}</div><div><h3>Recebimento Pix</h3><p>{configured?`${state?.account?.pixKeyMasked} · repasse ${state?.account?.payoutPolicy==='daily'?'diário':'manual'}`:'Escolha onde sua empresa quer receber.'}</p></div><button onClick={()=>{setOpen(true);setError('');setNotice('')}}>{configured?'Abrir':'Configurar'}</button></article>;
  const modal=open?<div className="receiveOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="receiveModal compact"><button className="receiveClose" onClick={()=>setOpen(false)}>×</button><span className="receiveKicker">RECEBIMENTO PIX</span><h2>{configured?'Seu Pix está configurado.':'Onde você quer receber?'}</h2><p className="receiveIntro">O valor vai para a chave Pix cadastrada. O NexOffice não fica com o dinheiro.</p>{error&&<div className="receiveError">{error}</div>}{notice&&<div className="receiveNotice">{notice}</div>}
  {configured&&state?.account?<div className="receiveCurrent simple"><div><b>{state.account.legalName}</b><span>{state.account.pixKeyType} · {state.account.pixKeyMasked}</span></div><div className="receiveCurrentMeta"><span>Repasse: {state.account.payoutPolicy==='daily'?'diário':'manual'}</span><span>Saldo: {state.account.balanceMinor==null?'—':money(state.account.balanceMinor)}</span></div><div className="receiveActions"><button onClick={()=>void refresh()} disabled={busy}>Atualizar saldo</button><button className="primary" onClick={()=>void testCharge()} disabled={busy||!state.actionsEnabled}>Criar teste R$ 1</button></div></div>:null}
  {!configured&&<form onSubmit={submit}><label>Recebedor<input name="legalName" required autoComplete="organization"/></label><label>CPF ou CNPJ<input name="taxId" required inputMode="numeric"/></label><div className="receiveTwo"><label>Tipo da chave<select name="pixKeyType" defaultValue="CPF"><option value="CPF">CPF</option><option value="CNPJ">CNPJ</option><option value="EMAIL">E-mail</option><option value="PHONE">Telefone</option><option value="EVP">Aleatória</option></select></label><label>Chave Pix<input name="pixKey" required/></label></div><label>Repasse<select name="payoutPolicy" defaultValue="daily"><option value="daily">Diário</option><option value="manual">Manual</option></select></label><label className="receiveConsent"><input type="checkbox" required/><span>Confirmo que a chave pertence ao recebedor.</span></label><button className="primary" disabled={busy||!state?.actionsEnabled}>{busy?'Ativando…':'Ativar recebimento Pix'}</button>{state&&!state.actionsEnabled&&<small className="receiveLocked">Teste financeiro ainda bloqueado neste ambiente.</small>}</form>}
  {test?.charge&&<div className="receiveTest"><div><b>Teste R$ 1,00</b><span>Aguardando pagamento</span></div>{test.charge.brCode&&<button onClick={()=>void copy(test.charge.brCode)}>Copiar Pix</button>}{test.charge.paymentLinkUrl&&<a href={test.charge.paymentLinkUrl} target="_blank" rel="noreferrer">Abrir cobrança ↗</a>}</div>}</section></div>:null;
  return <>{createPortal(card,target)}{modal?createPortal(modal,document.body):null}</>;
}
