import {useEffect,useState,type FormEvent} from 'react';
import {createPortal} from 'react-dom';
import {api,post} from './api';
import './receiving-account-onboarding.css';

type Account={workspaceId:string;legalName:string;taxIdMasked?:string|null;pixKeyMasked:string;pixKeyType:string;providerStatus:string;payoutPolicy:'manual'|'daily';balanceMinor?:number|null;configured:true};
type State={configured:boolean;account:Account|null;actionsEnabled:boolean;providerConfigured:boolean;sandbox?:boolean;degraded?:boolean;syncStatus?:string;receivingMode:string;externalEffect:false};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const configuredCompany=String((import.meta as any).env?.VITE_PIX_COMPANY_NAME||'').trim();
const companyLabel=configuredCompany||'sua empresa';

export default function ReceivingAccountOnboardingBridge(){
  const[target,setTarget]=useState<Element|null>(null),[state,setState]=useState<State|null>(null),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[test,setTest]=useState<any>(null),[changing,setChanging]=useState(false);
  useEffect(()=>{const inspect=()=>setTarget(document.querySelector('.financePixSlot')||document.querySelector('.setupChecklist'));inspect();const o=new MutationObserver(inspect);o.observe(document.documentElement,{subtree:true,childList:true});return()=>o.disconnect()},[]);
  useEffect(()=>{if(target)void load()},[target]);
  async function load(){
    setLoaded(false);
    try{
      const result=await api<State>('/v1/collections/receiving-account');
      setState(result);
      if(result.degraded&&result.account)setError('A conta Pix continua salva, mas o motor financeiro está temporariamente indisponível para sincronização. Não recadastre a chave.');
      else if(result.degraded)setError('Não foi possível confirmar o estado da conta Pix agora. Por segurança, o NexOffice não permitirá recadastro até a leitura ser restabelecida.');
      else setError('');
    }catch(err:any){
      // Falha de leitura nunca significa "conta inexistente". Preservamos o último
      // estado conhecido e bloqueamos setup/recriação até o backend responder.
      setState(prev=>prev?{...prev,degraded:true}:prev);
      setError(err?.message?`Falha ao consultar o recebimento Pix: ${err.message}. Os dados já cadastrados não serão substituídos.`:'Não foi possível confirmar o recebimento Pix agora. Os dados já cadastrados não serão substituídos.');
    }finally{setLoaded(true)}
  }
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{const result=await post<any>('/v1/collections/receiving-account/setup',{legalName:String(f.get('legalName')||''),taxId:String(f.get('taxId')||''),pixKeyType:String(f.get('pixKeyType')||'CPF'),pixKey:String(f.get('pixKey')||''),payoutPolicy:String(f.get('payoutPolicy')||'daily'),humanConfirmed:true});setNotice(`Conta de recebimento de ${companyLabel} conectada em ${result?.account?.pixKeyMasked||'a chave informada'}. As cobranças deste workspace usarão esta conta.`);await load()}catch(err:any){setError(err?.message||`Não foi possível conectar o recebimento Pix de ${companyLabel}.`)}finally{setBusy(false)}}
  async function changeKey(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{const result=await post<any>('/v1/collections/receiving-account/change-key',{legalName:state?.account?.legalName||configuredCompany||companyLabel,taxId:String(f.get('taxId')||''),pixKeyType:String(f.get('pixKeyType')||'CPF'),pixKey:String(f.get('pixKey')||''),payoutPolicy:state?.account?.payoutPolicy||'daily',humanConfirmed:true});setChanging(false);setNotice(result?.changed?`Chave Pix de ${companyLabel} atualizada com segurança para ${result?.account?.pixKeyMasked||'a nova chave'}.`:'A chave informada já é a chave ativa.');await load()}catch(err:any){setError(err?.message||'Não foi possível trocar a chave Pix.')}finally{setBusy(false)}}
  async function refresh(){setBusy(true);setError('');try{const result=await post<any>('/v1/collections/receiving-account/refresh',{});setState(prev=>prev?{...prev,configured:true,account:result.account,degraded:false,syncStatus:'synced'}:{configured:true,account:result.account,actionsEnabled:true,providerConfigured:true,degraded:false,syncStatus:'synced',receivingMode:'subaccount',externalEffect:false});setNotice(`Saldo atualizado: ${money(result?.account?.balanceMinor||0)}.`)}catch(err:any){setError(err?.message||'Não foi possível atualizar o saldo. A configuração salva foi preservada.')}finally{setBusy(false)}}
  async function testCharge(){if(!window.confirm(`Gerar cobrança teste de R$ 1,00 para validar a conta de recebimento de ${companyLabel}?`))return;setBusy(true);setError('');try{const result=await post<any>('/v1/collections/receiving-account/test-charge',{amountMinor:100,humanConfirmed:true});setTest(result);setNotice(`Cobrança teste criada. Quando for paga, o valor deve entrar na conta de recebimento de ${companyLabel}.`)}catch(err:any){setError(err?.message||'Não foi possível criar a cobrança teste.')}finally{setBusy(false)}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Pix copia e cola copiado.')}catch{setError('Não foi possível copiar automaticamente.')}}

  if(!target)return null;
  const inFinance=target.classList.contains('financePixSlot');
  const known=Boolean(state);
  const configured=Boolean(state?.configured&&state.account);
  const disabledReason=state?.degraded?'Sincronização financeira indisponível; os dados salvos foram preservados.':state&&!state.providerConfigured?'Motor financeiro ainda não configurado neste ambiente.':state&&!state.actionsEnabled?'Ações financeiras ainda estão desativadas neste ambiente.':'';
  const card=<article className={`setupReceiving ${inFinance?'financeReceivingCard ':''}${configured?'done':''}`}><div className="setupStepIcon">{configured?'✓':'$'}</div><div><h3>Pix da {configuredCompany||'empresa'}</h3><p>{configured?`${state?.account?.pixKeyType} ${state?.account?.pixKeyMasked} · conta ativa · repasse ${state?.account?.payoutPolicy==='daily'?'diário':'manual'}`:known?'Nenhuma conta de recebimento Pix foi encontrada para este workspace.':'Verificando a conta Pix salva deste workspace…'}</p></div>{known?<button onClick={()=>{setOpen(true);setNotice('');setChanging(false)}}>{configured?'Abrir':'Configurar'}</button>:<button onClick={()=>void load()} disabled={!loaded}>Verificar</button>}</article>;
  const modal=open?<div className="receiveOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="receiveModal compact"><button className="receiveClose" onClick={()=>setOpen(false)}>×</button><span className="receiveKicker">CONTA DE RECEBIMENTO PIX</span><h2>{configured?`Pix da ${companyLabel}`:`Configure o Pix de ${companyLabel}`}</h2><p className="receiveIntro">Esta é a conta que recebe as cobranças dos clientes de <strong>{companyLabel}</strong>. Dados já confirmados ficam vinculados ao workspace e nunca são tratados como apagados apenas porque uma consulta temporária falhou.</p>{error&&<div className="receiveError">{error}</div>}{notice&&<div className="receiveNotice">{notice}</div>}
  {configured&&state?.account&&!changing?<div className="receiveCurrent simple"><div><b>{state.account.legalName}</b><span>{state.account.pixKeyType} · {state.account.pixKeyMasked}{state.account.taxIdMasked?` · titular ${state.account.taxIdMasked}`:''}</span></div><div className="receiveCurrentMeta"><span>Status: {state.account.providerStatus||'ACTIVE'}</span><span>Repasse: {state.account.payoutPolicy==='daily'?'diário':'manual'}</span><span>Saldo: {state.account.balanceMinor==null?'—':money(state.account.balanceMinor)}</span></div>{state?.degraded&&<div className="receiveChangeWarning"><b>Dados preservados</b><span>A sincronização está degradada. Não é necessário informar novamente CPF/CNPJ ou chave Pix.</span></div>}<div className="receiveActions"><button onClick={()=>void refresh()} disabled={busy}>Atualizar saldo</button><button onClick={()=>{setError('');setNotice('');setChanging(true)}} disabled={busy||state.degraded}>Trocar chave Pix</button><button className="primary" onClick={()=>void testCharge()} disabled={busy||!state.actionsEnabled||state.degraded}>Validar com teste R$ 1</button></div></div>:null}
  {configured&&state?.account&&changing?<form onSubmit={changeKey}><div className="receiveChangeWarning"><b>Trocar chave Pix</b><span>Por segurança, a troca só será concluída se a conta atual estiver com saldo zero.</span></div><label>CPF ou CNPJ do titular da nova chave<input name="taxId" required inputMode="numeric" placeholder="Somente números"/></label><div className="receiveTwo"><label>Tipo da nova chave<select name="pixKeyType" defaultValue={state.account.pixKeyType||'CPF'}><option value="CPF">CPF</option><option value="CNPJ">CNPJ</option><option value="EMAIL">E-mail</option><option value="PHONE">Telefone</option><option value="EVP">Aleatória</option></select></label><label>Nova chave Pix<input name="pixKey" required placeholder="Nova chave de recebimento"/></label></div><label className="receiveConsent"><input type="checkbox" required/><span>Confirmo que a nova chave pertence a {companyLabel} ou ao titular responsável.</span></label><div className="receiveActions"><button type="button" onClick={()=>setChanging(false)} disabled={busy}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Validando…':'Trocar chave Pix'}</button></div></form>:null}
  {known&&!configured&&!state?.degraded&&<form onSubmit={submit}><div className="receiveChangeWarning"><b>Nenhuma conta vinculada foi encontrada</b><span>Só prossiga se este workspace realmente nunca teve uma conta de recebimento. Se você já cadastrou uma chave, use “Verificar” antes de criar ou reconectar.</span></div><label>Empresa deste workspace<input name="legalName" required autoComplete="organization" defaultValue={configuredCompany} placeholder="Nome da empresa" readOnly={Boolean(configuredCompany)}/></label><label>CPF ou CNPJ do titular da chave<input name="taxId" required inputMode="numeric" placeholder="Somente números"/></label><div className="receiveTwo"><label>Tipo da chave<select name="pixKeyType" defaultValue="CPF"><option value="CPF">CPF</option><option value="CNPJ">CNPJ</option><option value="EMAIL">E-mail</option><option value="PHONE">Telefone</option><option value="EVP">Aleatória</option></select></label><label>Chave Pix de {companyLabel}<input name="pixKey" required placeholder="Chave que receberá os repasses"/></label></div><label>Repasse<select name="payoutPolicy" defaultValue="daily"><option value="daily">Diário</option><option value="manual">Manual</option></select></label><label className="receiveConsent"><input type="checkbox" required/><span>Confirmo que esta chave Pix pertence a {companyLabel} ou ao titular responsável pela empresa.</span></label><button className="primary" disabled={busy||!state?.actionsEnabled}>{busy?'Conectando conta…':`Criar conta de ${companyLabel}`}</button>{disabledReason&&<small className="receiveLocked">{disabledReason}</small>}</form>}
  {!known&&<div className="receiveChangeWarning"><b>Não foi possível confirmar o estado da conta</b><span>Por segurança, o NexOffice não mostra um formulário vazio nem permite recriar a subconta enquanto a leitura não for confirmada.</span><button type="button" onClick={()=>void load()}>Tentar novamente</button></div>}
  {test?.charge&&<div className="receiveTest"><div><b>Teste R$ 1,00</b><span>Aguardando pagamento · destino: {companyLabel}</span></div>{test.charge.brCode&&<button onClick={()=>void copy(test.charge.brCode)}>Copiar Pix</button>}{test.charge.paymentLinkUrl&&<a href={test.charge.paymentLinkUrl} target="_blank" rel="noreferrer">Abrir cobrança ↗</a>}</div>}</section></div>:null;
  return <>{createPortal(card,target)}{modal?createPortal(modal,document.body):null}</>;
}
