import {useEffect,useState,type FormEvent} from 'react';
import {createPortal} from 'react-dom';
import {api,post} from './api';
import './receiving-account-onboarding.css';

type Account={workspaceId:string;legalName:string;taxIdMasked?:string|null;pixKeyMasked:string;pixKeyType:string;providerStatus:string;payoutPolicy:'manual'|'daily';balanceMinor?:number|null;configured:true};
type State={configured:boolean;account:Account|null;actionsEnabled:boolean;providerConfigured:boolean;sandbox?:boolean;degraded?:boolean;receivingMode:string;externalEffect:false};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const configuredCompany=String((import.meta as any).env?.VITE_PIX_COMPANY_NAME||'').trim();
const companyLabel=configuredCompany||'sua empresa';

export default function ReceivingAccountOnboardingBridge(){
  const[target,setTarget]=useState<Element|null>(null),[state,setState]=useState<State|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[test,setTest]=useState<any>(null);
  useEffect(()=>{const inspect=()=>setTarget(document.querySelector('.financePixSlot')||document.querySelector('.setupChecklist'));inspect();const o=new MutationObserver(inspect);o.observe(document.documentElement,{subtree:true,childList:true});return()=>o.disconnect()},[]);
  useEffect(()=>{if(target)void load()},[target]);
  async function load(){try{const result=await api<State>('/v1/collections/receiving-account');setState(result);if(result.degraded)setError('Não foi possível conectar ao motor financeiro de homologação. Recarregue a tela e tente novamente.')}catch(err:any){setState({configured:false,account:null,actionsEnabled:false,providerConfigured:false,degraded:true,receivingMode:'subaccount',externalEffect:false});setError(err?.message?`Falha ao consultar o recebimento Pix: ${err.message}`:'Não foi possível conectar ao financeiro de homologação.')}}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{const result=await post<any>('/v1/collections/receiving-account/setup',{legalName:String(f.get('legalName')||''),taxId:String(f.get('taxId')||''),pixKeyType:String(f.get('pixKeyType')||'CPF'),pixKey:String(f.get('pixKey')||''),payoutPolicy:String(f.get('payoutPolicy')||'daily'),humanConfirmed:true});setNotice(`Conta de recebimento de ${companyLabel} ativada em ${result?.account?.pixKeyMasked||'a chave informada'}. As cobranças deste workspace usarão esta conta.`);await load()}catch(err:any){setError(err?.message||`Não foi possível ativar o recebimento Pix de ${companyLabel}.`)}finally{setBusy(false)}}
  async function refresh(){setBusy(true);setError('');try{const result=await post<any>('/v1/collections/receiving-account/refresh',{});setState(prev=>prev?{...prev,configured:true,account:result.account}:prev);setNotice(`Saldo atualizado: ${money(result?.account?.balanceMinor||0)}.`)}catch(err:any){setError(err?.message||'Não foi possível atualizar o saldo.')}finally{setBusy(false)}}
  async function testCharge(){if(!window.confirm(`Gerar cobrança teste de R$ 1,00 para validar a conta de recebimento de ${companyLabel}?`))return;setBusy(true);setError('');try{const result=await post<any>('/v1/collections/receiving-account/test-charge',{amountMinor:100,humanConfirmed:true});setTest(result);setNotice(`Cobrança teste criada. Quando for paga, o valor deve entrar na conta de recebimento de ${companyLabel}.`)}catch(err:any){setError(err?.message||'Não foi possível criar a cobrança teste.')}finally{setBusy(false)}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Pix copia e cola copiado.')}catch{setError('Não foi possível copiar automaticamente.')}}

  if(!target)return null;
  const inFinance=target.classList.contains('financePixSlot');
  const configured=Boolean(state?.configured&&state.account);
  const disabledReason=state?.degraded?'Conexão com o financeiro de homologação indisponível.':state&&!state.providerConfigured?'Motor financeiro ainda não configurado neste ambiente.':state&&!state.actionsEnabled?'Ações financeiras ainda estão desativadas neste ambiente.':'';
  const card=<article className={`setupReceiving ${inFinance?'financeReceivingCard ':''}${configured?'done':''}`}><div className="setupStepIcon">{configured?'✓':'$'}</div><div><h3>Pix da {configuredCompany||'empresa'}</h3><p>{configured?`${state?.account?.pixKeyMasked} · conta de recebimento ativa · repasse ${state?.account?.payoutPolicy==='daily'?'diário':'manual'}`:`Cadastre a chave Pix de ${companyLabel}. Ela será o destino das cobranças pagas pelos clientes.`}</p></div><button onClick={()=>{setOpen(true);setNotice('')}}>{configured?'Abrir':'Configurar'}</button></article>;
  const modal=open?<div className="receiveOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="receiveModal compact"><button className="receiveClose" onClick={()=>setOpen(false)}>×</button><span className="receiveKicker">CONTA DE RECEBIMENTO PIX</span><h2>{configured?`Conta de recebimento de ${companyLabel} ativa`:`Configure o Pix de ${companyLabel}`}</h2><p className="receiveIntro">Esta etapa configura somente onde <strong>{companyLabel}</strong> recebe. Seus clientes não cadastram chave Pix aqui. Depois, ao criar uma cobrança para qualquer cliente, o pagamento será direcionado para a conta de recebimento vinculada a este workspace.</p>{error&&<div className="receiveError">{error}</div>}{notice&&<div className="receiveNotice">{notice}</div>}
  {configured&&state?.account?<div className="receiveCurrent simple"><div><b>{state.account.legalName}</b><span>{state.account.pixKeyType} · {state.account.pixKeyMasked}</span></div><div className="receiveCurrentMeta"><span>Conta: {companyLabel}</span><span>Repasse: {state.account.payoutPolicy==='daily'?'diário':'manual'}</span><span>Saldo: {state.account.balanceMinor==null?'—':money(state.account.balanceMinor)}</span></div><div className="receiveActions"><button onClick={()=>void refresh()} disabled={busy}>Atualizar saldo</button><button className="primary" onClick={()=>void testCharge()} disabled={busy||!state.actionsEnabled}>Validar com teste R$ 1</button></div></div>:null}
  {!configured&&<form onSubmit={submit}><label>Empresa deste workspace<input name="legalName" required autoComplete="organization" defaultValue={configuredCompany} placeholder="Nome da empresa" readOnly={Boolean(configuredCompany)}/></label><label>CPF ou CNPJ do titular da chave<input name="taxId" required inputMode="numeric" placeholder="Somente números"/></label><div className="receiveTwo"><label>Tipo da chave<select name="pixKeyType" defaultValue="CPF"><option value="CPF">CPF</option><option value="CNPJ">CNPJ</option><option value="EMAIL">E-mail</option><option value="PHONE">Telefone</option><option value="EVP">Aleatória</option></select></label><label>Chave Pix de {companyLabel}<input name="pixKey" required placeholder="Chave que receberá os repasses"/></label></div><label>Repasse<select name="payoutPolicy" defaultValue="daily"><option value="daily">Diário</option><option value="manual">Manual</option></select></label><label className="receiveConsent"><input type="checkbox" required/><span>Confirmo que esta chave Pix pertence a {companyLabel} ou ao titular responsável pela empresa.</span></label><button className="primary" disabled={busy||!state?.actionsEnabled}>{busy?'Criando conta…':`Criar conta de recebimento de ${companyLabel}`}</button>{disabledReason&&<small className="receiveLocked">{disabledReason}</small>}</form>}
  {test?.charge&&<div className="receiveTest"><div><b>Teste R$ 1,00</b><span>Aguardando pagamento · destino: {companyLabel}</span></div>{test.charge.brCode&&<button onClick={()=>void copy(test.charge.brCode)}>Copiar Pix</button>}{test.charge.paymentLinkUrl&&<a href={test.charge.paymentLinkUrl} target="_blank" rel="noreferrer">Abrir cobrança ↗</a>}</div>}</section></div>:null;
  return <>{createPortal(card,target)}{modal?createPortal(modal,document.body):null}</>;
}
