import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {api,post,session} from './api';
import './revenue-center.css';

type Contact={id:string;name:string;phone?:string|null;company_name?:string|null};
type Deal={id:string;contact_id?:string|null;contact_name?:string|null;title:string;stage:string;value_minor:number|string;next_action?:string|null};
type SmartBotsStatus={status:string;provisioned?:boolean;subscriberEligible?:boolean;whatsapp?:{connected:boolean;phone?:string|null;autoReply?:boolean;messageWebhookActive?:boolean}};
type MarketingStatus={configured:boolean;provider:string};
type CommandAction={id:string;title:string;summary:string;status:string;autonomy:string;primary_action?:{type?:string}|null};
type MoneyNow={kind:string;priority:string;title:string;potentialMinor?:number|null;action:string;reason:string};
type RevenueOverview={metrics:{openOpportunities:number;openPipelineMinor:number;modoOpportunities:number;modoCustomers:number;modoWonValueMinor:number;stalledOpportunities:number;stalledValueMinor:number;noNextAction:number;followupsPrepared:number;followupsPending:number;followupsApprovedOrExecuted:number;followupsDone:number};smartbots:{liveSendEnabled:boolean;isolatedGateEnabled:boolean;globalExternalActionsEnabled:boolean;humanApprovalRequired:boolean};moneyNow:MoneyNow[];attribution:{projects:Array<{projectId:string;opportunities:number;progressed:number;customers:number;wonValueMinor:number}>}};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const phone=(value?:string|null)=>String(value||'').replace(/\D/g,'');

export default function RevenueCenter(){
  const [active,setActive]=useState(false),[open,setOpen]=useState(true),[smartbots,setSmartbots]=useState<SmartBotsStatus|null>(null),[marketing,setMarketing]=useState<MarketingStatus|null>(null),[overview,setOverview]=useState<RevenueOverview|null>(null),[contacts,setContacts]=useState<Contact[]>([]),[deals,setDeals]=useState<Deal[]>([]),[actions,setActions]=useState<CommandAction[]>([]),[selectedContact,setSelectedContact]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const authenticated=Boolean(session.token()&&session.workspace());

  useEffect(()=>{const timer=setInterval(()=>{const selected=document.querySelector<HTMLButtonElement>('.sidebar nav button.active');setActive(Boolean(selected?.textContent?.includes('Marketing')))},400);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(authenticated&&active)void load()},[active,authenticated,session.workspace()]);

  async function load(){setError('');try{const [sb,mkt,rev,crmContacts,crmDeals,commandActions]=await Promise.all([api<SmartBotsStatus>('/v1/integrations/smartbots'),api<MarketingStatus>('/v1/marketing/status'),api<RevenueOverview>('/v1/revenue/overview'),api<Contact[]>('/v1/crm/contacts'),api<Deal[]>('/v1/crm/deals'),api<CommandAction[]>('/v1/command/actions')]);setSmartbots(sb);setMarketing(mkt);setOverview(rev);setContacts(crmContacts);setDeals(crmDeals);setActions(commandActions);if(!selectedContact){const first=crmContacts.find(item=>phone(item.phone));if(first)setSelectedContact(first.id)}}catch(e:any){setError(e?.message||'Não foi possível carregar o Revenue Loop.')}}
  const openDeals=useMemo(()=>deals.filter(item=>!['won','lost'].includes(item.stage)),[deals]);
  const pipeline=useMemo(()=>openDeals.reduce((sum,item)=>sum+Number(item.value_minor||0),0),[openDeals]);
  const whatsappContacts=useMemo(()=>contacts.filter(item=>phone(item.phone)),[contacts]);
  const smartActions=useMemo(()=>actions.filter(item=>String(item.primary_action?.type||'').startsWith('message.send')).slice(0,5),[actions]);
  const selected=contacts.find(item=>item.id===selectedContact)||null;
  const modoReady=Boolean(marketing?.configured),smartReady=Boolean(smartbots?.whatsapp?.connected),liveSend=Boolean(overview?.smartbots?.liveSendEnabled);
  const moneyNow:MoneyNow[]=overview?.moneyNow??[];

  async function activateSmartBots(){setBusy('activate');setNotice('');setError('');const popup=window.open('about:blank','_blank');if(popup)popup.opener=null;try{const result=await post<any>(`/v1/integrations/smartbots/${smartbots?.provisioned?'handoff':'activate'}`,{});if(result?.handoffUrl){if(popup)popup.location.href=result.handoffUrl;else window.location.href=result.handoffUrl}else if(popup)popup.close();setNotice('SmartBots preparado. Depois do onboarding, a rotina diária continua pelo NexOffice.');await load()}catch(e:any){if(popup)popup.close();setError(e?.message||'Não foi possível ativar o SmartBots.')}finally{setBusy('')}}
  async function prepareFollowup(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||!phone(selected.phone)||!message.trim())return;setBusy('followup');setNotice('');setError('');try{await post('/v1/revenue/followups',{contactId:selected.id,message:message.trim(),channel:'whatsapp'});setNotice('Follow-up preparado e enviado para aprovação na Central de Comando.');setMessage('');await load()}catch(e:any){setError(e?.message||'Não foi possível preparar o follow-up.')}finally{setBusy('')}}
  function prefill(contact:Contact){setSelectedContact(contact.id);setMessage(`Olá, ${contact.name}. Passando para dar continuidade ao nosso contato. Posso te ajudar a avançar no próximo passo?`)}

  if(!authenticated||!active)return null;
  return <aside className={`revenueDock ${open?'open':'closed'}`} aria-label="Revenue Loop NexOffice">
    <button className="revenueDockToggle" onClick={()=>setOpen(v=>!v)}>{open?'×':'$'}</button>
    {open&&<div className="revenueDockBody">
      <header><div><p>NEXOFFICE · REVENUE LOOP</p><h3>MODO + SmartBots</h3><small>Demanda → conversa → CRM → receita</small></div><button onClick={()=>void load()}>↻</button></header>
      <div className="revenueMiniLoop"><span className={modoReady?'ready':''}>MODO <b>{modoReady?'✓':'—'}</b></span><span>CRM <b>{overview?.metrics.openOpportunities??openDeals.length}</b></span><span className={smartReady?'ready':''}>SmartBots <b>{smartReady?'✓':'—'}</b></span><span>Pipeline <b>{money(overview?.metrics.openPipelineMinor??pipeline)}</b></span></div>
      {overview&&<div className="revenueMiniLoop"><span>Leads MODO <b>{overview.metrics.modoOpportunities}</b></span><span>Clientes ganhos <b>{overview.metrics.modoCustomers}</b></span><span>Receita atribuída <b>{money(overview.metrics.modoWonValueMinor)}</b></span><span className={liveSend?'ready':''}>Envio SmartBots <b>{liveSend?'LIVE':'OFF'}</b></span></div>}
      {error&&<div className="revenueError">{error}</div>}{notice&&<div className="revenueNotice">{notice}</div>}
      {moneyNow.length>0&&<section className="revenueBlock"><div className="revenueBlockHead"><div><small>DINHEIRO AGORA</small><b>Onde o NexOffice vê receita potencial</b></div><span>{moneyNow.length}</span></div><div className="revenueDealList">{moneyNow.map(item=><article key={item.kind}><div><b>{item.title}</b><small>{item.reason}</small></div>{item.potentialMinor!=null&&<strong>{money(item.potentialMinor)}</strong>}</article>)}</div></section>}
      <section className="revenueBlock"><div className="revenueBlockHead"><div><small>SMARTBOTS NATIVO</small><b>Atendimento & follow-up</b></div><span className={smartReady?'ready':''}>{smartReady?'WhatsApp ativo':smartbots?.provisioned?'ativando':'disponível'}</span></div><p>{smartReady?`${smartbots?.whatsapp?.phone||'Canal conectado'} · ${smartbots?.whatsapp?.autoReply?'autoatendimento ativo':'respostas protegidas'}`:'Ative uma vez; depois a operação diária acontece aqui.'}</p>{overview&&<p><b>{liveSend?'Envio aprovado pode sair pelo SmartBots.':'Envio real continua desligado.'}</b> {overview.smartbots.isolatedGateEnabled?'Gate exclusivo SmartBots ativo; demais engines seguem bloqueados.':'Gate exclusivo SmartBots permanece desligado.'}</p>}{!smartReady&&<button className="primary" onClick={()=>void activateSmartBots()} disabled={!smartbots?.subscriberEligible||busy==='activate'}>{busy==='activate'?'Preparando…':smartbots?.provisioned?'Concluir SmartBots':'Ativar SmartBots'}</button>}</section>
      <section className="revenueBlock"><div className="revenueBlockHead"><div><small>OPORTUNIDADES</small><b>Onde agir agora</b></div><span>{money(overview?.metrics.stalledValueMinor??pipeline)}</span></div><div className="revenueDealList">{openDeals.slice(0,4).map(deal=>{const contact=contacts.find(item=>item.id===deal.contact_id);return <article key={deal.id}><div><b>{deal.title}</b><small>{deal.contact_name||contact?.name||'Sem contato'} · {deal.next_action||deal.stage}</small></div>{contact&&phone(contact.phone)&&<button onClick={()=>prefill(contact)}>Follow-up</button>}</article>})}{!openDeals.length&&<small>Nenhuma oportunidade aberta.</small>}</div></section>
      <form className="revenueBlock revenueFollowup" onSubmit={prepareFollowup}><div className="revenueBlockHead"><div><small>SMART FOLLOW-UP</small><b>Preparar WhatsApp</b></div><span>approval-first</span></div><select value={selectedContact} onChange={e=>setSelectedContact(e.target.value)}><option value="">Contato do CRM</option>{whatsappContacts.map(item=><option key={item.id} value={item.id}>{item.name}{item.company_name?` · ${item.company_name}`:''}</option>)}</select><textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Mensagem de follow-up..."/><button className="primary" disabled={!selected||!message.trim()||busy==='followup'}>{busy==='followup'?'Preparando…':'Enviar para aprovação'}</button><small>Aprovação humana é obrigatória. O gate exclusivo do SmartBots pode ser liberado sem abrir campanhas, Pix, fiscal ou outros engines.</small></form>
      {smartActions.length>0&&<section className="revenueBlock"><div className="revenueBlockHead"><div><small>FILA</small><b>Comunicações preparadas</b></div><span>{smartActions.length}</span></div>{smartActions.map(action=><div className="revenueAction" key={action.id}><span>{action.title}</span><small>{action.autonomy==='approval_required'?'aguardando aprovação':action.status}</small></div>)}</section>}
    </div>}
  </aside>;
}