import {useEffect,useState,type FormEvent} from 'react';
import {api,post,session} from './api';

type Account={id:string;name:string;kind:string};
type Preview={format:'csv'|'ofx';count:number;headers:string[];sample:Array<{occurredAt:string;direction:'income'|'expense';amountMinor:number;description:string;counterparty?:string}>;warnings:string[]};
const money=(minor:any=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(minor||0)/100);
const date=(v:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(v));

export default function StatementImportCenter(){
  const [sessionKey,setSessionKey]=useState(()=>`${session.token()}|${session.workspace()}`);const authenticated=Boolean(session.token()&&session.workspace());
  const [open,setOpen]=useState(false);const [accounts,setAccounts]=useState<Account[]>([]);const [accountId,setAccountId]=useState('');const [file,setFile]=useState<File|null>(null);const [content,setContent]=useState('');const [preview,setPreview]=useState<Preview|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  useEffect(()=>{const timer=setInterval(()=>{const next=`${session.token()}|${session.workspace()}`;setSessionKey(prev=>prev===next?prev:next)},700);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!authenticated){setOpen(false);return}if(open)loadAccounts()},[sessionKey,open]);
  async function loadAccounts(){try{const list=await api<Account[]>('/v1/finance/accounts');setAccounts(list);if(!accountId&&list[0])setAccountId(list[0].id)}catch(e:any){setError(e.message)}}
  async function choose(next:File|null){setFile(next);setPreview(null);setMessage('');setError('');if(!next)return;if(next.size>2_000_000){setError('O arquivo deve ter até 2 MB.');return}const text=await next.text();setContent(text);setBusy(true);try{setPreview(await post<Preview>('/v1/reconciliation/import-file/preview',{filename:next.name,content:text}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function submit(e:FormEvent){e.preventDefault();if(!file||!content||!accountId)return;setBusy(true);setError('');setMessage('');try{const r=await post<any>('/v1/reconciliation/import-file',{accountId,filename:file.name,content});setMessage(`${r.inserted} movimentações importadas${r.duplicates?` · ${r.duplicates} duplicadas ignoradas`:''}. O arquivo bruto não foi armazenado.`);setPreview(null);setFile(null);setContent('');const input=document.getElementById('statement-file') as HTMLInputElement|null;if(input)input.value=''}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function autoMatch(){setBusy(true);setError('');try{const r=await post<any>('/v1/reconciliation/auto-match',{max:500,minConfidence:.9});setMessage(`Conciliação analisada: ${r.matched} movimentações conciliadas automaticamente${r.suggested?` · ${r.suggested} precisam de revisão`:''}.`)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  if(!authenticated)return null;
  return <><button className="statementLauncher" onClick={()=>setOpen(true)}>⇅ <span>Extrato</span></button>{open&&<div className="statementBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="statementPanel"><header><div><small>FINANCEIRO · CONCILIAÇÃO</small><h2>Importar extrato</h2><p>Envie CSV ou OFX. O NexOffice lê as movimentações, evita duplicidades e prepara a conciliação com seu financeiro.</p></div><button onClick={()=>setOpen(false)}>×</button></header>{busy&&<div className="statementBusy"/>}{error&&<div className="statementError">{error}</div>}{message&&<div className="statementSuccess">{message}</div>}<form onSubmit={submit}><label>Conta financeira<select value={accountId} onChange={e=>setAccountId(e.target.value)} required><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="dropFile"><b>{file?.name||'Escolha um arquivo CSV ou OFX'}</b><span>{file?'Arquivo lido localmente e pronto para conferência.':'Até 2 MB · o arquivo bruto não será guardado pelo NexOffice.'}</span><input id="statement-file" type="file" accept=".csv,.ofx,text/csv,application/x-ofx" onChange={e=>choose(e.target.files?.[0]||null)}/></label>{preview&&<div className="statementPreview"><div className="previewHead"><div><small>FORMATO</small><b>{preview.format.toUpperCase()}</b></div><div><small>MOVIMENTAÇÕES</small><b>{preview.count}</b></div></div><div className="previewRows">{preview.sample.map((x,i)=><div key={i}><span><b>{x.description}</b><small>{date(x.occurredAt)}{x.counterparty?` · ${x.counterparty}`:''}</small></span><strong className={x.direction==='income'?'positive':'negative'}>{x.direction==='income'?'+':'−'} {money(x.amountMinor)}</strong></div>)}</div>{preview.warnings?.length>0&&<small className="previewWarning">{preview.warnings.slice(0,3).join(' ')}</small>}<button className="statementPrimary" disabled={!accountId||busy}>Importar movimentações</button></div>}</form><div className="reconcileBox"><div><b>Já importou?</b><p>Rode a conciliação automática. O NexOffice compara valor, data e contraparte com os lançamentos existentes.</p></div><button onClick={autoMatch} disabled={busy}>Conciliar agora</button></div><footer><b>Isso não conecta seu banco.</b> É apenas importação de arquivo. Bank Connect/Open Finance continua reservado para a futura parceria bancária.</footer></section></div>}</>;
}
