import {query} from './db.js';
import {getBusinessProfile} from './business-intelligence.js';

export type SectorObservation={code:string;dimension:'finance'|'sales'|'customers'|'operation'|'resilience';currentValue:number;previousValue:number|null;deltaPct:number|null;triggered:boolean;evidence:Record<string,unknown>};
type SectorSignal=SectorObservation&{severity:'attention'|'critical';title:string;whatChanged:string;whyItMatters:string;recommendation:string;horizonDays:number;confidence:number;ontologyId:string|null;weight:number};

type CheckinField={key:string;label:string;unit:string;help:string;min?:number;max?:number};

const n=(v:any)=>Number(v||0);
const round=(v:number,d=1)=>{const p=10**d;return Math.round(v*p)/p};
const pctDelta=(current:number,previous:number|null)=>previous===null||previous===0?null:round((current-previous)/previous*100,1);
const obj=(v:any):Record<string,any>=>v&&typeof v==='object'?v:{};
const days=(v:number)=>v*86_400_000;

const desiredDirection:Record<string,'up'|'down'>={
  commerce_revenue_drop:'up',commerce_stockout_rise:'down',commerce_conversion_drop:'up',commerce_margin_drop:'up',
  recurring_expiry_concentration:'down',recurring_income_drop:'up',renewal_rate_drop:'up',
  education_attendance_drop:'up',education_reenrollment_drop:'up',education_dropout_rise:'down',education_renegotiation_rise:'down'
};

const checkinCatalog:Record<string,CheckinField>={
  gross_margin_pct:{key:'gross_margin_pct',label:'Margem bruta',unit:'%',help:'Quanto sobra das vendas depois do custo direto do produto ou serviço.',min:0,max:100},
  inventory_turnover:{key:'inventory_turnover',label:'Giro de estoque',unit:'x',help:'Quantas vezes o estoque gira no período.',min:0,max:1000},
  waste_rate_pct:{key:'waste_rate_pct',label:'Perdas / desperdício',unit:'%',help:'Percentual de perdas, quebras ou desperdício no período.',min:0,max:100},
  renewal_rate_pct:{key:'renewal_rate_pct',label:'Taxa de renovação',unit:'%',help:'Percentual dos contratos elegíveis que renovaram.',min:0,max:100},
  active_enrollments:{key:'active_enrollments',label:'Matrículas ativas',unit:'alunos',help:'Quantidade de matrículas ativas no período.',min:0},
  attendance_rate_pct:{key:'attendance_rate_pct',label:'Frequência média',unit:'%',help:'Percentual agregado de presença no período.',min:0,max:100},
  reenrollment_rate_pct:{key:'reenrollment_rate_pct',label:'Taxa de rematrícula',unit:'%',help:'Percentual agregado de rematrícula entre os elegíveis.',min:0,max:100},
  dropout_rate_pct:{key:'dropout_rate_pct',label:'Evasão',unit:'%',help:'Percentual agregado de evasão no período.',min:0,max:100},
  renegotiation_rate_pct:{key:'renegotiation_rate_pct',label:'Renegociações',unit:'%',help:'Percentual agregado de mensalidades ou contratos renegociados.',min:0,max:100}
};

async function ontologyConfig(sector:string,code:string){
  const rows=await query<any>(`select id,sector,archetype,version,leading_signals,anticipation_min_days from sector_ontologies where active=true and (sector='all' or sector=$1) order by case when sector=$1 then 0 else 1 end,version desc`,[sector]);
  for(const row of rows){const list=Array.isArray(row.leading_signals)?row.leading_signals:[];const item=list.find((x:any)=>x?.code===code);if(item)return{ontologyId:String(row.id),weight:Number(item.weight||1),horizonDays:Number(item.horizonDays||row.anticipation_min_days||30)}}
  return{ontologyId:null,weight:1,horizonDays:30};
}

async function latestCommercePair(workspaceId:string,signalType:string){
  const rows=await query<any>(`select source_product,period_start,period_end,metrics,dimensions,created_at from workspace_operational_signals where workspace_id=$1 and signal_type=$2 order by period_end desc,created_at desc limit 12`,[workspaceId,signalType]);
  if(!rows.length)return{current:null,previous:null};const current=rows[0];
  const currentWindow=String(current.dimensions?.window||''),source=String(current.source_product||'');const start=new Date(current.period_start).getTime();
  const previous=rows.find((x:any,i:number)=>i>0&&String(x.source_product||'')===source&&String(x.dimensions?.window||'')===currentWindow&&new Date(x.period_end).getTime()<=start)||rows.find((x:any,i:number)=>i>0&&String(x.source_product||'')===source&&String(x.dimensions?.window||'')===currentWindow)||null;
  return{current,previous};
}

async function metricPair(workspaceId:string,key:string,minGapDays=7){
  const rows=await query<any>(`select value_numeric,observed_at,source,quality from intelligence_metrics where workspace_id=$1 and metric_key=$2 and value_numeric is not null order by observed_at desc limit 30`,[workspaceId,key]);
  if(!rows.length)return{current:null,previous:null};const current=rows[0],cutoff=new Date(current.observed_at).getTime()-days(minGapDays);const previous=rows.find((x:any,i:number)=>i>0&&new Date(x.observed_at).getTime()<=cutoff)||null;return{current,previous};
}

async function previousObservation(workspaceId:string,code:string){return (await query<any>(`select current_value,run_date from intelligence_temporal_observations where workspace_id=$1 and code=$2 and run_date<current_date order by run_date desc limit 1`,[workspaceId,code]))[0]||null}

async function recurringFacts(workspaceId:string){
  const rows=await query<any>(`select direction,amount_minor,frequency,interval_count,ends_at,active from recurring_rules where workspace_id=$1 and active=true` ,[workspaceId]);
  const monthly=(row:any)=>{const amount=n(row.amount_minor),interval=Math.max(1,n(row.interval_count)||1);if(row.frequency==='weekly')return amount*52/12/interval;if(row.frequency==='yearly')return amount/12/interval;return amount/interval};
  let total=0,expiring=0,count=0,expiringCount=0;for(const row of rows){if(row.direction!=='income')continue;const value=monthly(row);total+=value;count++;if(row.ends_at&&new Date(row.ends_at).getTime()<=Date.now()+days(60)){expiring+=value;expiringCount++}}
  return{monthlyMinor:Math.round(total),expiring60Minor:Math.round(expiring),expirySharePct:total>0?round(expiring/total*100,1):0,activeRules:count,expiringRules:expiringCount};
}

async function pushSignal(target:SectorSignal[],sector:string,base:Omit<SectorSignal,'ontologyId'|'weight'|'horizonDays'>){const cfg=await ontologyConfig(sector,base.code);target.push({...base,...cfg})}

export async function runSectorIntelligenceV3(workspaceId:string){
  const profile=await getBusinessProfile(workspaceId);const sector=String(profile?.sector||'general');const signals:SectorSignal[]=[];const observations:SectorObservation[]=[];

  if(['commerce','restaurant'].includes(sector)||Boolean(profile?.uses_inventory)){
    const [orders,inventory,conversion]=await Promise.all([latestCommercePair(workspaceId,'orders.summary'),latestCommercePair(workspaceId,'inventory.summary'),latestCommercePair(workspaceId,'conversion.summary')]);
    if(orders.current&&orders.previous){
      const cur=n(obj(orders.current.metrics).netRevenueMinor),prev=n(obj(orders.previous.metrics).netRevenueMinor),delta=pctDelta(cur,prev),triggered=prev>0&&delta!==null&&delta<=-20;const o={code:'commerce_revenue_drop',dimension:'sales' as const,currentValue:cur,previousValue:prev,deltaPct:delta,triggered,evidence:{engine:'sector-intelligence-v3',source:'orders.summary',provider:orders.current.source_product,periodEnd:orders.current.period_end}};observations.push(o);if(triggered)await pushSignal(signals,sector,{...o,severity:delta!<=-40?'critical':'attention',title:'Receita do canal perdeu ritmo',whatChanged:`A receita líquida do canal caiu ${Math.abs(delta!)}% em relação ao período comparável anterior.`,whyItMatters:'Quando a receita desacelera junto da operação, vale agir antes que a queda se consolide no caixa.',recommendation:'Separe a queda entre tráfego, conversão, ticket, estoque e recompra antes de aumentar investimento.',confidence:.9});
      const cm=obj(orders.current.metrics),pm=obj(orders.previous.metrics);if(cm.grossMarginBps!==undefined&&pm.grossMarginBps!==undefined){const curM=n(cm.grossMarginBps)/100,prevM=n(pm.grossMarginBps)/100,deltaM=pctDelta(curM,prevM),points=round(curM-prevM,1),trig=prevM>0&&points<=-4;const mo={code:'commerce_margin_drop',dimension:'finance' as const,currentValue:curM,previousValue:prevM,deltaPct:deltaM,triggered:trig,evidence:{engine:'sector-intelligence-v3',source:'orders.summary',unit:'pct'}};observations.push(mo);if(trig)await pushSignal(signals,sector,{...mo,severity:points<=-8?'critical':'attention',title:'Margem perdeu espaço',whatChanged:`A margem bruta caiu de ${round(prevM)}% para ${round(curM)}%.`,whyItMatters:'Vender com margem menor pode esconder deterioração mesmo quando o faturamento parece saudável.',recommendation:'Revise preço, descontos, mix e custo dos itens que mais pressionaram a margem.',confidence:.88})}
    }
    if(inventory.current&&inventory.previous){const c=obj(inventory.current.metrics),p=obj(inventory.previous.metrics),curActive=n(c.activeSkus),prevActive=n(p.activeSkus),curRate=curActive>0?round(n(c.outOfStockSkus)/curActive*100,1):0,prevRate=prevActive>0?round(n(p.outOfStockSkus)/prevActive*100,1):0,points=round(curRate-prevRate,1),trig=curActive>=5&&prevActive>=5&&curRate>=10&&points>=5;const o={code:'commerce_stockout_rise',dimension:'operation' as const,currentValue:curRate,previousValue:prevRate,deltaPct:pctDelta(curRate,prevRate),triggered:trig,evidence:{engine:'sector-intelligence-v3',source:'inventory.summary',activeSkus:curActive}};observations.push(o);if(trig)await pushSignal(signals,sector,{...o,severity:curRate>=25||points>=15?'critical':'attention',title:'Falta de estoque aumentou',whatChanged:`Itens sem estoque passaram de ${prevRate}% para ${curRate}% dos itens ativos.`,whyItMatters:'Ruptura crescente pode tirar vendas justamente dos itens com demanda.',recommendation:'Priorize reposição pelo giro e margem, evitando recomprar itens lentos só para preencher estoque.',confidence:.88})}
    if(conversion.current&&conversion.previous){const c=n(obj(conversion.current.metrics).conversionRateBps)/100,p=n(obj(conversion.previous.metrics).conversionRateBps)/100,delta=pctDelta(c,p),trig=p>0&&delta!==null&&delta<=-20;const o={code:'commerce_conversion_drop',dimension:'sales' as const,currentValue:c,previousValue:p,deltaPct:delta,triggered:trig,evidence:{engine:'sector-intelligence-v3',source:'conversion.summary',unit:'pct'}};observations.push(o);if(trig)await pushSignal(signals,sector,{...o,severity:delta!<=-40?'critical':'attention',title:'Conversão da loja caiu',whatChanged:`A conversão passou de ${round(p,2)}% para ${round(c,2)}%.`,whyItMatters:'Mais visitas sem compra podem apontar problema de oferta, preço, estoque ou jornada.',recommendation:'Verifique os produtos mais visitados, abandono de carrinho, preço e disponibilidade antes de aumentar tráfego.',confidence:.86})}
    const manualMargin=await metricPair(workspaceId,'gross_margin_pct',14);if(!observations.some(x=>x.code==='commerce_margin_drop')&&manualMargin.current&&manualMargin.previous){const c=Number(manualMargin.current.value_numeric),p=Number(manualMargin.previous.value_numeric),points=round(c-p,1),trig=points<=-4;const o={code:'commerce_margin_drop',dimension:'finance' as const,currentValue:c,previousValue:p,deltaPct:pctDelta(c,p),triggered:trig,evidence:{engine:'sector-intelligence-v3',source:'sector_checkin'}};observations.push(o);if(trig)await pushSignal(signals,sector,{...o,severity:points<=-8?'critical':'attention',title:'Margem perdeu espaço',whatChanged:`A margem informada caiu de ${round(p)}% para ${round(c)}%.`,whyItMatters:'Margem menor reduz a capacidade de absorver despesas, atraso ou queda de vendas.',recommendation:'Revise preço, mix, descontos e custo direto dos itens mais representativos.',confidence:.74})}
  }

  const recurring=await recurringFacts(workspaceId);if(recurring.activeRules>0||Boolean(profile?.recurring_revenue)||String(profile?.revenue_model||'')==='recurring'){
    const prevIncome=await previousObservation(workspaceId,'recurring_income_drop');const prevValue=prevIncome?Number(prevIncome.current_value):null,delta=pctDelta(recurring.monthlyMinor,prevValue),triggered=prevValue!==null&&prevValue>0&&delta!==null&&delta<=-12;const o={code:'recurring_income_drop',dimension:'resilience' as const,currentValue:recurring.monthlyMinor,previousValue:prevValue,deltaPct:delta,triggered,evidence:{engine:'sector-intelligence-v3',source:'recurring_rules',activeRules:recurring.activeRules}};observations.push(o);if(triggered)await pushSignal(signals,sector,{...o,severity:delta!<=-25?'critical':'attention',title:'Base recorrente perdeu valor',whatChanged:`O valor mensal recorrente caiu ${Math.abs(delta!)}% desde a leitura anterior comparável.`,whyItMatters:'Uma base recorrente menor reduz previsibilidade antes de o efeito aparecer integralmente no faturamento.',recommendation:'Identifique contratos encerrados, reduções e clientes sem renovação; priorize os de maior valor.',confidence:.9});
    const expiryTriggered=recurring.activeRules>=2&&recurring.expirySharePct>=25;const eo={code:'recurring_expiry_concentration',dimension:'resilience' as const,currentValue:recurring.expirySharePct,previousValue:null,deltaPct:null,triggered:expiryTriggered,evidence:{engine:'sector-intelligence-v3',source:'recurring_rules',monthlyMinor:recurring.monthlyMinor,expiring60Minor:recurring.expiring60Minor,expiringRules:recurring.expiringRules}};observations.push(eo);if(expiryTriggered)await pushSignal(signals,sector,{...eo,severity:recurring.expirySharePct>=45?'critical':'attention',title:'Muita receita recorrente vence em breve',whatChanged:`${recurring.expirySharePct}% do valor mensal recorrente está ligado a regras com término nos próximos 60 dias.`,whyItMatters:'Vencimentos concentrados podem reduzir receita previsível se as renovações forem tratadas tarde.',recommendation:'Antecipe as renovações de maior valor e registre a próxima ação para cada contrato relevante.',confidence:.92});
    const renewal=await metricPair(workspaceId,'renewal_rate_pct',14);if(renewal.current&&renewal.previous){const c=Number(renewal.current.value_numeric),p=Number(renewal.previous.value_numeric),points=round(c-p,1),trig=p>0&&points<=-8;const ro={code:'renewal_rate_drop',dimension:'customers' as const,currentValue:c,previousValue:p,deltaPct:pctDelta(c,p),triggered:trig,evidence:{engine:'sector-intelligence-v3',source:'sector_checkin'}};observations.push(ro);if(trig)await pushSignal(signals,sector,{...ro,severity:points<=-18?'critical':'attention',title:'Renovações perderam ritmo',whatChanged:`A taxa de renovação caiu de ${round(p)}% para ${round(c)}%.`,whyItMatters:'Queda de renovação enfraquece a receita futura antes de aparecer como perda consolidada.',recommendation:'Separe motivos de não renovação e atue nos clientes com maior valor ou maior chance de recuperação.',confidence:.75})}
  }

  if(sector==='education'){
    const defs=[
      {key:'attendance_rate_pct',code:'education_attendance_drop',dimension:'operation' as const,title:'Frequência média caiu',drop:true,points:5,critical:12,why:'Frequência menor pode anteceder evasão e perda de vínculo.',action:'Identifique turmas ou períodos com queda e atue antes de a ausência virar evasão.'},
      {key:'reenrollment_rate_pct',code:'education_reenrollment_drop',dimension:'customers' as const,title:'Rematrícula perdeu força',drop:true,points:8,critical:18,why:'Menor rematrícula reduz a base futura e a previsibilidade da receita.',action:'Antecipe contato com elegíveis e separe objeções por motivo e turma.'},
      {key:'dropout_rate_pct',code:'education_dropout_rise',dimension:'resilience' as const,title:'Evasão aumentou',drop:false,points:3,critical:8,why:'Evasão crescente afeta receita, ocupação e custo de aquisição de reposição.',action:'Investigue os motivos agregados de saída e trate primeiro os grupos com pior tendência.'},
      {key:'renegotiation_rate_pct',code:'education_renegotiation_rise',dimension:'finance' as const,title:'Renegociações aumentaram',drop:false,points:5,critical:12,why:'Mais renegociação pode antecipar pressão de recebimento e permanência.',action:'Acompanhe as coortes com maior aumento e atue cedo nos acordos em risco.'}
    ];
    for(const d of defs){const pair=await metricPair(workspaceId,d.key,14);if(!pair.current||!pair.previous)continue;const c=Number(pair.current.value_numeric),p=Number(pair.previous.value_numeric),change=round(c-p,1),trig=d.drop?change<=-d.points:change>=d.points;const o={code:d.code,dimension:d.dimension,currentValue:c,previousValue:p,deltaPct:pctDelta(c,p),triggered:trig,evidence:{engine:'sector-intelligence-v3',source:'sector_checkin',metricKey:d.key}};observations.push(o);if(trig)await pushSignal(signals,sector,{...o,severity:Math.abs(change)>=d.critical?'critical':'attention',title:d.title,whatChanged:`O indicador passou de ${round(p)}% para ${round(c)}%.`,whyItMatters:d.why,recommendation:d.action,confidence:.76})}
  }

  await query(`update intelligence_temporal_signals set active=false,resolved_at=coalesce(resolved_at,now()),updated_at=now() where workspace_id=$1 and run_date=current_date and evidence->>'engine'='sector-intelligence-v3'`,[workspaceId]);
  for(const observation of observations)await query(`insert into intelligence_temporal_observations(workspace_id,run_date,code,dimension,current_value,previous_value,delta_pct,signal_triggered,source,evidence) values($1,current_date,$2,$3,$4,$5,$6,$7,'sector_intelligence_v3',$8) on conflict(workspace_id,run_date,code) do update set dimension=excluded.dimension,current_value=excluded.current_value,previous_value=excluded.previous_value,delta_pct=excluded.delta_pct,signal_triggered=excluded.signal_triggered,evidence=excluded.evidence,updated_at=now()`,[workspaceId,observation.code,observation.dimension,observation.currentValue,observation.previousValue,observation.deltaPct,observation.triggered,JSON.stringify(observation.evidence)]);
  for(const signal of signals)await query(`insert into intelligence_temporal_signals(workspace_id,ontology_id,run_date,code,dimension,severity,title,what_changed,why_it_matters,recommendation,current_value,previous_value,delta_pct,horizon_days,confidence,evidence,active) values($1,$2,current_date,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,true) on conflict(workspace_id,run_date,code) do update set ontology_id=excluded.ontology_id,dimension=excluded.dimension,severity=excluded.severity,title=excluded.title,what_changed=excluded.what_changed,why_it_matters=excluded.why_it_matters,recommendation=excluded.recommendation,current_value=excluded.current_value,previous_value=excluded.previous_value,delta_pct=excluded.delta_pct,horizon_days=excluded.horizon_days,confidence=excluded.confidence,evidence=excluded.evidence,active=true,resolved_at=null,updated_at=now()`,[workspaceId,signal.ontologyId,signal.code,signal.dimension,signal.severity,signal.title,signal.whatChanged,signal.whyItMatters,signal.recommendation,signal.currentValue,signal.previousValue,signal.deltaPct,signal.horizonDays,signal.confidence,JSON.stringify({...signal.evidence,engine:'sector-intelligence-v3',weight:signal.weight})]);

  const all=await query<any>(`select s.code,s.severity,s.confidence,s.horizon_days,s.evidence,o.leading_signals from intelligence_temporal_signals s left join sector_ontologies o on o.id=s.ontology_id where s.workspace_id=$1 and s.run_date=current_date and s.active=true`,[workspaceId]);
  let stress=0;for(const row of all){const list=Array.isArray(row.leading_signals)?row.leading_signals:[],item=list.find((x:any)=>x?.code===row.code),weight=Number(item?.weight||row.evidence?.weight||1);stress+=(row.severity==='critical'?28:14)*Math.max(.5,weight)}stress=Math.max(0,Math.min(100,Math.round(stress)));
  const posture=stress>=55?'elevated':stress>=20?'attention':'normal';const previous=(await query<any>(`select operational_stress_index from intelligence_risk_snapshots where workspace_id=$1 and run_date<current_date order by run_date desc limit 1`,[workspaceId]))[0];const diff=previous?stress-Number(previous.operational_stress_index||0):0,trend=diff>=10?'worsening':diff<=-10?'improving':'stable';
  await query(`update intelligence_risk_snapshots set operational_stress_index=$2,posture=$3,trend=$4,signal_summary=$5,evidence=coalesce(evidence,'{}'::jsonb)||$6::jsonb,as_of=now() where workspace_id=$1 and run_date=current_date and model_version='temporal-risk-v2'`,[workspaceId,stress,posture,trend,JSON.stringify(all.map((x:any)=>({code:x.code,severity:x.severity,horizonDays:x.horizon_days,confidence:Number(x.confidence)}))),JSON.stringify({sectorEngine:'sector-intelligence-v3',sectorDetectorsEvaluated:observations.length,sectorSignals:signals.length})]);
  return{sector,observations:observations.length,signals:signals.length,codes:signals.map(x=>x.code),stress,posture,trend};
}

export async function evaluateTemporalActions(workspaceId?:string){
  const rows=await query<any>(`select a.*,t.status task_status,t.completed_at task_completed,s.code from intelligence_actions a join intelligence_temporal_signals s on s.id=a.temporal_signal_id left join tasks t on t.id=a.task_id where a.temporal_signal_id is not null and a.evaluated_at is null and coalesce(a.evaluation_due_at,now())<=now() and ($1::uuid is null or a.workspace_id=$1)`,[workspaceId||null]);
  let evaluated=0,improved=0,stable=0,worsened=0;for(const action of rows){if(action.task_status!=='done'&&action.status!=='done')continue;const obs=(await query<any>(`select * from intelligence_temporal_observations where workspace_id=$1 and code=$2 and run_date>=coalesce($3::timestamptz,now()-interval '90 days')::date order by run_date desc limit 1`,[action.workspace_id,action.code,action.task_completed||action.completed_at||action.created_at]))[0];if(!obs||obs.current_value===null||action.baseline_value===null)continue;const baseline=Number(action.baseline_value),current=Number(obs.current_value),delta=round(current-baseline,2),pct=baseline===0?null:round(delta/Math.abs(baseline)*100,1),dir=String(action.desired_direction||desiredDirection[action.code]||'up');const threshold=Math.max(Math.abs(baseline)*.03,1);let status:'improved'|'stable'|'worsened'='stable';if(dir==='up'){if(delta>threshold)status='improved';else if(delta<-threshold)status='worsened'}else{if(delta<-threshold)status='improved';else if(delta>threshold)status='worsened'}const summary=status==='improved'?'O indicador caminhou na direção desejada após a ação.':status==='worsened'?'O indicador se moveu na direção oposta; vale revisar a ação e o contexto.':'O indicador permaneceu praticamente estável no período observado.';await query(`update intelligence_actions set status=case when status='created' then 'done' else status end,evaluated_at=now(),evaluation_status=$2,observed_value=$3,effect_delta=$4,effect_pct=$5,effect_summary=$6 where id=$1`,[action.id,status,current,delta,pct,summary]);evaluated++;if(status==='improved')improved++;else if(status==='worsened')worsened++;else stable++}
  return{evaluated,improved,stable,worsened};
}

export async function createTemporalAction(workspaceId:string,userId:string,signalId:string){
  const signal=(await query<any>(`select * from intelligence_temporal_signals where id=$1 and workspace_id=$2 and active=true`,[signalId,workspaceId]))[0];if(!signal)throw new Error('Sinal temporal não encontrado ou não está mais ativo.');const existing=(await query<any>(`select a.*,t.status task_status from intelligence_actions a left join tasks t on t.id=a.task_id where a.workspace_id=$1 and a.temporal_signal_id=$2 limit 1`,[workspaceId,signalId]))[0];if(existing)return{existing:true,action:existing};
  const dueDays=Math.min(30,Math.max(7,Math.round(Number(signal.horizon_days||30)/2)));const dueAt=new Date(Date.now()+days(dueDays)).toISOString();const priority=signal.severity==='critical'?'critical':'high',title=`Ação NexOffice · ${signal.title}`;
  const task=(await query<any>(`insert into tasks(workspace_id,title,description,status,priority,due_at,metadata) values($1,$2,$3,'todo',$4,$5,$6) returning *`,[workspaceId,title,`${signal.recommendation||''}\n\nMotivo: ${signal.what_changed||''}`.trim(),priority,dueAt,JSON.stringify({origin:'trajectory',temporalSignalId:signal.id,signalCode:signal.code})]))[0];
  const action=(await query<any>(`insert into intelligence_actions(workspace_id,temporal_signal_id,task_id,source_type,source_key,title,status,created_by,baseline_value,desired_direction,evaluation_due_at,evaluation_status,metadata) values($1,$2,$3,'sector',$4,$5,'created',$6,$7,$8,$9,'waiting',$10) returning *`,[workspaceId,signal.id,task.id,signal.code,title,userId,signal.current_value,desiredDirection[signal.code]||'up',dueAt,JSON.stringify({horizonDays:signal.horizon_days,baselineEvidence:signal.evidence})]))[0];return{existing:false,action,task};
}

export function checkinFieldsForProfile(profile:any):CheckinField[]{const sector=String(profile?.sector||'general'),keys:string[]=[];if(['commerce','restaurant'].includes(sector)||profile?.uses_inventory)keys.push('gross_margin_pct','inventory_turnover','waste_rate_pct');if(profile?.recurring_revenue||String(profile?.revenue_model||'')==='recurring')keys.push('renewal_rate_pct');if(sector==='education')keys.push('active_enrollments','attendance_rate_pct','reenrollment_rate_pct','dropout_rate_pct','renegotiation_rate_pct');return [...new Set(keys)].map(k=>checkinCatalog[k]).filter(Boolean)}

export async function getSectorCheckin(workspaceId:string){const profile=await getBusinessProfile(workspaceId);const fields=checkinFieldsForProfile(profile);const latest:Record<string,any>={};for(const field of fields){latest[field.key]=(await query<any>(`select value_numeric,observed_at,source from intelligence_metrics where workspace_id=$1 and metric_key=$2 and value_numeric is not null order by observed_at desc limit 1`,[workspaceId,field.key]))[0]||null}return{sector:String(profile?.sector||'general'),fields,latest}}

export async function recordSectorCheckin(workspaceId:string,values:Record<string,number>){const profile=await getBusinessProfile(workspaceId),allowed=new Map(checkinFieldsForProfile(profile).map(x=>[x.key,x]));for(const [key,value] of Object.entries(values)){const field=allowed.get(key);if(!field||!Number.isFinite(value))continue;if(field.min!==undefined&&value<field.min)continue;if(field.max!==undefined&&value>field.max)continue;await query(`insert into intelligence_metrics(workspace_id,metric_key,value_numeric,unit,source,quality,confidence,observed_at,metadata) values($1,$2,$3,$4,'client_reported','medium',0.75,now(),$5)`,[workspaceId,key,value,field.unit,JSON.stringify({origin:'sector_checkin_v3'})])}return runSectorIntelligenceV3(workspaceId)}

export async function enrichTrajectoryWithActions(workspaceId:string,result:any){const rows=await query<any>(`select s.id,s.code,a.id action_id,a.status action_status,t.status task_status,a.evaluation_status,a.effect_summary from intelligence_temporal_signals s left join intelligence_actions a on a.temporal_signal_id=s.id left join tasks t on t.id=a.task_id where s.workspace_id=$1 and s.active=true`,[workspaceId]);const byCode=new Map(rows.map((x:any)=>[x.code,x]));return{...result,movements:(result?.movements||[]).map((m:any)=>{const row:any=byCode.get(m.code);return{...m,signalId:row?.id||null,action:row?.action_id?{id:row.action_id,status:row.action_status,taskStatus:row.task_status,evaluationStatus:row.evaluation_status,effectSummary:row.effect_summary}:null}})}}

export async function readSectorValidationOverview(){const [coverage,actions,codes]=await Promise.all([
  query<any>(`select count(*)::int observations,count(distinct workspace_id)::int companies,count(*) filter(where signal_triggered)::int triggered from intelligence_temporal_observations where run_date>=current_date-90`),
  query<any>(`select count(*)::int actions,count(*) filter(where evaluation_status='improved')::int improved,count(*) filter(where evaluation_status='stable')::int stable,count(*) filter(where evaluation_status='worsened')::int worsened,count(*) filter(where evaluation_status='waiting')::int waiting from intelligence_actions where temporal_signal_id is not null and created_at>=now()-interval '90 days'`),
  query<any>(`select o.code,count(*)::int observations,count(*) filter(where o.signal_triggered)::int triggers,count(a.id)::int actions,count(a.id) filter(where a.evaluation_status='improved')::int improved,count(a.id) filter(where a.evaluation_status='worsened')::int worsened from intelligence_temporal_observations o left join intelligence_temporal_signals s on s.workspace_id=o.workspace_id and s.run_date=o.run_date and s.code=o.code left join intelligence_actions a on a.temporal_signal_id=s.id where o.run_date>=current_date-90 group by o.code order by triggers desc,observations desc`)
]);return{coverage:coverage[0]||{},actions:actions[0]||{},codes}}
