import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {ApiError,workspaceContext} from './auth.js';
import {query} from './db.js';
import {auditLog,emitBusinessEvent} from './events.js';

const uuid=z.string().uuid();
const taskSchema=z.object({contactId:uuid.optional().nullable(),dealId:uuid.optional().nullable(),title:z.string().min(1),description:z.string().optional().nullable(),status:z.enum(['todo','doing','done','cancelled']).default('todo'),priority:z.enum(['low','normal','high','critical']).default('normal'),assignedTo:uuid.optional().nullable(),dueAt:z.string().datetime().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});
const appointmentSchema=z.object({contactId:uuid.optional().nullable(),title:z.string().min(1),startsAt:z.string().datetime(),endsAt:z.string().datetime().optional().nullable(),status:z.enum(['scheduled','confirmed','completed','cancelled','no_show']).default('scheduled'),assignedTo:uuid.optional().nullable(),externalRef:z.string().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});

export async function registerOpsRoutes(app:FastifyInstance){
  app.get('/v1/tasks',async req=>{const ctx=await workspaceContext(req,'agenda.read'),status=String((req.query as any)?.status||'');return query<any>(`select t.*,c.name contact_name,d.title deal_title from tasks t left join crm_contacts c on c.id=t.contact_id left join crm_deals d on d.id=t.deal_id where t.workspace_id=$1 and ($2='' or t.status=$2) order by case t.priority when 'critical' then 1 when 'high' then 2 else 3 end,t.due_at nulls last,t.created_at desc`,[ctx.workspaceId,status])});
  app.post('/v1/tasks',async req=>{const ctx=await workspaceContext(req,'agenda.write'),input=taskSchema.parse(req.body);const rows=await query<any>(`insert into tasks(workspace_id,contact_id,deal_id,title,description,status,priority,assigned_to,due_at,completed_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[ctx.workspaceId,input.contactId||null,input.dealId||null,input.title,input.description||null,input.status,input.priority,input.assignedTo||null,input.dueAt||null,input.status==='done'?new Date().toISOString():null,JSON.stringify(input.metadata)]);await auditLog(ctx,'task.created','task',rows[0].id,null,rows[0]);await emitBusinessEvent(ctx.workspaceId,'task.created','nexoffice.tasks','task',rows[0].id,{title:input.title,status:input.status,priority:input.priority,dueAt:input.dueAt||null});if(input.status==='done')await emitBusinessEvent(ctx.workspaceId,'task.completed','nexoffice.tasks','task',rows[0].id,{title:input.title});return rows[0]});
  app.patch('/v1/tasks/:id',async req=>{const ctx=await workspaceContext(req,'agenda.write'),id=uuid.parse((req.params as any).id),input=taskSchema.partial().parse(req.body),before=(await query<any>(`select * from tasks where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Tarefa não encontrada.');const status=input.status??before.status;const rows=await query<any>(`update tasks set contact_id=$3,deal_id=$4,title=$5,description=$6,status=$7,priority=$8,assigned_to=$9,due_at=$10,completed_at=$11,metadata=$12,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.dealId===undefined?before.deal_id:input.dealId,input.title??before.title,input.description===undefined?before.description:input.description,status,input.priority??before.priority,input.assignedTo===undefined?before.assigned_to:input.assignedTo,input.dueAt===undefined?before.due_at:input.dueAt,status==='done'?(before.completed_at||new Date().toISOString()):null,JSON.stringify(input.metadata??before.metadata)]);await auditLog(ctx,'task.updated','task',id,before,rows[0]);if(status!==before.status)await emitBusinessEvent(ctx.workspaceId,status==='done'?'task.completed':'task.status_changed','nexoffice.tasks','task',id,{title:rows[0].title,from:before.status,to:status});return rows[0]});
  app.get('/v1/appointments',async req=>{const ctx=await workspaceContext(req,'agenda.read'),from=(req.query as any)?.from||new Date(Date.now()-7*86400000).toISOString(),to=(req.query as any)?.to||new Date(Date.now()+45*86400000).toISOString();return query<any>(`select a.*,c.name contact_name from appointments a left join crm_contacts c on c.id=a.contact_id where a.workspace_id=$1 and a.starts_at between $2 and $3 order by a.starts_at`,[ctx.workspaceId,from,to])});
  app.post('/v1/appointments',async req=>{const ctx=await workspaceContext(req,'agenda.write'),input=appointmentSchema.parse(req.body);if(input.endsAt&&new Date(input.endsAt)<=new Date(input.startsAt))throw new ApiError(400,'invalid_time_range','O fim precisa ser posterior ao início.');const rows=await query<any>(`insert into appointments(workspace_id,contact_id,title,starts_at,ends_at,status,assigned_to,external_ref,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[ctx.workspaceId,input.contactId||null,input.title,input.startsAt,input.endsAt||null,input.status,input.assignedTo||null,input.externalRef||null,JSON.stringify(input.metadata)]);await auditLog(ctx,'appointment.created','appointment',rows[0].id,null,rows[0]);await emitBusinessEvent(ctx.workspaceId,'appointment.created','nexoffice.agenda','appointment',rows[0].id,{title:input.title,startsAt:input.startsAt,status:input.status});if(input.status==='completed'||input.status==='no_show'||input.status==='cancelled')await emitBusinessEvent(ctx.workspaceId,`appointment.${input.status}`,'nexoffice.agenda','appointment',rows[0].id,{title:input.title,startsAt:input.startsAt});return rows[0]});
  app.patch('/v1/appointments/:id',async req=>{const ctx=await workspaceContext(req,'agenda.write'),id=uuid.parse((req.params as any).id),input=appointmentSchema.partial().parse(req.body),before=(await query<any>(`select * from appointments where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Compromisso não encontrado.');const starts=input.startsAt??String(before.starts_at),ends=input.endsAt===undefined?(before.ends_at?String(before.ends_at):null):input.endsAt;if(ends&&new Date(ends)<=new Date(starts))throw new ApiError(400,'invalid_time_range','O fim precisa ser posterior ao início.');const rows=await query<any>(`update appointments set contact_id=$3,title=$4,starts_at=$5,ends_at=$6,status=$7,assigned_to=$8,external_ref=$9,metadata=$10,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.title??before.title,starts,ends,input.status??before.status,input.assignedTo===undefined?before.assigned_to:input.assignedTo,input.externalRef===undefined?before.external_ref:input.externalRef,JSON.stringify(input.metadata??before.metadata)]);await auditLog(ctx,'appointment.updated','appointment',id,before,rows[0]);if(input.status&&input.status!==before.status)await emitBusinessEvent(ctx.workspaceId,['completed','cancelled','no_show'].includes(input.status)?`appointment.${input.status}`:'appointment.status_changed','nexoffice.agenda','appointment',id,{title:rows[0].title,startsAt:String(rows[0].starts_at),from:before.status,to:input.status});return rows[0]});
}
