import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {workspaceContext,ApiError} from './auth.js';
import {query} from './db.js';
import {auditLog,emitBusinessEvent} from './events.js';

const uuid=z.string().uuid();
const contactSchema=z.object({kind:z.enum(['person','company']).default('person'),name:z.string().min(1),email:z.string().email().optional().nullable(),phone:z.string().optional().nullable(),companyName:z.string().optional().nullable(),documentNumber:z.string().optional().nullable(),source:z.string().optional().nullable(),tags:z.array(z.string()).default([]),customFields:z.record(z.string(),z.unknown()).default({})});
const dealSchema=z.object({contactId:uuid.optional().nullable(),title:z.string().min(1),stage:z.enum(['lead','qualified','meeting','proposal','won','lost']).default('lead'),valueMinor:z.number().int().nonnegative().default(0),currency:z.string().length(3).default('BRL'),ownerId:uuid.optional().nullable(),source:z.string().optional().nullable(),nextAction:z.string().optional().nullable(),expectedCloseAt:z.string().datetime().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});

export async function registerCrmRoutes(app:FastifyInstance){
  app.get('/v1/crm/contacts',async req=>{const ctx=await workspaceContext(req,'crm.read'),q=String((req.query as any)?.q||'').trim();return query<any>(`select * from crm_contacts where workspace_id=$1 and ($2='' or name ilike '%'||$2||'%' or coalesce(email,'') ilike '%'||$2||'%' or coalesce(phone,'') ilike '%'||$2||'%' or coalesce(company_name,'') ilike '%'||$2||'%') order by updated_at desc limit 500`,[ctx.workspaceId,q])});
  app.post('/v1/crm/contacts',async req=>{const ctx=await workspaceContext(req,'crm.write'),input=contactSchema.parse(req.body);const rows=await query<any>(`insert into crm_contacts(workspace_id,kind,name,email,phone,company_name,document_number,source,tags,custom_fields) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[ctx.workspaceId,input.kind,input.name,input.email||null,input.phone||null,input.companyName||null,input.documentNumber||null,input.source||null,input.tags,JSON.stringify(input.customFields)]);await auditLog(ctx,'crm.contact.created','crm_contact',rows[0].id,null,rows[0]);await emitBusinessEvent(ctx.workspaceId,'lead.created','nexoffice.crm','contact',rows[0].id,{name:input.name,source:input.source||null});return rows[0]});
  app.get('/v1/crm/contacts/:id',async req=>{const ctx=await workspaceContext(req,'crm.read'),id=uuid.parse((req.params as any).id),contact=(await query<any>(`select * from crm_contacts where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!contact)throw new ApiError(404,'not_found','Contato não encontrado.');const [activities,deals,tasks,appointments,documents,ledger]=await Promise.all([query<any>(`select * from crm_activities where workspace_id=$1 and contact_id=$2 order by occurred_at desc limit 200`,[ctx.workspaceId,id]),query<any>(`select * from crm_deals where workspace_id=$1 and contact_id=$2 order by updated_at desc`,[ctx.workspaceId,id]),query<any>(`select * from tasks where workspace_id=$1 and contact_id=$2 order by created_at desc`,[ctx.workspaceId,id]),query<any>(`select * from appointments where workspace_id=$1 and contact_id=$2 order by starts_at desc limit 100`,[ctx.workspaceId,id]),query<any>(`select * from document_refs where workspace_id=$1 and contact_id=$2 order by updated_at desc`,[ctx.workspaceId,id]),query<any>(`select * from ledger_entries where workspace_id=$1 and contact_id=$2 order by created_at desc limit 200`,[ctx.workspaceId,id])]);return {contact,activities,deals,tasks,appointments,documents,ledger}});
  app.patch('/v1/crm/contacts/:id',async req=>{const ctx=await workspaceContext(req,'crm.write'),id=uuid.parse((req.params as any).id),input=contactSchema.partial().parse(req.body),before=(await query<any>(`select * from crm_contacts where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Contato não encontrado.');const rows=await query<any>(`update crm_contacts set kind=$3,name=$4,email=$5,phone=$6,company_name=$7,document_number=$8,source=$9,tags=$10,custom_fields=$11,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.kind??before.kind,input.name??before.name,input.email===undefined?before.email:input.email,input.phone===undefined?before.phone:input.phone,input.companyName===undefined?before.company_name:input.companyName,input.documentNumber===undefined?before.document_number:input.documentNumber,input.source===undefined?before.source:input.source,input.tags??before.tags,JSON.stringify(input.customFields??before.custom_fields)]);await auditLog(ctx,'crm.contact.updated','crm_contact',id,before,rows[0]);return rows[0]});
  app.get('/v1/crm/activities',async req=>{const ctx=await workspaceContext(req,'crm.read'),contactId=(req.query as any)?.contactId||null,dealId=(req.query as any)?.dealId||null;return query<any>(`select a.*,c.name contact_name from crm_activities a left join crm_contacts c on c.id=a.contact_id where a.workspace_id=$1 and ($2::uuid is null or a.contact_id=$2) and ($3::uuid is null or a.deal_id=$3) order by occurred_at desc limit 500`,[ctx.workspaceId,contactId,dealId])});
  app.post('/v1/crm/activities',async req=>{const ctx=await workspaceContext(req,'crm.write'),input=z.object({contactId:uuid.optional().nullable(),dealId:uuid.optional().nullable(),type:z.enum(['note','call','email','whatsapp','sms','meeting','task','system']),direction:z.enum(['inbound','outbound']).optional().nullable(),subject:z.string().optional().nullable(),body:z.string().optional().nullable(),occurredAt:z.string().datetime().optional(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const rows=await query<any>(`insert into crm_activities(workspace_id,contact_id,deal_id,type,direction,subject,body,occurred_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[ctx.workspaceId,input.contactId||null,input.dealId||null,input.type,input.direction||null,input.subject||null,input.body||null,input.occurredAt||new Date().toISOString(),JSON.stringify(input.metadata)]);await auditLog(ctx,'crm.activity.created','crm_activity',rows[0].id,null,{type:input.type,contactId:input.contactId});return rows[0]});
  app.get('/v1/crm/deals',async req=>{const ctx=await workspaceContext(req,'crm.read'),stage=String((req.query as any)?.stage||'');return query<any>(`select d.*,c.name contact_name,c.email contact_email,c.phone contact_phone from crm_deals d left join crm_contacts c on c.id=d.contact_id where d.workspace_id=$1 and ($2='' or d.stage::text=$2) order by d.updated_at desc limit 500`,[ctx.workspaceId,stage])});
  app.post('/v1/crm/deals',async req=>{const ctx=await workspaceContext(req,'crm.write'),input=dealSchema.parse(req.body);const rows=await query<any>(`insert into crm_deals(workspace_id,contact_id,title,stage,value_minor,currency,owner_id,source,next_action,expected_close_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[ctx.workspaceId,input.contactId||null,input.title,input.stage,input.valueMinor,input.currency,input.ownerId||null,input.source||null,input.nextAction||null,input.expectedCloseAt||null,JSON.stringify(input.metadata)]);await auditLog(ctx,'crm.deal.created','crm_deal',rows[0].id,null,rows[0]);return rows[0]});
  app.patch('/v1/crm/deals/:id',async req=>{const ctx=await workspaceContext(req,'crm.write'),id=uuid.parse((req.params as any).id),input=dealSchema.partial().parse(req.body),before=(await query<any>(`select * from crm_deals where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Oportunidade não encontrada.');const rows=await query<any>(`update crm_deals set contact_id=$3,title=$4,stage=$5,value_minor=$6,currency=$7,owner_id=$8,source=$9,next_action=$10,expected_close_at=$11,metadata=$12,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.title??before.title,input.stage??before.stage,input.valueMinor??Number(before.value_minor),input.currency??before.currency,input.ownerId===undefined?before.owner_id:input.ownerId,input.source===undefined?before.source:input.source,input.nextAction===undefined?before.next_action:input.nextAction,input.expectedCloseAt===undefined?before.expected_close_at:input.expectedCloseAt,JSON.stringify(input.metadata??before.metadata)]);await auditLog(ctx,'crm.deal.updated','crm_deal',id,before,rows[0]);if(input.stage&&input.stage!==before.stage)await emitBusinessEvent(ctx.workspaceId,input.stage==='won'?'deal.won':'deal.stage_changed','nexoffice.crm','deal',id,{title:rows[0].title,from:before.stage,to:input.stage,valueMinor:Number(rows[0].value_minor)});return rows[0]});
}
