import type {FastifyInstance} from 'fastify';
import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import {z} from 'zod';
import {workspaceContext} from './auth.js';
import {auditLog} from './events.js';
import {getBusinessProfile,upsertBusinessProfile} from './business-intelligence.js';

const publicUrl=z.string().trim().max(1000).optional().nullable();
const enrichSchema=z.object({businessName:z.string().trim().max(180).optional().default(''),cnpj:z.string().trim().max(32).optional().default(''),website:publicUrl,instagram:publicUrl,whatsapp:z.string().trim().max(80).optional().default(''),socialUrls:z.array(z.string().trim().max(1000)).max(8).optional().default([])});
const confirmSchema=z.object({sector:z.string().trim().min(2).max(80).optional(),subsector:z.string().trim().max(120).nullable().optional(),revenueModel:z.string().trim().max(80).optional(),sellsProducts:z.boolean().optional(),sellsServices:z.boolean().optional(),recurringRevenue:z.boolean().optional(),usesAgenda:z.boolean().optional(),usesInventory:z.boolean().optional(),usesContracts:z.boolean().optional(),employeeCount:z.number().int().min(0).max(100000).nullable().optional(),activeCustomersEstimate:z.number().int().min(0).max(100000000).nullable().optional(),primarySalesChannel:z.string().trim().max(120).nullable().optional(),seasonality:z.string().trim().max(300).nullable().optional(),mainDependency:z.string().trim().max(300).nullable().optional(),notes:z.string().trim().max(2000).nullable().optional(),metadata:z.record(z.string(),z.unknown()).default({}),complete:z.boolean().default(false)});

type Source={kind:'cnpj'|'website'|'social'|'search';url?:string;status:'ok'|'not_found'|'unavailable'|'blocked'|'invalid';label:string;fetchedAt:string};
type Discovered={businessName?:string;legalName?:string;tradeName?:string;sector?:string;subsector?:string;city?:string;state?:string;email?:string;phone?:string;description?:string;websiteTitle?:string;productsOrServices?:string[];socialLinks?:string[];headings?:string[];publicReferences?:string[];registryStatus?:string;cnpj?:string};
type ScanResult={source:Source;data:Discovered};
const now=()=>new Date().toISOString();
const clean=(v:any,max=1000)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,max);
const unique=(items:string[],limit=20)=>[...new Set(items.map(v=>clean(v,300)).filter(Boolean))].slice(0,limit);
const asObject=(v:any):Record<string,any>=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
function deepMerge(a:any,b:any):any{if(Array.isArray(b))return b;if(!b||typeof b!=='object')return b;const out={...asObject(a)};for(const [k,v] of Object.entries(b))out[k]=v&&typeof v==='object'&&!Array.isArray(v)?deepMerge(out[k],v):v;return out}
function normalizeCnpj(value:string){return value.toUpperCase().replace(/[^0-9A-Z]/g,'').slice(0,14)}
function normalizeUrl(value:string){const raw=value.trim();if(!raw)return'';const full=/^https?:\/\//i.test(raw)?raw:`https://${raw}`;const u=new URL(full);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw new Error('invalid_url');u.hash='';return u.toString()}
function privateIp(ip:string){if(ip==='::1'||ip==='::'||ip.toLowerCase().startsWith('fe80:')||ip.toLowerCase().startsWith('fc')||ip.toLowerCase().startsWith('fd'))return true;if(isIP(ip)!==4)return false;const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||p[0]>=224}
async function assertPublicUrl(raw:string){const normalized=normalizeUrl(raw),u=new URL(normalized),host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local')||host.endsWith('.internal')||privateIp(host))throw new Error('private_url');if(isIP(host)){if(privateIp(host))throw new Error('private_url');return normalized}const addresses=await lookup(host,{all:true});if(!addresses.length||addresses.some(a=>privateIp(a.address)))throw new Error('private_url');return normalized}
async function fetchPublicHtml(raw:string){let current=await assertPublicUrl(raw);for(let redirects=0;redirects<4;redirects++){const response=await fetch(current,{headers:{'user-agent':'NexOfficeBusinessDiscovery/1.1 (+public-business-profile)',accept:'text/html,application/xhtml+xml'},redirect:'manual',signal:AbortSignal.timeout(9000)});if(response.status>=300&&response.status<400){const location=response.headers.get('location');if(!location)throw new Error('redirect_without_location');current=await assertPublicUrl(new URL(location,current).toString());continue}if(!response.ok)throw new Error(`http_${response.status}`);const type=String(response.headers.get('content-type')||'').toLowerCase();if(!type.includes('text/html')&&!type.includes('application/xhtml'))throw new Error('not_html');const length=Number(response.headers.get('content-length')||0);if(length>2_500_000)throw new Error('too_large');return{url:current,html:(await response.text()).slice(0,2_500_000)}}throw new Error('too_many_redirects')}
function decode(value:string){return value.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
function strip(value:string){return clean(decode(value.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')),500)}
function meta(html:string,key:string){const tags=html.match(/<meta\b[^>]*>/gi)||[];for(const tag of tags){const name=(tag.match(/(?:name|property)=["']([^"']+)["']/i)||[])[1];if(String(name||'').toLowerCase()!==key.toLowerCase())continue;return clean((tag.match(/content=["']([^"']*)["']/i)||[])[1],1000)}return''}
function tagTexts(html:string,tag:string,limit=20){const out:string[]=[];const re=new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`,'gi');let m:RegExpExecArray|null;while((m=re.exec(html))&&out.length<limit){const text=strip(m[1]);if(text.length>=3)out.push(text)}return unique(out,limit)}
function jsonLdOfferings(html:string){const out:string[]=[];const re=/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))){try{const parsed=JSON.parse(m[1]);const nodes=Array.isArray(parsed)?parsed:[parsed];const walk=(node:any)=>{if(!node||typeof node!=='object')return;if(Array.isArray(node)){node.forEach(walk);return}const type=Array.isArray(node['@type'])?node['@type'].join(' '):String(node['@type']||'');if(/Product|Service|Offer|Course/i.test(type)&&node.name)out.push(clean(node.name,180));for(const v of Object.values(node))if(v&&typeof v==='object')walk(v)};nodes.forEach(walk)}catch{}}return unique(out,20)}
function socialLinks(html:string,baseUrl:string){const result:string[]=[];const re=/href=["']([^"']+)["']/gi;let m:RegExpExecArray|null;while((m=re.exec(html))&&result.length<50){try{const url=new URL(m[1],baseUrl);if(/(^|\.)(instagram|facebook|linkedin|tiktok|x|twitter|youtube)\.com$/i.test(url.hostname.replace(/^www\./,'')))result.push(url.toString())}catch{}}return unique(result,12)}
async function scanPublicPage(raw:string,kind:'website'|'social'):Promise<ScanResult>{try{const page=await fetchPublicHtml(raw),html=page.html;const title=clean((html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||meta(html,'og:title'),240);const description=meta(html,'description')||meta(html,'og:description');const headings=unique([...tagTexts(html,'h1',8),...tagTexts(html,'h2',16),...tagTexts(html,'h3',10)],24);const offerings=unique([...jsonLdOfferings(html),...headings.filter(x=>x.length>=3&&x.length<=120)],16);return{source:{kind,url:page.url,status:'ok',label:kind==='website'?'Site público':'Perfil público',fetchedAt:now()},data:{websiteTitle:title||undefined,description:description||undefined,headings,productsOrServices:offerings,socialLinks:socialLinks(html,page.url)}}}catch(error:any){const code=String(error?.message||'');return{source:{kind,url:raw,status:/private|invalid/.test(code)?'invalid':/http_40[13]/.test(code)?'blocked':'unavailable',label:kind==='website'?'Site público':'Perfil público',fetchedAt:now()},data:{}}}}
function searchResultUrl(raw:string){try{const decoded=decode(raw);const u=new URL(decoded,'https://html.duckduckgo.com');const wrapped=u.searchParams.get('uddg');const target=wrapped?decodeURIComponent(wrapped):u.toString();const parsed=new URL(target);if(!['http:','https:'].includes(parsed.protocol))return'';if(/(^|\.)duckduckgo\.com$/i.test(parsed.hostname))return'';return parsed.toString()}catch{return''}}
function publicQuery(input:z.infer<typeof enrichSchema>){const handle=String(input.instagram||'').match(/(?:instagram\.com\/|@)([A-Za-z0-9._]+)/i)?.[1]||'';return clean([input.businessName?`"${input.businessName}"`:'',handle?`"${handle}" Instagram`:'','Brasil'].filter(Boolean).join(' '),280)}
async function searchPublicWeb(input:z.infer<typeof enrichSchema>):Promise<ScanResult>{const q=publicQuery(input);if(!q||(!input.businessName&&!input.instagram))return{source:{kind:'search',status:'not_found',label:'Busca pública na web',fetchedAt:now()},data:{}};const searchUrl=`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`;try{const response=await fetch(searchUrl,{headers:{'user-agent':'Mozilla/5.0 (compatible; NexOfficeBusinessDiscovery/1.1)','accept':'text/html'},signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`http_${response.status}`);const html=(await response.text()).slice(0,1_500_000),matches:Array<{title:string;url:string;snippet:string}>=[];const re=/<a[^>]*class=["'][^"']*result__a[^"']*["'][^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))&&matches.length<8){const url=searchResultUrl(m[1]),title=strip(m[2]);if(!url||!title)continue;const after=html.slice(re.lastIndex,re.lastIndex+1800);const snippetMatch=after.match(/class=["'][^"']*result__snippet[^"']*["'][^>]*>([\s\S]*?)<\/(?:a|div)>/i);matches.push({title,url,snippet:snippetMatch?strip(snippetMatch[1]):''})}if(!matches.length)return{source:{kind:'search',url:searchUrl,status:'not_found',label:'Busca pública na web',fetchedAt:now()},data:{}};const refs=unique(matches.slice(0,6).map(x=>`${x.title}${x.snippet?` — ${x.snippet}`:''} — ${x.url}`),6);const socials=unique(matches.map(x=>x.url).filter(url=>/(instagram|facebook|linkedin|tiktok|x|twitter|youtube)\.com/i.test(url)),10);const candidateUrls=matches.map(x=>x.url).filter(url=>!/(instagram|facebook|linkedin|tiktok|x|twitter|youtube|google|bing|duckduckgo)\.com/i.test(url)).slice(0,2);const pageScans=await Promise.all(candidateUrls.map(url=>scanPublicPage(url,'website')));const pageData=mergeDiscovered(pageScans.filter(x=>x.source.status==='ok').map(x=>x.data));const first=matches[0];return{source:{kind:'search',url:searchUrl,status:'ok',label:'Busca pública na web',fetchedAt:now()},data:mergeDiscovered([{websiteTitle:first.title||undefined,description:first.snippet||undefined,publicReferences:refs,socialLinks:socials},pageData])}}catch{return{source:{kind:'search',url:searchUrl,status:'unavailable',label:'Busca pública na web',fetchedAt:now()},data:{}}}}
async function scanCnpj(raw:string):Promise<ScanResult>{const cnpj=normalizeCnpj(raw);if(!cnpj)return{source:{kind:'cnpj',status:'not_found',label:'CNPJ',fetchedAt:now()},data:{}};if(cnpj.length!==14)return{source:{kind:'cnpj',status:'invalid',label:'CNPJ',fetchedAt:now()},data:{cnpj}};try{const response=await fetch(`https://brasilapi.com.br/api/cnpj/v1/${encodeURIComponent(cnpj)}`,{headers:{accept:'application/json','user-agent':'NexOfficeBusinessDiscovery/1.1'},signal:AbortSignal.timeout(9000)});if(!response.ok)return{source:{kind:'cnpj',status:response.status===404?'not_found':'unavailable',label:'CNPJ',fetchedAt:now()},data:{cnpj}};const p:any=await response.json();const secondary=Array.isArray(p.cnaes_secundarios)?p.cnaes_secundarios.map((x:any)=>clean(x?.descricao,160)).filter(Boolean):[];return{source:{kind:'cnpj',status:'ok',label:'Cadastro público do CNPJ',fetchedAt:now()},data:{cnpj,legalName:clean(p.razao_social,180)||undefined,tradeName:clean(p.nome_fantasia,180)||undefined,businessName:clean(p.nome_fantasia||p.razao_social,180)||undefined,sector:clean(p.cnae_fiscal_descricao,180)||undefined,subsector:secondary[0]||undefined,city:clean(p.municipio,120)||undefined,state:clean(p.uf,20)||undefined,email:clean(p.email,180)||undefined,phone:clean(p.ddd_telefone_1||p.ddd_telefone_2,80)||undefined,registryStatus:clean(p.descricao_situacao_cadastral,80)||undefined}}}catch{return{source:{kind:'cnpj',status:'unavailable',label:'Cadastro público do CNPJ',fetchedAt:now()},data:{cnpj}}}}
function mergeDiscovered(parts:Discovered[]){const result:Discovered={};for(const part of parts)for(const [key,value] of Object.entries(part))if(value!==undefined&&value!==null&&value!==''&&(!Array.isArray(value)||value.length)){if(Array.isArray(value))(result as any)[key]=unique([...(Array.isArray((result as any)[key])?(result as any)[key]:[]),...value],key==='headings'?24:key==='publicReferences'?8:20);else if(!(result as any)[key])(result as any)[key]=value}return result}
function suggestions(discovered:Discovered,input:z.infer<typeof enrichSchema>){const cards:any[]=[];const hasContact=Boolean(input.whatsapp||discovered.phone),hasDigital=Boolean(input.website||input.instagram||discovered.socialLinks?.length||discovered.publicReferences?.length),offerings=discovered.productsOrServices||[];if(hasContact)cards.push({id:'bot',title:'Criar seu Bot',description:'Já temos um canal de contato para começar atendimento e captação.',target:'Assistentes IA',role:'secretary'});if(hasContact)cards.push({id:'bot-crm',title:'Bot + CRM',description:'Captar interessados, organizar contatos e acompanhar oportunidades.',target:'Assistentes IA',role:'crm'});if(hasDigital)cards.push({id:'campaign',title:'Preparar marketing',description:offerings.length?'Já encontramos sinais da sua oferta para começar conteúdo e campanhas.':'Usar seu posicionamento público para preparar conteúdo e campanhas.',target:'Assistentes IA',role:'growth'});cards.push({id:'charge',title:'Organizar cobranças',description:'Definir como você recebe e acompanhar vencimentos.',target:'Financeiro'});cards.push({id:'day',title:'Organizar o dia',description:'Agenda, tarefas e prioridades no mesmo lugar.',target:'Operação'});return cards.slice(0,5)}

export async function registerBusinessOnboardingRoutes(app:FastifyInstance){
  app.get('/v1/onboarding/business',async req=>{const ctx=await workspaceContext(req,'workspace.read');const profile=await getBusinessProfile(ctx.workspaceId),metadata=asObject(profile.metadata);return{workspace:{id:ctx.workspaceId,name:ctx.workspaceName},profile,onboarding:asObject(metadata.onboarding),completed:Boolean(asObject(metadata.onboarding).completedAt)}});
  app.post('/v1/onboarding/business/enrich',async req=>{const ctx=await workspaceContext(req,'workspace.read'),input=enrichSchema.parse(req.body||{}),tasks:Promise<ScanResult>[]=[];if(input.cnpj)tasks.push(scanCnpj(input.cnpj));if(input.website)tasks.push(scanPublicPage(input.website,'website'));if(input.instagram)tasks.push(scanPublicPage(input.instagram,'social'));for(const url of input.socialUrls.filter(Boolean).slice(0,4))tasks.push(scanPublicPage(url,'social'));if(!input.website&&(input.businessName||input.instagram))tasks.push(searchPublicWeb(input));const results=await Promise.all(tasks),discovered=mergeDiscovered(results.map(r=>r.data));if(input.businessName&&!discovered.businessName)discovered.businessName=input.businessName;if(input.whatsapp&&!discovered.phone)discovered.phone=input.whatsapp;const needsConfirmation:string[]=[];if(discovered.sector)needsConfirmation.push('atividade principal');if(discovered.productsOrServices?.length)needsConfirmation.push('principais produtos ou serviços');if(discovered.description)needsConfirmation.push('descrição do negócio');if(discovered.publicReferences?.length)needsConfirmation.push('referências públicas encontradas');const existingProfile=await getBusinessProfile(ctx.workspaceId);return{discovered,sources:results.map(r=>r.source),needsConfirmation:unique(needsConfirmation,10),suggestions:suggestions(discovered,input),existingProfile,principles:{publicSourcesOnly:true,publicSearchFallback:true,inferencesNeedConfirmation:true,nothingPublished:true,externalActions:false}}});
  app.put('/v1/onboarding/business/confirm',async req=>{const ctx=await workspaceContext(req,'workspace.read'),input=confirmSchema.parse(req.body||{}),before=await getBusinessProfile(ctx.workspaceId),currentMeta=asObject(before.metadata),supplied=asObject(input.metadata),merged=deepMerge(currentMeta,supplied);merged.onboarding={...asObject(currentMeta.onboarding),...asObject(supplied.onboarding),version:'business-v1',updatedAt:now(),...(input.complete?{completedAt:now()}:{})};const updated=await upsertBusinessProfile(ctx.workspaceId,{sector:input.sector,subsector:input.subsector,revenueModel:input.revenueModel,sellsProducts:input.sellsProducts,sellsServices:input.sellsServices,recurringRevenue:input.recurringRevenue,usesAgenda:input.usesAgenda,usesInventory:input.usesInventory,usesContracts:input.usesContracts,employeeCount:input.employeeCount,activeCustomersEstimate:input.activeCustomersEstimate,primarySalesChannel:input.primarySalesChannel,seasonality:input.seasonality,mainDependency:input.mainDependency,notes:input.notes,metadata:merged});await auditLog(ctx,'business.onboarding.confirmed','workspace',ctx.workspaceId,before,updated,{version:'business-v1',completed:input.complete,externalEffect:false});return{profile:updated,completed:input.complete}});
}
