import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {ApiError,workspaceContext} from './auth.js';
import {query} from './db.js';
import {advanceRecurrence,auditLog,emitBusinessEvent,financeSummary} from './events.js';

const uuid=z.string().uuid();
const ledgerSchema=z.object({contactId:uuid.optional().nullable(),accountId:uuid.optional().nullable(),direction:z.enum(['income','expense']),category:z.string().min(1),description:z.string().min(1),amountMinor:z.number().int().positive(),currency:z.string().length(3).default('BRL'),status:z.enum(['planned','open','paid','cancelled','overdue']).default('open'),dueAt:z.string().datetime().optional().nullable(),paidAt:z.string().datetime().optional().nullable(),recurrenceKey:z.string().optional().nullable(),externalRef:z.string().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});

export async function registerFinanceRoutes(app:FastifyInstance){
  app.get('/v1/finance/accounts',async req=>{const ctx=await workspaceContext(req,'finance.read');return query<any>(`select * from finance_accounts where workspace_id=$1 order by active desc,name`,[ctx.workspaceId])});
  app.post('/v1/finance/accounts',async req=>{const ctx=await workspaceContext(req,'finance.write'),input=z.object({name:z.string().min(1),kind:z.enum(['cash','bank','wallet','receivable','payable','other']).default('bank'),openingBalanceMinor:z.number().int().default(0),currency:z.string().length(3).default('BRL')}).parse(req.body);const rows=await query<any>(`insert into finance_accounts(workspace_id,name,kind,opening_balance_minor,currency) values($1,$2,$3,$4,$5) returning *`,[ctx.workspaceId,input.name,input.kind,input.openingBalanceMinor,input.currency]);await auditLog(ctx,'finance.account.created','finance_account',rows[0].id,null,rows[0]);return rows[0]});
  app.get('/v1/ledger',async req=>{const ctx=await workspaceContext(req,'finance.read'),q=req.query as any;return query<any>(`select l.*,c.name contact_name,a.name account_name from ledger_entries l left join crm_contacts c on c.id=l.contact_id left join finance_accounts a on a.id=l.account_id where l.workspace_id=$1 and ($2='' or l.status::text=$2) and ($3='' or l.direction::text=$3) order by coalesce(l.due_at,l.created_at) desc limit 1000`,[ctx.workspaceId,String(q?.status||''),String(q?.direction||'')])});
  app.post('/v1/ledger',async req=>{const ctx=await workspaceContext(req,'finance.write'),input=ledgerSchema.parse(req.body);const rows=await query<any>(`insert into ledger_entries(workspace_id,contact_id,account_id,direction,category,description,amount_minor,currency,status,due_at,paid_at,recurrence_key,external_ref,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *`,[ctx.workspaceId,input.contactId||null,input.accountId||null,input.direction,input.category,input.description,input.amountMinor,input.currency,input.status,input.dueAt||null,input.paidAt||null,input.recurrenceKey||null,input.externalRef||null,JSON.stringify(input.metadata)]);await auditLog(ctx,'ledger.created','ledger_entry',rows[0].id,null,rows[0]);await emitBusinessEvent(ctx.workspaceId,'finance.entry_created','nexoffice.erp','ledger_entry',rows[0].id,{direction:input.direction,category:input.category,amountMinor:input.amountMinor,status:input.status,dueAt:input.dueAt||null});if(input.status==='overdue')await emitBusinessEvent(ctx.workspaceId,'payment.overdue','nexoffice.erp','ledger_entry',rows[0].id,{description:input.description,amountMinor:input.amountMinor});if(input.status==='paid')await emitBusinessEvent(ctx.workspaceId,'payment.received','nexoffice.erp','ledger_entry',rows[0].id,{description:input.description,amountMinor:input.amountMinor});return rows[0]});
  app.patch('/v1/ledger/:id',async req=>{const ctx=await workspaceContext(req,'finance.write'),id=uuid.parse((req.params as any).id),input=ledgerSchema.partial().parse(req.body),before=(await query<any>(`select * from ledger_entries where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Lançamento não encontrado.');const status=input.status??before.status,paidAt=status==='paid'?(input.paidAt||before.paid_at||new Date().toISOString()):(input.paidAt===undefined?before.paid_at:input.paidAt);const rows=await query<any>(`update ledger_entries set contact_id=$3,account_id=$4,direction=$5,category=$6,description=$7,amount_minor=$8,currency=$9,status=$10,due_at=$11,paid_at=$12,recurrence_key=$13,external_ref=$14,metadata=$15,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.accountId===undefined?before.account_id:input.accountId,input.direction??before.direction,input.category??before.category,input.description??before.description,input.amountMinor??Number(before.amount_minor),input.currency??before.currency,status,input.dueAt===undefined?before.due_at:input.dueAt,paidAt,input.recurrenceKey===undefined?before.recurrence_key:input.recurrenceKey,input.externalRef===undefined?before.external_ref:input.externalRef,JSON.stringify(input.metadata??before.metadata)]);await auditLog(ctx,'ledger.updated','ledger_entry',id,before,rows[0]);if(status!==before.status)await emitBusinessEvent(ctx.workspaceId,'finance.entry_status_changed','nexoffice.erp','ledger_entry',id,{description:rows[0].description,amountMinor:Number(rows[0].amount_minor),from:before.status,to:status});if(status==='paid'&&before.status!=='paid')await emitBusinessEvent(ctx.workspaceId,'payment.received','nexoffice.erp','ledger_entry',id,{description:rows[0].description,amountMinor:Number(rows[0].amount_minor)});if(status==='overdue'&&before.status!=='overdue')await emitBusinessEvent(ctx.workspaceId,'payment.overdue','nexoffice.erp','ledger_entry',id,{description:rows[0].description,amountMinor:Number(rows[0].amount_minor)});return rows[0]});
  app.get('/v1/finance/summary',async req=>{const ctx=await workspaceContext(req,'finance.read');return financeSummary(ctx.workspaceId)});
  app.get('/v1/finance/cashflow',async req=>{const ctx=await workspaceContext(req,'finance.read'),months=Math.min(24,Math.max(1,Number((req.query as any)?.months||6)));return query<any>(`select date_trunc('month',coalesce(paid_at,due_at,created_at)) month,coalesce(sum(amount_minor) filter(where direction='income' and status<>'cancelled'),0)::bigint income_minor,coalesce(sum(amount_minor) filter(where direction='expense' and status<>'cancelled'),0)::bigint expense_minor,coalesce(sum(amount_minor) filter(where direction='income' and status in ('open','overdue','planned')),0)::bigint receivable_minor,coalesce(sum(amount_minor) filter(where direction='expense' and status in ('open','overdue','planned')),0)::bigint payable_minor from ledger_entries where workspace_id=$1 and coalesce(paid_at,due_at,created_at)>=date_trunc('month',now())-($2::text||' months')::interval group by 1 order by 1`,[ctx.workspaceId,String(months)])});
  app.get('/v1/recurring-rules',async req=>{const ctx=await workspaceContext(req,'finance.read');return query<any>(`select * from recurring_rules where workspace_id=$1 order by active desc,next_run_at`,[ctx.workspaceId])});
  app.post('/v1/recurring-rules',async req=>{const ctx=await workspaceContext(req,'finance.write'),input=z.object({contactId:uuid.optional().nullable(),accountId:uuid.optional().nullable(),direction:z.enum(['income','expense']),category:z.string().min(1),description:z.string().min(1),amountMinor:z.number().int().positive(),currency:z.string().length(3).default('BRL'),frequency:z.enum(['weekly','monthly','yearly']),intervalCount:z.number().int().positive().default(1),nextRunAt:z.string().datetime(),endsAt:z.string().datetime().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const rows=await query<any>(`insert into recurring_rules(workspace_id,contact_id,account_id,direction,category,description,amount_minor,currency,frequency,interval_count,next_run_at,ends_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning *`,[ctx.workspaceId,input.contactId||null,input.accountId||null,input.direction,input.category,input.description,input.amountMinor,input.currency,input.frequency,input.intervalCount,input.nextRunAt,input.endsAt||null,JSON.stringify(input.metadata)]);await auditLog(ctx,'recurrence.created','recurring_rule',rows[0].id,null,rows[0]);await emitBusinessEvent(ctx.workspaceId,'recurrence.created','nexoffice.erp','recurring_rule',rows[0].id,{direction:input.direction,amountMinor:input.amountMinor,frequency:input.frequency,intervalCount:input.intervalCount});return rows[0]});
  app.post('/v1/recurring-rules/run',async req=>{const ctx=await workspaceContext(req,'finance.write'),horizon=z.object({days:z.number().int().min(0).max(90).default(30)}).parse(req.body||{}).days,until=new Date(Date.now()+horizon*86400000),rules=await query<any>(`select * from recurring_rules where workspace_id=$1 and active=true and next_run_at<=$2 and (ends_at is null or next_run_at<=ends_at) order by next_run_at limit 200`,[ctx.workspaceId,until.toISOString()]);let created=0;for(const rule of rules){let next=new Date(rule.next_run_at),safety=0;while(next<=until&&(!rule.ends_at||next<=new Date(rule.ends_at))&&safety++<24){const key=`recurring:${rule.id}:${next.toISOString()}`;const insert=await query<any>(`insert into ledger_entries(workspace_id,contact_id,account_id,direction,category,description,amount_minor,currency,status,due_at,recurrence_key,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,'open',$9,$10,$11) on conflict do nothing returning id`,[ctx.workspaceId,rule.contact_id,rule.account_id,rule.direction,rule.category,rule.description,rule.amount_minor,rule.currency,next.toISOString(),key,JSON.stringify({...rule.metadata,recurringRuleId:rule.id})]);created+=insert.length;next=advanceRecurrence(next,rule.frequency,Number(rule.interval_count))}await query(`update recurring_rules set next_run_at=$3,updated_at=now(),active=case when ends_at is not null and $3>ends_at then false else active end where id=$1 and workspace_id=$2`,[rule.id,ctx.workspaceId,next.toISOString()])}await auditLog(ctx,'recurrence.run','workspace',ctx.workspaceId,null,{created,horizonDays:horizon});return {created,processedRules:rules.length}});
}
