import type {FastifyInstance} from 'fastify';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {ApiError,authenticate,hashOpaqueToken,hashPassword,issueSession,newInviteToken,revokeSession,slugify,verifyPassword,workspaceContext} from './auth.js';
import {query,transaction} from './db.js';
import {auditLog} from './events.js';

export async function registerAuthRoutes(app:FastifyInstance){
  app.post('/v1/auth/register',async req=>{
    const input=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),businessName:z.string().min(2).optional(),slug:z.string().regex(/^[a-z0-9-]+$/).optional(),vertical:z.enum(['general','legal','health','condo','commerce']).default('general'),inviteToken:z.string().optional()}).parse(req.body);
    const email=input.email.trim().toLowerCase();
    if((await query<any>(`select id from users where lower(email)=lower($1) limit 1`,[email])).length)throw new ApiError(409,'email_exists','Este e-mail já possui conta.');
    const userId=randomUUID(),passwordHash=await hashPassword(input.password);let workspaceId='',workspaceName='';
    await transaction(async client=>{
      await client.query(`insert into users(id,name,email,password_hash) values($1,$2,$3,$4)`,[userId,input.name.trim(),email,passwordHash]);
      if(input.inviteToken){
        const invitation=await client.query(`select i.*,w.name workspace_name from workspace_invites i join workspaces w on w.id=i.workspace_id where i.token_hash=$1 and i.status='pending' and i.expires_at>now() for update`,[hashOpaqueToken(input.inviteToken)]);
        if(!invitation.rows.length)throw new ApiError(400,'invalid_invite','Convite inválido ou expirado.');
        if(String(invitation.rows[0].email).toLowerCase()!==email)throw new ApiError(400,'invite_email_mismatch','O convite pertence a outro e-mail.');
        workspaceId=invitation.rows[0].workspace_id;workspaceName=invitation.rows[0].workspace_name;
        await client.query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,$3,$4) on conflict(workspace_id,user_id) do update set active=true,role=excluded.role,permissions=excluded.permissions`,[workspaceId,userId,invitation.rows[0].role,invitation.rows[0].permissions||[]]);
        await client.query(`update workspace_invites set status='accepted',accepted_by=$2,accepted_at=now() where id=$1`,[invitation.rows[0].id,userId]);
      }else{
        if(!input.businessName)throw new ApiError(400,'business_name_required','Informe o nome do negócio.');
        let candidate=input.slug||slugify(input.businessName);if((await client.query(`select 1 from workspaces where slug=$1`,[candidate])).rows.length)candidate=`${candidate}-${Math.random().toString(36).slice(2,6)}`;
        const workspace=await client.query(`insert into workspaces(name,slug,vertical,status,modules) values($1,$2,$3,'active',$4) returning id,name`,[input.businessName.trim(),candidate,input.vertical,['crm','agenda','tasks','erp','collections','documents','service','command-center','agents','growth','usage']]);
        workspaceId=workspace.rows[0].id;workspaceName=workspace.rows[0].name;
        await client.query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,'owner',$3)`,[workspaceId,userId,['*']]);
        await client.query(`insert into workspace_origins(workspace_id,source_product,mode) values($1,'nexoffice','standalone') on conflict do nothing`,[workspaceId]);
        await client.query(`insert into finance_accounts(workspace_id,name,kind) values($1,'Conta principal','bank') on conflict do nothing`,[workspaceId]);
        for(const capability of ['core.crm','core.agenda','core.erp','core.command-center'])await client.query(`insert into entitlements(workspace_id,capability,status,source) values($1,$2,'active','nexoffice') on conflict do nothing`,[workspaceId,capability]);
      }
    });
    const session=await issueSession(userId);return {token:session.token,expiresAt:session.expiresAt,user:{id:userId,name:input.name,email},workspace:{id:workspaceId,name:workspaceName}};
  });
  app.post('/v1/auth/login',async req=>{const input=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body),email=input.email.trim().toLowerCase();const rows=await query<any>(`select id,name,email,password_hash,status from users where lower(email)=lower($1) limit 1`,[email]);if(!rows.length||rows[0].status!=='active'||!(await verifyPassword(input.password,rows[0].password_hash)))throw new ApiError(401,'invalid_credentials','E-mail ou senha incorretos.');const session=await issueSession(rows[0].id);return {token:session.token,expiresAt:session.expiresAt,user:{id:rows[0].id,name:rows[0].name,email:rows[0].email}}});
  app.post('/v1/auth/logout',async req=>{await revokeSession(req);return {ok:true}});
  app.get('/v1/auth/me',async req=>{const user=await authenticate(req);const memberships=await query<any>(`select w.id,w.name,w.slug,w.vertical,w.plan,w.status,w.timezone,w.currency,m.role,m.permissions from workspace_members m join workspaces w on w.id=m.workspace_id where m.user_id=$1 and m.active=true order by w.created_at`,[user.id]);return {user,workspaces:memberships}});
  app.get('/v1/workspaces',async req=>{const user=await authenticate(req);return query<any>(`select w.*,m.role,m.permissions from workspace_members m join workspaces w on w.id=m.workspace_id where m.user_id=$1 and m.active=true order by w.created_at`,[user.id])});
  app.post('/v1/workspaces',async req=>{const user=await authenticate(req);const input=z.object({name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/).optional(),vertical:z.enum(['general','legal','health','condo','commerce']).default('general')}).parse(req.body);let candidate=input.slug||slugify(input.name);if((await query<any>(`select 1 from workspaces where slug=$1`,[candidate])).length)candidate=`${candidate}-${Math.random().toString(36).slice(2,6)}`;const rows=await query<any>(`insert into workspaces(name,slug,vertical,status,modules) values($1,$2,$3,'active',$4) returning *`,[input.name,candidate,input.vertical,['crm','agenda','tasks','erp','collections','documents','service','command-center','agents','growth','usage']]);await query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,'owner',$3)`,[rows[0].id,user.id,['*']]);await query(`insert into workspace_origins(workspace_id,source_product,mode) values($1,'nexoffice','standalone') on conflict do nothing`,[rows[0].id]);await query(`insert into finance_accounts(workspace_id,name,kind) values($1,'Conta principal','bank') on conflict do nothing`,[rows[0].id]);return rows[0]});
  app.get('/v1/workspace',async req=>{const ctx=await workspaceContext(req,'workspace.read');return (await query<any>(`select * from workspaces where id=$1`,[ctx.workspaceId]))[0]});
  app.patch('/v1/workspace',async req=>{const ctx=await workspaceContext(req,'workspace.manage');const input=z.object({name:z.string().min(2).optional(),timezone:z.string().optional(),currency:z.string().length(3).optional(),settings:z.record(z.string(),z.unknown()).optional()}).parse(req.body);const before=(await query<any>(`select * from workspaces where id=$1`,[ctx.workspaceId]))[0];const after=(await query<any>(`update workspaces set name=$2,timezone=$3,currency=$4,settings=$5,updated_at=now() where id=$1 returning *`,[ctx.workspaceId,input.name??before.name,input.timezone??before.timezone,input.currency??before.currency,JSON.stringify(input.settings??before.settings)]))[0];await auditLog(ctx,'workspace.updated','workspace',ctx.workspaceId,before,after);return after});
  app.get('/v1/members',async req=>{const ctx=await workspaceContext(req,'workspace.read');return query<any>(`select m.id,m.user_id,m.role,m.permissions,m.active,m.created_at,u.name,u.email from workspace_members m join users u on u.id=m.user_id where m.workspace_id=$1 order by case m.role when 'owner' then 1 when 'admin' then 2 else 3 end,u.name`,[ctx.workspaceId])});
  app.post('/v1/members/invite',async req=>{const ctx=await workspaceContext(req,'members.manage');const input=z.object({email:z.string().email(),role:z.enum(['admin','member','viewer']).default('member'),permissions:z.array(z.string()).default([])}).parse(req.body),email=input.email.toLowerCase();if((await query<any>(`select m.id from workspace_members m join users u on u.id=m.user_id where m.workspace_id=$1 and lower(u.email)=lower($2) and m.active=true`,[ctx.workspaceId,email])).length)throw new ApiError(409,'already_member','Este usuário já faz parte do workspace.');await query(`update workspace_invites set status='revoked' where workspace_id=$1 and lower(email)=lower($2) and status='pending'`,[ctx.workspaceId,email]);const invite=newInviteToken();const rows=await query<any>(`insert into workspace_invites(workspace_id,email,role,permissions,token_hash,invited_by) values($1,$2,$3,$4,$5,$6) returning id,email,role,expires_at`,[ctx.workspaceId,email,input.role,input.permissions,invite.hash,ctx.user.id]);await auditLog(ctx,'member.invited','workspace_invite',rows[0].id,null,{email,role:input.role});return {...rows[0],inviteToken:invite.token,inviteUrl:`${String(process.env.WEB_APP_URL||'').replace(/\/$/,'')}/?invite=${encodeURIComponent(invite.token)}`}});
  app.post('/v1/invites/accept',async req=>{const user=await authenticate(req),input=z.object({token:z.string().min(10)}).parse(req.body),invite=(await query<any>(`select * from workspace_invites where token_hash=$1 and status='pending' and expires_at>now() limit 1`,[hashOpaqueToken(input.token)]))[0];if(!invite)throw new ApiError(400,'invalid_invite','Convite inválido ou expirado.');if(String(invite.email).toLowerCase()!==user.email.toLowerCase())throw new ApiError(400,'invite_email_mismatch','Entre com o e-mail que recebeu o convite.');await transaction(async client=>{await client.query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,$3,$4) on conflict(workspace_id,user_id) do update set active=true,role=excluded.role,permissions=excluded.permissions`,[invite.workspace_id,user.id,invite.role,invite.permissions||[]]);await client.query(`update workspace_invites set status='accepted',accepted_by=$2,accepted_at=now() where id=$1`,[invite.id,user.id])});return {ok:true,workspaceId:invite.workspace_id}});
  app.patch('/v1/members/:id',async req=>{const ctx=await workspaceContext(req,'members.manage'),id=z.string().uuid().parse((req.params as any).id),input=z.object({role:z.enum(['admin','member','viewer']).optional(),permissions:z.array(z.string()).optional(),active:z.boolean().optional()}).parse(req.body),current=(await query<any>(`select * from workspace_members where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!current)throw new ApiError(404,'not_found','Membro não encontrado.');if(current.role==='owner')throw new ApiError(400,'owner_protected','O proprietário não pode ser alterado por esta rota.');const rows=await query<any>(`update workspace_members set role=$3,permissions=$4,active=$5 where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.role??current.role,input.permissions??current.permissions,input.active??current.active]);await auditLog(ctx,'member.updated','workspace_member',id,current,rows[0]);return rows[0]});
}
