import 'dotenv/config';
import Fastify, {type FastifyRequest} from 'fastify';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {BusinessEvent} from '@nexoffice/domain';
import {db, query, transaction} from './db.js';
import {processBusinessEvent} from './orchestrator.js';
import {ApiError, authenticate, hashOpaqueToken, hashPassword, issueSession, newInviteToken, revokeSession, slugify, verifyPassword, workspaceContext} from './auth.js';

const app = Fastify({logger: true});
const port = Number(process.env.PORT || 4000);
const allowedOrigins = String(process.env.ALLOWED_ORIGINS || '*').split(',').map(x=>x.trim()).filter(Boolean);
const uuid = z.string().uuid();

app.addHook('onSend', async (req, reply, payload) => {
  const origin = String(req.headers.origin || '');
  if (allowedOrigins.includes('*')) reply.header('access-control-allow-origin','*');
  else if (origin && allowedOrigins.includes(origin)) reply.header('access-control-allow-origin',origin);
  reply.header('access-control-allow-headers','content-type, authorization, x-workspace-id, x-nexoffice-key');
  reply.header('access-control-allow-methods','GET,POST,PATCH,PUT,DELETE,OPTIONS');
  reply.header('access-control-max-age','86400');
  return payload;
});
app.options('*', async (_req,reply)=>reply.code(204).send());

const contactSchema = z.object({
  kind:z.enum(['person','company']).default('person'), name:z.string().min(1), email:z.string().email().optional().nullable(),
  phone:z.string().optional().nullable(), companyName:z.string().optional().nullable(), documentNumber:z.string().optional().nullable(),
  source:z.string().optional().nullable(), tags:z.array(z.string()).default([]), customFields:z.record(z.string(),z.unknown()).default({})
});
const dealSchema = z.object({
  contactId:uuid.optional().nullable(), title:z.string().min(1), stage:z.enum(['lead','qualified','meeting','proposal','won','lost']).default('lead'),
  valueMinor:z.number().int().nonnegative().default(0), currency:z.string().length(3).default('BRL'), ownerId:uuid.optional().nullable(), source:z.string().optional().nullable(),
  nextAction:z.string().optional().nullable(), expectedCloseAt:z.string().datetime().optional().nullable(), metadata:z.record(z.string(),z.unknown()).default({})
});
const ledgerSchema = z.object({
  contactId:uuid.optional().nullable(), accountId:uuid.optional().nullable(), direction:z.enum(['income','expense']), category:z.string().min(1), description:z.string().min(1),
  amountMinor:z.number().int().positive(), currency:z.string().length(3).default('BRL'), status:z.enum(['planned','open','paid','cancelled','overdue']).default('open'),
  dueAt:z.string().datetime().optional().nullable(), paidAt:z.string().datetime().optional().nullable(), recurrenceKey:z.string().optional().nullable(), externalRef:z.string().optional().nullable(), metadata:z.record(z.string(),z.unknown()).default({})
});
const taskSchema = z.object({contactId:uuid.optional().nullable(),dealId:uuid.optional().nullable(),title:z.string().min(1),description:z.string().optional().nullable(),status:z.enum(['todo','doing','done','cancelled']).default('todo'),priority:z.enum(['low','normal','high','critical']).default('normal'),assignedTo:uuid.optional().nullable(),dueAt:z.string().datetime().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});
const appointmentSchema = z.object({contactId:uuid.optional().nullable(),title:z.string().min(1),startsAt:z.string().datetime(),endsAt:z.string().datetime().optional().nullable(),status:z.enum(['scheduled','confirmed','completed','cancelled','no_show']).default('scheduled'),assignedTo:uuid.optional().nullable(),externalRef:z.string().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})});

app.get('/health', async()=>({status:'ok',service:'nexoffice-api',version:'0.2.0',database:Boolean(db)}));

// --- Authentication & onboarding ------------------------------------------------
app.post('/v1/auth/register', async req => {
  const input=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),businessName:z.string().min(2).optional(),slug:z.string().regex(/^[a-z0-9-]+$/).optional(),vertical:z.enum(['general','legal','health','condo','commerce']).default('general'),inviteToken:z.string().optional()}).parse(req.body);
  const email=input.email.trim().toLowerCase();
  const exists=await query<any>(`select id from users where lower(email)=lower($1) limit 1`,[email]);
  if(exists.length)throw new ApiError(409,'email_exists','Este e-mail já possui conta.');
  const passwordHash=await hashPassword(input.password);
  const userId=randomUUID();
  let workspaceId='';
  let workspaceName='';
  await transaction(async client=>{
    await client.query(`insert into users(id,name,email,password_hash) values($1,$2,$3,$4)`,[userId,input.name.trim(),email,passwordHash]);
    if(input.inviteToken){
      const tokenHash=hashOpaqueToken(input.inviteToken);
      const invitation=await client.query(`select i.*,w.name workspace_name from workspace_invites i join workspaces w on w.id=i.workspace_id where i.token_hash=$1 and i.status='pending' and i.expires_at>now() for update`,[tokenHash]);
      if(!invitation.rows.length)throw new ApiError(400,'invalid_invite','Convite inválido ou expirado.');
      if(String(invitation.rows[0].email).toLowerCase()!==email)throw new ApiError(400,'invite_email_mismatch','O convite pertence a outro e-mail.');
      workspaceId=invitation.rows[0].workspace_id; workspaceName=invitation.rows[0].workspace_name;
      await client.query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,$3,$4) on conflict(workspace_id,user_id) do update set active=true,role=excluded.role,permissions=excluded.permissions`,[workspaceId,userId,invitation.rows[0].role,invitation.rows[0].permissions||[]]);
      await client.query(`update workspace_invites set status='accepted',accepted_by=$2,accepted_at=now() where id=$1`,[invitation.rows[0].id,userId]);
    }else{
      if(!input.businessName)throw new ApiError(400,'business_name_required','Informe o nome do negócio.');
      let candidate=input.slug||slugify(input.businessName); const collision=await client.query(`select 1 from workspaces where slug=$1`,[candidate]);
      if(collision.rows.length)candidate=`${candidate}-${Math.random().toString(36).slice(2,6)}`;
      const workspace=await client.query(`insert into workspaces(name,slug,vertical,status,modules) values($1,$2,$3,'active',$4) returning id,name`,[input.businessName.trim(),candidate,input.vertical,['crm','agenda','tasks','erp','collections','documents','service','command-center','agents','growth','usage']]);
      workspaceId=workspace.rows[0].id; workspaceName=workspace.rows[0].name;
      await client.query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,'owner',$3)`,[workspaceId,userId,['*']]);
      await client.query(`insert into workspace_origins(workspace_id,source_product,mode) values($1,'nexoffice','standalone') on conflict do nothing`,[workspaceId]);
      await client.query(`insert into finance_accounts(workspace_id,name,kind) values($1,'Conta principal','bank') on conflict do nothing`,[workspaceId]);
      for(const capability of ['core.crm','core.agenda','core.erp','core.command-center'])await client.query(`insert into entitlements(workspace_id,capability,status,source) values($1,$2,'active','nexoffice') on conflict do nothing`,[workspaceId,capability]);
    }
  });
  const session=await issueSession(userId);
  return {token:session.token,expiresAt:session.expiresAt,user:{id:userId,name:input.name,email},workspace:{id:workspaceId,name:workspaceName}};
});

app.post('/v1/auth/login', async req=>{
  const input=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body); const email=input.email.trim().toLowerCase();
  const rows=await query<any>(`select id,name,email,password_hash,status from users where lower(email)=lower($1) limit 1`,[email]);
  if(!rows.length||rows[0].status!=='active'||!(await verifyPassword(input.password,rows[0].password_hash)))throw new ApiError(401,'invalid_credentials','E-mail ou senha incorretos.');
  const session=await issueSession(rows[0].id); return {token:session.token,expiresAt:session.expiresAt,user:{id:rows[0].id,name:rows[0].name,email:rows[0].email}};
});
app.post('/v1/auth/logout',async req=>{await revokeSession(req);return {ok:true}});
app.get('/v1/auth/me',async req=>{
  const user=await authenticate(req); const memberships=await query<any>(`select w.id,w.name,w.slug,w.vertical,w.plan,w.status,w.timezone,w.currency,m.role,m.permissions from workspace_members m join workspaces w on w.id=m.workspace_id where m.user_id=$1 and m.active=true order by w.created_at`,[user.id]);
  return {user,workspaces:memberships};
});

// --- Workspaces, members and invitations ---------------------------------------
app.get('/v1/workspaces',async req=>{const user=await authenticate(req);return query<any>(`select w.*,m.role,m.permissions from workspace_members m join workspaces w on w.id=m.workspace_id where m.user_id=$1 and m.active=true order by w.created_at`,[user.id])});
app.post('/v1/workspaces',async req=>{
  const user=await authenticate(req); const input=z.object({name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/).optional(),vertical:z.enum(['general','legal','health','condo','commerce']).default('general')}).parse(req.body);
  let candidate=input.slug||slugify(input.name);if((await query<any>(`select 1 from workspaces where slug=$1`,[candidate])).length)candidate=`${candidate}-${Math.random().toString(36).slice(2,6)}`;
  const rows=await query<any>(`insert into workspaces(name,slug,vertical,status,modules) values($1,$2,$3,'active',$4) returning *`,[input.name,candidate,input.vertical,['crm','agenda','tasks','erp','collections','documents','service','command-center','agents','growth','usage']]);
  await query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,'owner',$3)`,[rows[0].id,user.id,['*']]);
  await query(`insert into workspace_origins(workspace_id,source_product,mode) values($1,'nexoffice','standalone') on conflict do nothing`,[rows[0].id]);
  await query(`insert into finance_accounts(workspace_id,name,kind) values($1,'Conta principal','bank') on conflict do nothing`,[rows[0].id]); return rows[0];
});
app.get('/v1/workspace',async req=>{const ctx=await workspaceContext(req,'workspace.read');const rows=await query<any>(`select * from workspaces where id=$1`,[ctx.workspaceId]);return rows[0]});
app.patch('/v1/workspace',async req=>{
  const ctx=await workspaceContext(req,'workspace.manage');const input=z.object({name:z.string().min(2).optional(),timezone:z.string().optional(),currency:z.string().length(3).optional(),settings:z.record(z.string(),z.unknown()).optional()}).parse(req.body);
  const before=(await query<any>(`select * from workspaces where id=$1`,[ctx.workspaceId]))[0];
  const after=(await query<any>(`update workspaces set name=$2,timezone=$3,currency=$4,settings=$5,updated_at=now() where id=$1 returning *`,[ctx.workspaceId,input.name??before.name,input.timezone??before.timezone,input.currency??before.currency,JSON.stringify(input.settings??before.settings)]))[0];
  await audit(ctx,'workspace.updated','workspace',ctx.workspaceId,before,after);return after;
});
app.get('/v1/members',async req=>{const ctx=await workspaceContext(req,'workspace.read');return query<any>(`select m.id,m.user_id,m.role,m.permissions,m.active,m.created_at,u.name,u.email from workspace_members m join users u on u.id=m.user_id where m.workspace_id=$1 order by case m.role when 'owner' then 1 when 'admin' then 2 else 3 end,u.name`,[ctx.workspaceId])});
app.post('/v1/members/invite',async req=>{
  const ctx=await workspaceContext(req,'members.manage');const input=z.object({email:z.string().email(),role:z.enum(['admin','member','viewer']).default('member'),permissions:z.array(z.string()).default([])}).parse(req.body);const email=input.email.toLowerCase();
  const existing=await query<any>(`select m.id from workspace_members m join users u on u.id=m.user_id where m.workspace_id=$1 and lower(u.email)=lower($2) and m.active=true`,[ctx.workspaceId,email]);if(existing.length)throw new ApiError(409,'already_member','Este usuário já faz parte do workspace.');
  await query(`update workspace_invites set status='revoked' where workspace_id=$1 and lower(email)=lower($2) and status='pending'`,[ctx.workspaceId,email]);
  const invite=newInviteToken();const rows=await query<any>(`insert into workspace_invites(workspace_id,email,role,permissions,token_hash,invited_by) values($1,$2,$3,$4,$5,$6) returning id,email,role,expires_at`,[ctx.workspaceId,email,input.role,input.permissions,invite.hash,ctx.user.id]);
  await audit(ctx,'member.invited','workspace_invite',rows[0].id,null,{email,role:input.role});
  return {...rows[0],inviteToken:invite.token,inviteUrl:`${String(process.env.WEB_APP_URL||'').replace(/\/$/,'')}/?invite=${encodeURIComponent(invite.token)}`};
});
app.post('/v1/invites/accept',async req=>{
  const user=await authenticate(req);const input=z.object({token:z.string().min(10)}).parse(req.body);const tokenHash=hashOpaqueToken(input.token);
  const invite=(await query<any>(`select * from workspace_invites where token_hash=$1 and status='pending' and expires_at>now() limit 1`,[tokenHash]))[0];if(!invite)throw new ApiError(400,'invalid_invite','Convite inválido ou expirado.');if(String(invite.email).toLowerCase()!==user.email.toLowerCase())throw new ApiError(400,'invite_email_mismatch','Entre com o e-mail que recebeu o convite.');
  await transaction(async client=>{await client.query(`insert into workspace_members(workspace_id,user_id,role,permissions) values($1,$2,$3,$4) on conflict(workspace_id,user_id) do update set active=true,role=excluded.role,permissions=excluded.permissions`,[invite.workspace_id,user.id,invite.role,invite.permissions||[]]);await client.query(`update workspace_invites set status='accepted',accepted_by=$2,accepted_at=now() where id=$1`,[invite.id,user.id])});return {ok:true,workspaceId:invite.workspace_id};
});
app.patch('/v1/members/:id',async req=>{
  const ctx=await workspaceContext(req,'members.manage');const id=uuid.parse((req.params as any).id);const input=z.object({role:z.enum(['admin','member','viewer']).optional(),permissions:z.array(z.string()).optional(),active:z.boolean().optional()}).parse(req.body);
  const current=(await query<any>(`select * from workspace_members where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!current)throw new ApiError(404,'not_found','Membro não encontrado.');if(current.role==='owner')throw new ApiError(400,'owner_protected','O proprietário não pode ser alterado por esta rota.');
  const rows=await query<any>(`update workspace_members set role=$3,permissions=$4,active=$5 where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.role??current.role,input.permissions??current.permissions,input.active??current.active]);await audit(ctx,'member.updated','workspace_member',id,current,rows[0]);return rows[0];
});

// --- CRM -----------------------------------------------------------------------
app.get('/v1/crm/contacts',async req=>{
  const ctx=await workspaceContext(req,'crm.read');const q=String((req.query as any)?.q||'').trim();
  return query<any>(`select * from crm_contacts where workspace_id=$1 and ($2='' or name ilike '%'||$2||'%' or coalesce(email,'') ilike '%'||$2||'%' or coalesce(phone,'') ilike '%'||$2||'%' or coalesce(company_name,'') ilike '%'||$2||'%') order by updated_at desc limit 500`,[ctx.workspaceId,q]);
});
app.post('/v1/crm/contacts',async req=>{
  const ctx=await workspaceContext(req,'crm.write');const input=contactSchema.parse(req.body);const rows=await query<any>(`insert into crm_contacts(workspace_id,kind,name,email,phone,company_name,document_number,source,tags,custom_fields) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[ctx.workspaceId,input.kind,input.name,input.email||null,input.phone||null,input.companyName||null,input.documentNumber||null,input.source||null,input.tags,JSON.stringify(input.customFields)]);
  await audit(ctx,'crm.contact.created','crm_contact',rows[0].id,null,rows[0]);await emit(ctx.workspaceId,'lead.created','nexoffice.crm','contact',rows[0].id,{name:input.name,source:input.source||null});return rows[0];
});
app.get('/v1/crm/contacts/:id',async req=>{
  const ctx=await workspaceContext(req,'crm.read');const id=uuid.parse((req.params as any).id);const contact=(await query<any>(`select * from crm_contacts where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!contact)throw new ApiError(404,'not_found','Contato não encontrado.');
  const [activities,deals,tasks]=await Promise.all([query<any>(`select * from crm_activities where workspace_id=$1 and contact_id=$2 order by occurred_at desc limit 200`,[ctx.workspaceId,id]),query<any>(`select * from crm_deals where workspace_id=$1 and contact_id=$2 order by updated_at desc`,[ctx.workspaceId,id]),query<any>(`select * from tasks where workspace_id=$1 and contact_id=$2 order by created_at desc`,[ctx.workspaceId,id])]);return {contact,activities,deals,tasks};
});
app.patch('/v1/crm/contacts/:id',async req=>{
  const ctx=await workspaceContext(req,'crm.write');const id=uuid.parse((req.params as any).id);const input=contactSchema.partial().parse(req.body);const before=(await query<any>(`select * from crm_contacts where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Contato não encontrado.');
  const rows=await query<any>(`update crm_contacts set kind=$3,name=$4,email=$5,phone=$6,company_name=$7,document_number=$8,source=$9,tags=$10,custom_fields=$11,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.kind??before.kind,input.name??before.name,input.email===undefined?before.email:input.email,input.phone===undefined?before.phone:input.phone,input.companyName===undefined?before.company_name:input.companyName,input.documentNumber===undefined?before.document_number:input.documentNumber,input.source===undefined?before.source:input.source,input.tags??before.tags,JSON.stringify(input.customFields??before.custom_fields)]);await audit(ctx,'crm.contact.updated','crm_contact',id,before,rows[0]);return rows[0];
});
app.get('/v1/crm/activities',async req=>{
  const ctx=await workspaceContext(req,'crm.read');const contactId=(req.query as any)?.contactId||null;const dealId=(req.query as any)?.dealId||null;return query<any>(`select a.*,c.name contact_name from crm_activities a left join crm_contacts c on c.id=a.contact_id where a.workspace_id=$1 and ($2::uuid is null or a.contact_id=$2) and ($3::uuid is null or a.deal_id=$3) order by occurred_at desc limit 500`,[ctx.workspaceId,contactId,dealId]);
});
app.post('/v1/crm/activities',async req=>{
  const ctx=await workspaceContext(req,'crm.write');const input=z.object({contactId:uuid.optional().nullable(),dealId:uuid.optional().nullable(),type:z.enum(['note','call','email','whatsapp','sms','meeting','task','system']),direction:z.enum(['inbound','outbound']).optional().nullable(),subject:z.string().optional().nullable(),body:z.string().optional().nullable(),occurredAt:z.string().datetime().optional(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const rows=await query<any>(`insert into crm_activities(workspace_id,contact_id,deal_id,type,direction,subject,body,occurred_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[ctx.workspaceId,input.contactId||null,input.dealId||null,input.type,input.direction||null,input.subject||null,input.body||null,input.occurredAt||new Date().toISOString(),JSON.stringify(input.metadata)]);await audit(ctx,'crm.activity.created','crm_activity',rows[0].id,null,{type:input.type,contactId:input.contactId});return rows[0];
});
app.get('/v1/crm/deals',async req=>{
  const ctx=await workspaceContext(req,'crm.read');const stage=String((req.query as any)?.stage||'');return query<any>(`select d.*,c.name contact_name,c.email contact_email,c.phone contact_phone from crm_deals d left join crm_contacts c on c.id=d.contact_id where d.workspace_id=$1 and ($2='' or d.stage::text=$2) order by d.updated_at desc limit 500`,[ctx.workspaceId,stage]);
});
app.post('/v1/crm/deals',async req=>{
  const ctx=await workspaceContext(req,'crm.write');const input=dealSchema.parse(req.body);const rows=await query<any>(`insert into crm_deals(workspace_id,contact_id,title,stage,value_minor,currency,owner_id,source,next_action,expected_close_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[ctx.workspaceId,input.contactId||null,input.title,input.stage,input.valueMinor,input.currency,input.ownerId||null,input.source||null,input.nextAction||null,input.expectedCloseAt||null,JSON.stringify(input.metadata)]);await audit(ctx,'crm.deal.created','crm_deal',rows[0].id,null,rows[0]);return rows[0];
});
app.patch('/v1/crm/deals/:id',async req=>{
  const ctx=await workspaceContext(req,'crm.write');const id=uuid.parse((req.params as any).id);const input=dealSchema.partial().parse(req.body);const before=(await query<any>(`select * from crm_deals where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Oportunidade não encontrada.');
  const rows=await query<any>(`update crm_deals set contact_id=$3,title=$4,stage=$5,value_minor=$6,currency=$7,owner_id=$8,source=$9,next_action=$10,expected_close_at=$11,metadata=$12,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.title??before.title,input.stage??before.stage,input.valueMinor??Number(before.value_minor),input.currency??before.currency,input.ownerId===undefined?before.owner_id:input.ownerId,input.source===undefined?before.source:input.source,input.nextAction===undefined?before.next_action:input.nextAction,input.expectedCloseAt===undefined?before.expected_close_at:input.expectedCloseAt,JSON.stringify(input.metadata??before.metadata)]);
  await audit(ctx,'crm.deal.updated','crm_deal',id,before,rows[0]);if(input.stage&&input.stage!==before.stage)await emit(ctx.workspaceId,input.stage==='won'?'deal.won':'deal.stage_changed','nexoffice.crm','deal',id,{title:rows[0].title,from:before.stage,to:input.stage,valueMinor:Number(rows[0].value_minor)});return rows[0];
});

// --- Tasks and calendar --------------------------------------------------------
app.get('/v1/tasks',async req=>{const ctx=await workspaceContext(req,'agenda.read');const status=String((req.query as any)?.status||'');return query<any>(`select t.*,c.name contact_name,d.title deal_title from tasks t left join crm_contacts c on c.id=t.contact_id left join crm_deals d on d.id=t.deal_id where t.workspace_id=$1 and ($2='' or t.status=$2) order by case t.priority when 'critical' then 1 when 'high' then 2 else 3 end,t.due_at nulls last,t.created_at desc`,[ctx.workspaceId,status])});
app.post('/v1/tasks',async req=>{const ctx=await workspaceContext(req,'agenda.write');const input=taskSchema.parse(req.body);const rows=await query<any>(`insert into tasks(workspace_id,contact_id,deal_id,title,description,status,priority,assigned_to,due_at,completed_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[ctx.workspaceId,input.contactId||null,input.dealId||null,input.title,input.description||null,input.status,input.priority,input.assignedTo||null,input.dueAt||null,input.status==='done'?new Date().toISOString():null,JSON.stringify(input.metadata)]);await audit(ctx,'task.created','task',rows[0].id,null,rows[0]);return rows[0]});
app.patch('/v1/tasks/:id',async req=>{const ctx=await workspaceContext(req,'agenda.write');const id=uuid.parse((req.params as any).id);const input=taskSchema.partial().parse(req.body);const before=(await query<any>(`select * from tasks where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Tarefa não encontrada.');const status=input.status??before.status;const rows=await query<any>(`update tasks set contact_id=$3,deal_id=$4,title=$5,description=$6,status=$7,priority=$8,assigned_to=$9,due_at=$10,completed_at=$11,metadata=$12,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.dealId===undefined?before.deal_id:input.dealId,input.title??before.title,input.description===undefined?before.description:input.description,status,input.priority??before.priority,input.assignedTo===undefined?before.assigned_to:input.assignedTo,input.dueAt===undefined?before.due_at:input.dueAt,status==='done'?(before.completed_at||new Date().toISOString()):null,JSON.stringify(input.metadata??before.metadata)]);await audit(ctx,'task.updated','task',id,before,rows[0]);return rows[0]});
app.get('/v1/appointments',async req=>{const ctx=await workspaceContext(req,'agenda.read');const from=(req.query as any)?.from||new Date(Date.now()-7*86400000).toISOString();const to=(req.query as any)?.to||new Date(Date.now()+45*86400000).toISOString();return query<any>(`select a.*,c.name contact_name from appointments a left join crm_contacts c on c.id=a.contact_id where a.workspace_id=$1 and a.starts_at between $2 and $3 order by a.starts_at`,[ctx.workspaceId,from,to])});
app.post('/v1/appointments',async req=>{const ctx=await workspaceContext(req,'agenda.write');const input=appointmentSchema.parse(req.body);const rows=await query<any>(`insert into appointments(workspace_id,contact_id,title,starts_at,ends_at,status,assigned_to,external_ref,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[ctx.workspaceId,input.contactId||null,input.title,input.startsAt,input.endsAt||null,input.status,input.assignedTo||null,input.externalRef||null,JSON.stringify(input.metadata)]);await audit(ctx,'appointment.created','appointment',rows[0].id,null,rows[0]);return rows[0]});
app.patch('/v1/appointments/:id',async req=>{const ctx=await workspaceContext(req,'agenda.write');const id=uuid.parse((req.params as any).id);const input=appointmentSchema.partial().parse(req.body);const before=(await query<any>(`select * from appointments where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Compromisso não encontrado.');const rows=await query<any>(`update appointments set contact_id=$3,title=$4,starts_at=$5,ends_at=$6,status=$7,assigned_to=$8,external_ref=$9,metadata=$10,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.title??before.title,input.startsAt??before.starts_at,input.endsAt===undefined?before.ends_at:input.endsAt,input.status??before.status,input.assignedTo===undefined?before.assigned_to:input.assignedTo,input.externalRef===undefined?before.external_ref:input.externalRef,JSON.stringify(input.metadata??before.metadata)]);await audit(ctx,'appointment.updated','appointment',id,before,rows[0]);if(input.status==='cancelled'&&before.status!=='cancelled')await emit(ctx.workspaceId,'appointment.cancelled','nexoffice.agenda','appointment',id,{title:rows[0].title,startsAt:String(rows[0].starts_at)});return rows[0]});

// --- ERP Lite / Finance --------------------------------------------------------
app.get('/v1/finance/accounts',async req=>{const ctx=await workspaceContext(req,'finance.read');return query<any>(`select * from finance_accounts where workspace_id=$1 order by active desc,name`,[ctx.workspaceId])});
app.post('/v1/finance/accounts',async req=>{const ctx=await workspaceContext(req,'finance.write');const input=z.object({name:z.string().min(1),kind:z.enum(['cash','bank','wallet','receivable','payable','other']).default('bank'),openingBalanceMinor:z.number().int().default(0),currency:z.string().length(3).default('BRL')}).parse(req.body);const rows=await query<any>(`insert into finance_accounts(workspace_id,name,kind,opening_balance_minor,currency) values($1,$2,$3,$4,$5) returning *`,[ctx.workspaceId,input.name,input.kind,input.openingBalanceMinor,input.currency]);await audit(ctx,'finance.account.created','finance_account',rows[0].id,null,rows[0]);return rows[0]});
app.get('/v1/ledger',async req=>{const ctx=await workspaceContext(req,'finance.read');const q=req.query as any;return query<any>(`select l.*,c.name contact_name,a.name account_name from ledger_entries l left join crm_contacts c on c.id=l.contact_id left join finance_accounts a on a.id=l.account_id where l.workspace_id=$1 and ($2='' or l.status::text=$2) and ($3='' or l.direction::text=$3) order by coalesce(l.due_at,l.created_at) desc limit 1000`,[ctx.workspaceId,String(q?.status||''),String(q?.direction||'')])});
app.post('/v1/ledger',async req=>{const ctx=await workspaceContext(req,'finance.write');const input=ledgerSchema.parse(req.body);const rows=await query<any>(`insert into ledger_entries(workspace_id,contact_id,account_id,direction,category,description,amount_minor,currency,status,due_at,paid_at,recurrence_key,external_ref,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *`,[ctx.workspaceId,input.contactId||null,input.accountId||null,input.direction,input.category,input.description,input.amountMinor,input.currency,input.status,input.dueAt||null,input.paidAt||null,input.recurrenceKey||null,input.externalRef||null,JSON.stringify(input.metadata)]);await audit(ctx,'ledger.created','ledger_entry',rows[0].id,null,rows[0]);if(input.status==='overdue')await emit(ctx.workspaceId,'payment.overdue','nexoffice.erp','ledger_entry',rows[0].id,{description:input.description,amountMinor:input.amountMinor});if(input.status==='paid')await emit(ctx.workspaceId,'payment.received','nexoffice.erp','ledger_entry',rows[0].id,{description:input.description,amountMinor:input.amountMinor});return rows[0]});
app.patch('/v1/ledger/:id',async req=>{const ctx=await workspaceContext(req,'finance.write');const id=uuid.parse((req.params as any).id);const input=ledgerSchema.partial().parse(req.body);const before=(await query<any>(`select * from ledger_entries where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Lançamento não encontrado.');const status=input.status??before.status;const paidAt=status==='paid'?(input.paidAt||before.paid_at||new Date().toISOString()):(input.paidAt===undefined?before.paid_at:input.paidAt);const rows=await query<any>(`update ledger_entries set contact_id=$3,account_id=$4,direction=$5,category=$6,description=$7,amount_minor=$8,currency=$9,status=$10,due_at=$11,paid_at=$12,recurrence_key=$13,external_ref=$14,metadata=$15,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,input.contactId===undefined?before.contact_id:input.contactId,input.accountId===undefined?before.account_id:input.accountId,input.direction??before.direction,input.category??before.category,input.description??before.description,input.amountMinor??Number(before.amount_minor),input.currency??before.currency,status,input.dueAt===undefined?before.due_at:input.dueAt,paidAt,input.recurrenceKey===undefined?before.recurrence_key:input.recurrenceKey,input.externalRef===undefined?before.external_ref:input.externalRef,JSON.stringify(input.metadata??before.metadata)]);await audit(ctx,'ledger.updated','ledger_entry',id,before,rows[0]);if(status==='paid'&&before.status!=='paid')await emit(ctx.workspaceId,'payment.received','nexoffice.erp','ledger_entry',id,{description:rows[0].description,amountMinor:Number(rows[0].amount_minor)});if(status==='overdue'&&before.status!=='overdue')await emit(ctx.workspaceId,'payment.overdue','nexoffice.erp','ledger_entry',id,{description:rows[0].description,amountMinor:Number(rows[0].amount_minor)});return rows[0]});
app.get('/v1/finance/summary',async req=>{const ctx=await workspaceContext(req,'finance.read');return financeSummary(ctx.workspaceId)});
app.get('/v1/finance/cashflow',async req=>{const ctx=await workspaceContext(req,'finance.read');const months=Math.min(24,Math.max(1,Number((req.query as any)?.months||6)));return query<any>(`select date_trunc('month',coalesce(paid_at,due_at,created_at)) month,coalesce(sum(amount_minor) filter(where direction='income' and status<>'cancelled'),0)::bigint income_minor,coalesce(sum(amount_minor) filter(where direction='expense' and status<>'cancelled'),0)::bigint expense_minor,coalesce(sum(amount_minor) filter(where direction='income' and status in ('open','overdue','planned')),0)::bigint receivable_minor,coalesce(sum(amount_minor) filter(where direction='expense' and status in ('open','overdue','planned')),0)::bigint payable_minor from ledger_entries where workspace_id=$1 and coalesce(paid_at,due_at,created_at)>=date_trunc('month',now())-($2::text||' months')::interval group by 1 order by 1`,[ctx.workspaceId,String(months)])});
app.get('/v1/recurring-rules',async req=>{const ctx=await workspaceContext(req,'finance.read');return query<any>(`select * from recurring_rules where workspace_id=$1 order by active desc,next_run_at`,[ctx.workspaceId])});
app.post('/v1/recurring-rules',async req=>{const ctx=await workspaceContext(req,'finance.write');const input=z.object({contactId:uuid.optional().nullable(),accountId:uuid.optional().nullable(),direction:z.enum(['income','expense']),category:z.string().min(1),description:z.string().min(1),amountMinor:z.number().int().positive(),currency:z.string().length(3).default('BRL'),frequency:z.enum(['weekly','monthly','yearly']),intervalCount:z.number().int().positive().default(1),nextRunAt:z.string().datetime(),endsAt:z.string().datetime().optional().nullable(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const rows=await query<any>(`insert into recurring_rules(workspace_id,contact_id,account_id,direction,category,description,amount_minor,currency,frequency,interval_count,next_run_at,ends_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning *`,[ctx.workspaceId,input.contactId||null,input.accountId||null,input.direction,input.category,input.description,input.amountMinor,input.currency,input.frequency,input.intervalCount,input.nextRunAt,input.endsAt||null,JSON.stringify(input.metadata)]);await audit(ctx,'recurrence.created','recurring_rule',rows[0].id,null,rows[0]);return rows[0]});
app.post('/v1/recurring-rules/run',async req=>{const ctx=await workspaceContext(req,'finance.write');const horizon=z.object({days:z.number().int().min(0).max(90).default(30)}).parse(req.body||{}).days;const until=new Date(Date.now()+horizon*86400000);const rules=await query<any>(`select * from recurring_rules where workspace_id=$1 and active=true and next_run_at<=$2 and (ends_at is null or next_run_at<=ends_at) order by next_run_at limit 200`,[ctx.workspaceId,until.toISOString()]);let created=0;for(const rule of rules){let next=new Date(rule.next_run_at);let safety=0;while(next<=until&&(!rule.ends_at||next<=new Date(rule.ends_at))&&safety++<24){const key=`recurring:${rule.id}:${next.toISOString()}`;const exists=await query<any>(`select 1 from ledger_entries where workspace_id=$1 and recurrence_key=$2`,[ctx.workspaceId,key]);if(!exists.length){await query(`insert into ledger_entries(workspace_id,contact_id,account_id,direction,category,description,amount_minor,currency,status,due_at,recurrence_key,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,'open',$9,$10,$11)`,[ctx.workspaceId,rule.contact_id,rule.account_id,rule.direction,rule.category,rule.description,rule.amount_minor,rule.currency,next.toISOString(),key,JSON.stringify({...rule.metadata,recurringRuleId:rule.id})]);created++}next=advance(next,rule.frequency,Number(rule.interval_count))}await query(`update recurring_rules set next_run_at=$3,updated_at=now(),active=case when ends_at is not null and $3>ends_at then false else active end where id=$1 and workspace_id=$2`,[rule.id,ctx.workspaceId,next.toISOString()])}await audit(ctx,'recurrence.run','workspace',ctx.workspaceId,null,{created,horizonDays:horizon});return {created,processedRules:rules.length}});

// --- Command Center, approvals, policies, audit and usage ----------------------
app.post('/v1/events',async req=>{const ctx=await workspaceContext(req,'command.read');const input=z.object({type:z.string().min(3),source:z.string().default('api'),subjectType:z.string().optional().nullable(),subjectId:uuid.optional().nullable(),payload:z.record(z.string(),z.unknown()).default({}),correlationId:z.string().optional().nullable()}).parse(req.body);return emit(ctx.workspaceId,input.type,input.source,input.subjectType||null,input.subjectId||null,input.payload,input.correlationId||null)});
app.get('/v1/command/actions',async req=>{const ctx=await workspaceContext(req,'command.read');const includeDone=String((req.query as any)?.includeDone||'false')==='true';return query<any>(`select * from command_actions where workspace_id=$1 and ($2::boolean or status not in ('done','dismissed','rejected')) order by case priority when 'critical' then 1 when 'high' then 2 when 'normal' then 3 else 4 end,created_at desc limit 300`,[ctx.workspaceId,includeDone])});
app.post('/v1/command/actions/:id/decision',async req=>{const ctx=await workspaceContext(req,'command.decide');const id=uuid.parse((req.params as any).id);const input=z.object({decision:z.enum(['approved','rejected','dismissed'])}).parse(req.body);const before=(await query<any>(`select * from command_actions where id=$1 and workspace_id=$2`,[id,ctx.workspaceId]))[0];if(!before)throw new ApiError(404,'not_found','Ação não encontrada.');if(before.approval_id&&input.decision!=='dismissed')await query(`update approval_requests set status=$3,decided_by=$4,decided_at=now() where id=$1 and workspace_id=$2 and status='pending'`,[before.approval_id,ctx.workspaceId,input.decision,ctx.user.id]);const status=input.decision==='dismissed'?'dismissed':input.decision;const rows=await query<any>(`update command_actions set status=$3,updated_at=now() where id=$1 and workspace_id=$2 returning *`,[id,ctx.workspaceId,status]);await audit(ctx,'command.decision','command_action',id,before,rows[0],{decision:input.decision});return rows[0]});
app.get('/v1/approvals',async req=>{const ctx=await workspaceContext(req,'command.read');return query<any>(`select * from approval_requests where workspace_id=$1 and status='pending' order by created_at desc limit 200`,[ctx.workspaceId])});
app.post('/v1/approvals/:id/decision',async req=>{const ctx=await workspaceContext(req,'command.decide');const id=uuid.parse((req.params as any).id);const input=z.object({decision:z.enum(['approved','rejected'])}).parse(req.body);const rows=await query<any>(`update approval_requests set status=$3,decided_by=$4,decided_at=now() where workspace_id=$1 and id=$2 and status='pending' returning *`,[ctx.workspaceId,id,input.decision,ctx.user.id]);if(rows.length)await query(`update command_actions set status=$3,updated_at=now() where workspace_id=$1 and approval_id=$2`,[ctx.workspaceId,id,input.decision]);if(!rows.length)throw new ApiError(404,'not_found_or_decided','Aprovação não encontrada ou já decidida.');await audit(ctx,'approval.decided','approval_request',id,null,rows[0],{decision:input.decision});return rows[0]});
app.get('/v1/autonomy-policies',async req=>{const ctx=await workspaceContext(req,'command.read');return query<any>(`select * from autonomy_policies where workspace_id=$1 order by action_type`,[ctx.workspaceId])});
app.put('/v1/autonomy-policies/:actionType',async req=>{const ctx=await workspaceContext(req,'autonomy.manage');const actionType=decodeURIComponent(String((req.params as any).actionType));const input=z.object({mode:z.enum(['automatic','notify','approval_required']),maxAmountMinor:z.number().int().nonnegative().optional().nullable(),allowedChannels:z.array(z.string()).optional().nullable(),conditions:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const before=(await query<any>(`select * from autonomy_policies where workspace_id=$1 and action_type=$2`,[ctx.workspaceId,actionType]))[0]||null;const rows=await query<any>(`insert into autonomy_policies(workspace_id,action_type,mode,max_amount_minor,allowed_channels,conditions) values($1,$2,$3,$4,$5,$6) on conflict(workspace_id,action_type) do update set mode=excluded.mode,max_amount_minor=excluded.max_amount_minor,allowed_channels=excluded.allowed_channels,conditions=excluded.conditions,updated_at=now() returning *`,[ctx.workspaceId,actionType,input.mode,input.maxAmountMinor||null,input.allowedChannels||null,JSON.stringify(input.conditions)]);await audit(ctx,'autonomy.updated','autonomy_policy',rows[0].id,before,rows[0]);return rows[0]});
app.get('/v1/audit',async req=>{const ctx=await workspaceContext(req,'workspace.manage');return query<any>(`select * from audit_log where workspace_id=$1 order by occurred_at desc limit 500`,[ctx.workspaceId])});
app.get('/v1/integrations',async req=>{const ctx=await workspaceContext(req,'integrations.read');return query<any>(`select id,provider,status,external_account_ref,capabilities,config,connected_at,updated_at from integrations where workspace_id=$1 order by provider`,[ctx.workspaceId])});
app.post('/v1/usage',async req=>{const ctx=await workspaceContext(req,'usage.read');const input=z.object({capability:z.string(),operation:z.string(),units:z.number().nonnegative(),unitName:z.string(),provider:z.string().optional().nullable(),costMinorEstimate:z.number().int().nonnegative().optional().nullable(),currency:z.string().length(3).default('BRL'),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body);const rows=await query<any>(`insert into usage_events(workspace_id,capability,operation,units,unit_name,provider,cost_minor_estimate,currency,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[ctx.workspaceId,input.capability,input.operation,input.units,input.unitName,input.provider||null,input.costMinorEstimate||null,input.currency,JSON.stringify(input.metadata)]);return rows[0]});
app.get('/v1/usage/summary',async req=>{const ctx=await workspaceContext(req,'usage.read');return query<any>(`select capability,provider,sum(units)::float units,max(unit_name) unit_name,coalesce(sum(cost_minor_estimate),0)::bigint cost_minor from usage_events where workspace_id=$1 and occurred_at>=date_trunc('month',now()) group by capability,provider order by cost_minor desc,capability`,[ctx.workspaceId])});
app.get('/v1/dashboard',async req=>{const ctx=await workspaceContext(req,'workspace.read');const [crm,finance,actions,approvals,tasks,appointments,usage]=await Promise.all([query<any>(`select count(*)::int deals,count(*) filter(where stage not in ('won','lost'))::int open_deals,coalesce(sum(value_minor) filter(where stage not in ('won','lost')),0)::bigint open_pipeline_minor,count(*) filter(where stage='won' and updated_at>=date_trunc('month',now()))::int won_month from crm_deals where workspace_id=$1`,[ctx.workspaceId]),financeSummary(ctx.workspaceId),query<any>(`select count(*)::int open_actions from command_actions where workspace_id=$1 and status in ('open','approved','executing')`,[ctx.workspaceId]),query<any>(`select count(*)::int pending_approvals from approval_requests where workspace_id=$1 and status='pending'`,[ctx.workspaceId]),query<any>(`select count(*)::int due_tasks from tasks where workspace_id=$1 and status in ('todo','doing') and due_at<=now()+interval '24 hours'`,[ctx.workspaceId]),query<any>(`select count(*)::int today_appointments from appointments where workspace_id=$1 and starts_at>=date_trunc('day',now()) and starts_at<date_trunc('day',now())+interval '1 day' and status not in ('cancelled')`,[ctx.workspaceId]),query<any>(`select capability,sum(units)::float units,coalesce(sum(cost_minor_estimate),0)::bigint cost_minor from usage_events where workspace_id=$1 and occurred_at>=date_trunc('month',now()) group by capability order by cost_minor desc`,[ctx.workspaceId])]);return {workspace:{id:ctx.workspaceId,name:ctx.workspaceName,role:ctx.role},crm:crm[0],finance,command:actions[0],approvals:approvals[0],tasks:tasks[0],appointments:appointments[0],usage}});

app.setErrorHandler((error,_req,reply)=>{app.log.error(error);const anyError=error as any;const status=Number(anyError?.statusCode||anyError?.status||((anyError?.issues)?400:500));reply.code(status).send({error:anyError?.code||'request_failed',message:error instanceof Error?error.message:String(error),issues:anyError?.issues});});

async function financeSummary(workspaceId:string){const rows=await query<any>(`select coalesce(sum(amount_minor) filter(where direction='income' and status='paid'),0)::bigint income_paid_minor,coalesce(sum(amount_minor) filter(where direction='expense' and status='paid'),0)::bigint expense_paid_minor,coalesce(sum(amount_minor) filter(where direction='income' and status in ('open','overdue')),0)::bigint receivable_minor,coalesce(sum(amount_minor) filter(where direction='expense' and status in ('open','overdue')),0)::bigint payable_minor,count(*) filter(where status='overdue')::int overdue_count from ledger_entries where workspace_id=$1`,[workspaceId]);return rows[0]}
async function audit(ctx:{workspaceId:string;user:{id:string}},action:string,subjectType:string,subjectId:string,before:unknown,after:unknown,metadata:Record<string,unknown>={}){await query(`insert into audit_log(workspace_id,actor_type,actor_ref,action,subject_type,subject_id,before_state,after_state,metadata) values($1,'user',$2,$3,$4,$5,$6,$7,$8)`,[ctx.workspaceId,ctx.user.id,action,subjectType,subjectId,before?JSON.stringify(before):null,after?JSON.stringify(after):null,JSON.stringify(metadata)]).catch(()=>null)}
async function emit(workspaceId:string,type:string,source:string,subjectType:string|null,subjectId:string|null,payload:Record<string,unknown>,correlationId:string|null=null){const id=randomUUID();const occurredAt=new Date().toISOString();const rows=await query<any>(`insert into business_events(id,workspace_id,type,source,subject_type,subject_id,payload,correlation_id,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[id,workspaceId,type,source,subjectType,subjectId,JSON.stringify(payload),correlationId,occurredAt]);const event:BusinessEvent={id,workspaceId,type,source,subjectType,subjectId,payload,correlationId,occurredAt};const action=await processBusinessEvent(event).catch(error=>({error:error instanceof Error?error.message:String(error)}));return {event:rows[0],action}}
function advance(date:Date,frequency:string,count:number){const next=new Date(date);if(frequency==='weekly')next.setUTCDate(next.getUTCDate()+7*count);else if(frequency==='yearly')next.setUTCFullYear(next.getUTCFullYear()+count);else next.setUTCMonth(next.getUTCMonth()+count);return next}

await app.listen({port,host:'0.0.0.0'});
